// 0
[mapelement_0]
category=category_1049
graphic="mapfunction,0"
mapfunction=yes
vis=3

// 1
[mapelement_1]
category=category_1050
graphic="mapfunction,1"
mapfunction=yes
vis=3

// 2
[mapelement_2]
category=category_1052
graphic="mapfunction,2"
mapfunction=yes
vis=3

// 3
[mapelement_3]
category=category_1053
graphic="mapfunction,3"
mapfunction=yes
vis=3

// 4
[mapelement_4]
category=category_1054
graphic="mapfunction,4"
mapfunction=yes
vis=3

// 5
[mapelement_5]
category=category_1055
graphic="mapfunction,5"
mapfunction=yes
vis=3

// 6
[mapelement_6]
text=The Node
size=0
colour=16777215
category=category_1129
mapfunction=no

// 7
[mapelement_7]
category=category_1057
graphic="mapfunction,7"
mapfunction=yes
vis=3

// 8
[mapelement_8]
category=category_1058
graphic="mapfunction,8"
mapfunction=yes
vis=3

// 9
[mapelement_9]
category=category_1059
graphic="mapfunction,9"
mapfunction=yes
vis=3

// 10
[mapelement_10]
category=category_1060
graphic="mapfunction,10"
mapfunction=yes
vis=3

// 11
[mapelement_11]
category=category_1061
graphic="mapfunction,11"
mapfunction=yes
vis=3

// 12
[mapelement_12]
category=category_1062
graphic="mapfunction,12"
mapfunction=yes
vis=3

// 13
[mapelement_13]
category=category_1062
graphic="mapfunction,86"
op1=Open
mapfunction=no
vis=3
unknown17=Map

// 14
[mapelement_14]
category=category_1063
graphic="mapfunction,87"
op1=Open
mapfunction=no
unknown17=Map

// 15
[mapelement_15]
category=category_1064
graphic="mapfunction,13"
mapfunction=yes
vis=3

// 16
[mapelement_16]
category=category_1065
graphic="mapfunction,14"
mapfunction=yes
vis=3

// 17
[mapelement_17]
category=category_1066
graphic="mapfunction,15"
mapfunction=yes
vis=3

// 18
[mapelement_18]
category=category_1067
graphic="mapfunction,16"
mapfunction=yes
vis=3

// 19
[mapelement_19]
category=category_1068
graphic="mapfunction,17"
mapfunction=yes
vis=3

// 20
[mapelement_20]
category=category_1069
graphic="mapfunction,18"
mapfunction=yes
vis=3

// 21
[mapelement_21]
category=category_1070
graphic="mapfunction,19"
mapfunction=yes
vis=3

// 22
[mapelement_22]
category=category_1071
graphic="mapfunction,20"
mapfunction=yes
vis=3

// 23
[mapelement_23]
category=category_1072
graphic="mapfunction,21"
mapfunction=yes
vis=3

// 24
[mapelement_24]
category=category_1073
graphic="mapfunction,22"
mapfunction=yes
vis=3

// 25
[mapelement_25]
category=category_1074
graphic="mapfunction,23"
mapfunction=yes
vis=3

// 26
[mapelement_26]
category=category_1075
graphic="mapfunction,24"
mapfunction=yes
vis=3

// 27
[mapelement_27]
category=category_1076
graphic="mapfunction,25"
mapfunction=yes
vis=3

// 28
[mapelement_28]
category=category_1077
graphic="mapfunction,26"
mapfunction=yes
vis=3

// 29
[mapelement_29]
category=category_1078
graphic="mapfunction,27"
mapfunction=yes
vis=3

// 30
[mapelement_30]
category=category_1079
graphic="mapfunction,28"
mapfunction=yes
vis=3

// 31
[mapelement_31]
category=category_1080
graphic="mapfunction,29"
mapfunction=yes
vis=3

// 32
[mapelement_32]
category=category_1081
graphic="mapfunction,30"
mapfunction=yes
vis=3

// 33
[mapelement_33]
category=category_1082
graphic="mapfunction,31"
mapfunction=yes
vis=3

// 34
[mapelement_34]
category=category_1083
graphic="mapfunction,32"
mapfunction=yes
vis=3

// 35
[mapelement_35]
category=category_1084
graphic="mapfunction,33"
mapfunction=yes
vis=3

// 36
[mapelement_36]
category=category_1085
graphic="mapfunction,34"
mapfunction=yes
vis=3

// 37
[mapelement_37]
category=category_1086
graphic="mapfunction,35"
mapfunction=yes
vis=3

// 38
[mapelement_38]
category=category_1081
graphic="mapfunction,36"
mapfunction=yes
vis=3

// 39
[mapelement_39]
category=category_1081
graphic="mapfunction,37"
mapfunction=yes
vis=3

// 40
[mapelement_40]
category=category_1087
graphic="mapfunction,38"
mapfunction=yes
vis=3

// 41
[mapelement_41]
category=category_1088
graphic="mapfunction,39"
mapfunction=yes
vis=3

// 42
[mapelement_42]
category=category_1089
graphic="mapfunction,40"
mapfunction=yes
vis=3

// 43
[mapelement_43]
category=category_1090
graphic="mapfunction,41"
mapfunction=yes
vis=3

// 44
[mapelement_44]
category=category_1091
graphic="mapfunction,42"
mapfunction=yes
vis=3

// 45
[mapelement_45]
category=category_1092
graphic="mapfunction,43"
mapfunction=yes
vis=3

// 46
[mapelement_46]
category=category_1093
graphic="mapfunction,44"
mapfunction=yes
vis=3

// 47
[mapelement_47]
category=category_1094
graphic="mapfunction,45"
mapfunction=yes
vis=3

// 48
[mapelement_48]
category=category_1095
graphic="mapfunction,46"
mapfunction=yes
vis=3

// 49
[mapelement_49]
category=category_1096
graphic="mapfunction,47"
mapfunction=yes
vis=3

// 50
[mapelement_50]
category=category_1097
graphic="mapfunction,48"
mapfunction=yes
vis=3

// 51
[mapelement_51]
category=category_1098
graphic="mapfunction,49"
mapfunction=yes
vis=3

// 52
[mapelement_52]
category=category_1081
graphic="mapfunction,50"
mapfunction=yes
vis=3

// 53
[mapelement_53]
category=category_1099
graphic="mapfunction,51"
mapfunction=yes
vis=3

// 54
[mapelement_54]
category=category_1100
graphic="mapfunction,52"
mapfunction=yes
vis=3

// 55
[mapelement_55]
category=category_1101
graphic="mapfunction,53"
mapfunction=yes
vis=3

// 56
[mapelement_56]
category=category_1102
graphic="mapfunction,54"
mapfunction=yes
vis=3

// 57
[mapelement_57]
text=Weiss
size=1
colour=16777215
category=category_1129
mapfunction=no

// 58
[mapelement_58]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 59
[mapelement_59]
category=category_1105
graphic="mapfunction,57"
mapfunction=yes
vis=3

// 60
[mapelement_60]
category=category_1106
graphic="mapfunction,58"
mapfunction=yes
vis=3

// 61
[mapelement_61]
category=category_1107
graphic="mapfunction,59"
mapfunction=yes
vis=3

// 62
[mapelement_62]
category=category_1108
graphic="mapfunction,60"
mapfunction=yes
vis=3

// 63
[mapelement_63]
category=category_1109
graphic="mapfunction,61"
mapfunction=yes
vis=3

// 64
[mapelement_64]
category=category_1110
graphic="mapfunction,62"
mapfunction=yes
vis=3

// 65
[mapelement_65]
category=category_1111
graphic="mapfunction,63"
mapfunction=yes
vis=3

// 66
[mapelement_66]
category=category_1112
graphic="mapfunction,64"
mapfunction=yes
vis=3

// 67
[mapelement_67]
category=category_1113
graphic="mapfunction,65"
mapfunction=yes
vis=3

// 68
[mapelement_68]
category=category_1114
graphic="mapfunction,67"
mapfunction=yes
vis=3

// 69
[mapelement_69]
category=category_1115
graphic="mapfunction,68"
mapfunction=yes
vis=3

// 70
[mapelement_70]
category=category_1116
graphic="mapfunction,69"
mapfunction=yes
vis=3

// 71
[mapelement_71]
category=category_1117
graphic="mapfunction,70"
mapfunction=yes
vis=3

// 72
[mapelement_72]
category=category_1118
graphic="mapfunction,71"
mapfunction=yes
vis=3

// 73
[mapelement_73]
category=category_1119
graphic="mapfunction,72"
mapfunction=yes
vis=3

// 74
[mapelement_74]
category=category_1120
graphic="mapfunction,73"
mapfunction=yes
vis=3

// 75
[mapelement_75]
category=category_1121
graphic="mapfunction,74"
mapfunction=yes
vis=3

// 76
[mapelement_76]
category=category_1122
graphic="mapfunction,75"
mapfunction=yes
vis=3

// 77
[mapelement_77]
category=category_1123
graphic="mapfunction,76"
mapfunction=yes
vis=3

// 78
[mapelement_78]
text=Salt Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 79
[mapelement_79]
category=category_1125
graphic="mapfunction,78"
mapfunction=yes
vis=3

// 80
[mapelement_80]
category=category_1125
graphic="mapfunction,79"
mapfunction=yes
vis=3

// 81
[mapelement_81]
category=category_1125
graphic="mapfunction,80"
mapfunction=yes
vis=3

// 82
[mapelement_82]
category=category_1125
graphic="mapfunction,81"
mapfunction=yes
vis=3

// 83
[mapelement_83]
category=category_1125
graphic="mapfunction,82"
mapfunction=yes
vis=3

// 84
[mapelement_84]
category=category_1126
graphic="mapfunction,83"
mapfunction=yes
vis=3

// 85
[mapelement_85]
text=Scurrius<br>The Rat King
size=0
colour=16777215
category=category_1129
mapfunction=no

// 86
[mapelement_86]
category=category_1128
graphic="mapfunction,132"
mapfunction=yes
vis=3

// 87
[mapelement_87]
text=Lumbridge
size=1
colour=16777215
category=category_1129
mapfunction=no

// 88
[mapelement_88]
text=Varrock
size=1
colour=16777215
category=category_1129
mapfunction=no

// 89
[mapelement_89]
text=Kingdom of<br>Misthalin
size=2
colour=16750623
category=category_1129
mapfunction=no

// 90
[mapelement_90]
text=Al Kharid
size=1
colour=16777215
category=category_1129
mapfunction=no

// 91
[mapelement_91]
category=category_1716
graphic="mapfunction,85"
mapfunction=yes
vis=3

// 92
[mapelement_92]
text=Shantay<br>Pass
size=0
colour=16777215
category=category_1129
mapfunction=no

// 93
[mapelement_93]
text=Toll<br>Gate
size=0
colour=16777215
category=category_1129
mapfunction=no

// 94
[mapelement_94]
text=Tutorial Island
size=1
colour=16777215
category=category_1129
mapfunction=no

// 95
[mapelement_95]
text=Port<br>Sarim
size=1
colour=16777215
category=category_1129
mapfunction=no

// 96
[mapelement_96]
text=Falador
size=1
colour=16777215
category=category_1129
mapfunction=no

// 97
[mapelement_97]
text=Edgeville
size=1
colour=16777215
category=category_1129
mapfunction=no

// 98
[mapelement_98]
text=Brimhaven
size=1
colour=16777215
category=category_1129
mapfunction=no

// 99
[mapelement_99]
text=Karamja
size=2
colour=16750623
category=category_1129
mapfunction=no

// 100
[mapelement_100]
text=Crandor
size=1
colour=16777215
category=category_1129
mapfunction=no

// 101
[mapelement_101]
text=Entrana
size=1
colour=16777215
category=category_1129
mapfunction=no

// 102
[mapelement_102]
text=Draynor<br>Village
size=1
colour=16777215
category=category_1129
mapfunction=no

// 103
[mapelement_103]
text=Jail
size=0
colour=16777215
category=category_1129
mapfunction=no

// 104
[mapelement_104]
text=Market
size=0
colour=16777215
category=category_1129
mapfunction=no

// 105
[mapelement_105]
text=Draynor<br>Manor
size=0
colour=16777215
category=category_1129
mapfunction=no

// 106
[mapelement_106]
text=Barbarian<br>Village
size=1
colour=16777215
category=category_1129
mapfunction=no

// 107
[mapelement_107]
text=Desert Mining<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 108
[mapelement_108]
text=Bedabin<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 109
[mapelement_109]
text=Exam Centre
size=0
colour=16777215
category=category_1129
mapfunction=no

// 110
[mapelement_110]
text=Digsite
size=0
colour=16777215
category=category_1129
mapfunction=no

// 111
[mapelement_111]
text=Lumber Yard
size=0
colour=16777215
category=category_1129
mapfunction=no

// 112
[mapelement_112]
text=Palace
size=0
colour=16777215
category=category_1129
mapfunction=no

// 113
[mapelement_113]
text=Grand Exchange
size=0
colour=16777215
category=category_1129
mapfunction=no

// 114
[mapelement_114]
text=Cooks'<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 115
[mapelement_115]
text=Monastery
size=0
colour=16777215
category=category_1129
mapfunction=no

// 116
[mapelement_116]
text=Dwarven<br>Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 117
[mapelement_117]
text=Ice<br>Mountain
size=1
colour=16777215
category=category_1129
mapfunction=no

// 118
[mapelement_118]
text=Black Knights'<br>Fortress
size=0
colour=16777215
category=category_1129
mapfunction=no

// 119
[mapelement_119]
text=Goblin<br>Village
size=0
colour=16777215
category=category_1129
mapfunction=no

// 120
[mapelement_120]
text=White Knights'<br>Castle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 121
[mapelement_121]
text=Park
size=0
colour=16777215
category=category_1129
mapfunction=no

// 122
[mapelement_122]
text=Kingdom of<br>Asgarnia
size=2
colour=16750623
category=category_1129
mapfunction=no

// 123
[mapelement_123]
text=Dark Wizards'<br>Tower
size=0
colour=16777215
category=category_1129
mapfunction=no

// 124
[mapelement_124]
text=Slayer<br>Tower
size=0
colour=16777215
category=category_1129
mapfunction=no

// 125
[mapelement_125]
text=Melzar's<br>Maze
size=0
colour=16777215
category=category_1129
mapfunction=no

// 126
[mapelement_126]
text=Rimmington
size=1
colour=16777215
category=category_1129
mapfunction=no

// 127
[mapelement_127]
text=Wizards' Tower
size=0
colour=16777215
category=category_1129
mapfunction=no

// 128
[mapelement_128]
text=Lumbridge<br>Swamp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 129
[mapelement_129]
text=Fishing<br>Platform
size=0
colour=16777215
category=category_1129
mapfunction=no

// 130
[mapelement_130]
text=Tai Bwo<br>Wannai
size=1
colour=16777215
category=category_1129
mapfunction=no

// 131
[mapelement_131]
text=Shilo Village
size=1
colour=16777215
category=category_1129
mapfunction=no

// 132
[mapelement_132]
text=Ship Yard
size=0
colour=16777215
category=category_1129
mapfunction=no

// 133
[mapelement_133]
text=Cairn Isle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 134
[mapelement_134]
text=Kharazi Jungle
size=1
colour=16777215
category=category_1129
mapfunction=no

// 135
[mapelement_135]
text=Chaos<br>Temple
size=0
colour=16777215
category=category_1129
mapfunction=no

// 136
[mapelement_136]
text=Graveyard of<br>Shadows
size=0
colour=16777215
category=category_1129
mapfunction=no

// 137
[mapelement_137]
text=Bandit<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 138
[mapelement_138]
text=Dark Warriors'<br>Fortress
size=0
colour=16777215
category=category_1129
mapfunction=no

// 139
[mapelement_139]
text=Ruins
size=0
colour=16777215
category=category_1129
mapfunction=no

// 140
[mapelement_140]
text=The Forgotten<br>Cemetery
size=0
colour=16777215
category=category_1129
mapfunction=no

// 141
[mapelement_141]
text=Bone Yard
size=0
colour=16777215
category=category_1129
mapfunction=no

// 142
[mapelement_142]
text=Lava Dragon<br>Isle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 143
[mapelement_143]
text=Wilderness
size=2
colour=16750623
category=category_1129
mapfunction=no

// 144
[mapelement_144]
text=Lava Maze
size=0
colour=16777215
category=category_1129
mapfunction=no

// 145
[mapelement_145]
text=Frozen Waste<br>Plateau
size=0
colour=16777215
category=category_1129
mapfunction=no

// 146
[mapelement_146]
text=Agility Training<br>Area
size=0
colour=16777215
category=category_1129
mapfunction=no

// 147
[mapelement_147]
text=Pirates'<br>Hideout
size=0
colour=16777215
category=category_1129
mapfunction=no

// 148
[mapelement_148]
text=Mage Arena
size=0
colour=16777215
category=category_1129
mapfunction=no

// 149
[mapelement_149]
text=Deserted<br>Keep
size=0
colour=16777215
category=category_1129
mapfunction=no

// 150
[mapelement_150]
text=Resource Area
size=0
colour=16777215
category=category_1129
mapfunction=no

// 151
[mapelement_151]
text=Scorpion<br>Pit
size=0
colour=16777215
category=category_1129
mapfunction=no

// 152
[mapelement_152]
text=Rogues' Castle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 153
[mapelement_153]
text=Demonic<br>Ruins
size=0
colour=16777215
category=category_1129
mapfunction=no

// 154
[mapelement_154]
text=Fountain<br>of Rune
size=0
colour=16777215
category=category_1129
mapfunction=no

// 155
[mapelement_155]
text=Bear
size=0
colour=16777215
category=category_1129
mapfunction=no

// 156
[mapelement_156]
text=Spider
size=0
colour=16777215
category=category_1129
mapfunction=no

// 157
[mapelement_157]
text=Heroes'<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 158
[mapelement_158]
text=Druids'<br>Circle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 159
[mapelement_159]
text=Taverley
size=1
colour=16777215
category=category_1129
mapfunction=no

// 160
[mapelement_160]
text=White Wolf<br>Mountain
size=1
colour=16777215
category=category_1129
mapfunction=no

// 161
[mapelement_161]
text=Catherby
size=1
colour=16777215
category=category_1129
mapfunction=no

// 162
[mapelement_162]
text=Camelot<br>Castle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 163
[mapelement_163]
text=Seers'<br>Village
size=1
colour=16777215
category=category_1129
mapfunction=no

// 164
[mapelement_164]
text=Sinclair Mansion
size=0
colour=16777215
category=category_1129
mapfunction=no

// 165
[mapelement_165]
text=Flax
size=0
colour=16777215
category=category_1129
mapfunction=no

// 166
[mapelement_166]
text=Beehives
size=0
colour=16777215
category=category_1129
mapfunction=no

// 167
[mapelement_167]
text=Sorcerer's Tower
size=0
colour=16777215
category=category_1129
mapfunction=no

// 168
[mapelement_168]
text=Keep<br>Le Faye
size=0
colour=16777215
category=category_1129
mapfunction=no

// 169
[mapelement_169]
text=Legends'<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 170
[mapelement_170]
text=Hemenster
size=0
colour=16777215
category=category_1129
mapfunction=no

// 171
[mapelement_171]
text=McGrubor's<br>Wood
size=0
colour=16777215
category=category_1129
mapfunction=no

// 172
[mapelement_172]
text=Coal<br>Trucks
size=0
colour=16777215
category=category_1129
mapfunction=no

// 173
[mapelement_173]
text=Fishing<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 174
[mapelement_174]
text=Kingdom of<br>Kandarin
size=2
colour=16750623
category=category_1129
mapfunction=no

// 175
[mapelement_175]
text=East<br>Ardougne
size=1
colour=16777215
category=category_1129
mapfunction=no

// 176
[mapelement_176]
text=West<br>Ardougne
size=1
colour=16777215
category=category_1129
mapfunction=no

// 177
[mapelement_177]
text=Combat<br>Training<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 178
[mapelement_178]
text=Agility<br>Training<br>Area
size=0
colour=16777215
category=category_1129
mapfunction=no

// 179
[mapelement_179]
text=Tree Gnome<br>Stronghold
size=1
colour=16777215
category=category_1129
mapfunction=no

// 180
[mapelement_180]
text=Grand Tree
size=0
colour=16777215
category=category_1129
mapfunction=no

// 181
[mapelement_181]
text=Swamp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 182
[mapelement_182]
text=Gnome Ball<br>Field
size=0
colour=16777215
category=category_1129
mapfunction=no

// 183
[mapelement_183]
text=Barbarian<br>Outpost
size=0
colour=16777215
category=category_1129
mapfunction=no

// 184
[mapelement_184]
text=Underground<br>Pass
size=0
colour=16777215
category=category_1129
mapfunction=no

// 185
[mapelement_185]
text=Battlefield
size=0
colour=16777215
category=category_1129
mapfunction=no

// 186
[mapelement_186]
text=Baxtorian<br>Falls
size=0
colour=16777215
category=category_1129
mapfunction=no

// 187
[mapelement_187]
text=Tree Gnome<br>Village
size=1
colour=16777215
category=category_1129
mapfunction=no

// 188
[mapelement_188]
text=Fight<br>Arena
size=0
colour=16777215
category=category_1129
mapfunction=no

// 189
[mapelement_189]
text=Port<br>Khazard
size=1
colour=16777215
category=category_1129
mapfunction=no

// 190
[mapelement_190]
text=Yanille
size=1
colour=16777215
category=category_1129
mapfunction=no

// 191
[mapelement_191]
text=Wizards'<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 192
[mapelement_192]
text=Nightmare<br>Zone
size=0
colour=16777215
category=category_1129
mapfunction=no

// 193
[mapelement_193]
text=Observatory
size=0
colour=16777215
category=category_1129
mapfunction=no

// 194
[mapelement_194]
text=Necromancer
size=0
colour=16777215
category=category_1129
mapfunction=no

// 195
[mapelement_195]
text=Gu'Tanoth
size=1
colour=16777215
category=category_1129
mapfunction=no

// 196
[mapelement_196]
text=Feldip<br>Hills
size=2
colour=16750623
category=category_1129
mapfunction=no

// 197
[mapelement_197]
text=Ardougne<br>Zoo
size=0
colour=16777215
category=category_1129
mapfunction=no

// 198
[mapelement_198]
text=Morytania
size=2
colour=16750623
category=category_1129
mapfunction=no

// 199
[mapelement_199]
text=Mort Myre<br>Swamp
size=1
colour=16777215
category=category_1129
mapfunction=no

// 200
[mapelement_200]
text=Canifis
size=1
colour=16777215
category=category_1129
mapfunction=no

// 201
[mapelement_201]
text=River<br>Salve
size=0
colour=16777215
category=category_1129
mapfunction=no

// 202
[mapelement_202]
text=River Lum
size=0
colour=16777215
category=category_1129
mapfunction=no

// 203
[mapelement_203]
text=Crombwick<br>Manor
size=0
colour=16777215
category=category_1129
mapfunction=no

// 204
[mapelement_204]
text=Agility<br>Arena
size=0
colour=16777215
category=category_1129
mapfunction=no

// 205
[mapelement_205]
text=Burthorpe
size=1
colour=16777215
category=category_1129
mapfunction=no

// 206
[mapelement_206]
text=Death<br>Plateau
size=0
colour=16777215
category=category_1129
mapfunction=no

// 207
[mapelement_207]
text=Tirannwn
size=2
colour=16750623
category=category_1129
mapfunction=no

// 208
[mapelement_208]
text=Isafdar
size=1
colour=16777215
category=category_1129
mapfunction=no

// 209
[mapelement_209]
text=Arandar
size=1
colour=16777215
category=category_1129
mapfunction=no

// 210
[mapelement_210]
text=Prifddinas
size=1
colour=16777215
category=category_1129
mapfunction=no

// 211
[mapelement_211]
text=Tyras<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 212
[mapelement_212]
text=Iorwerth<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 213
[mapelement_213]
text=Trollheim
size=0
colour=16777215
category=category_1129
mapfunction=no

// 214
[mapelement_214]
text=Troll<br>Stronghold
size=1
colour=16777215
category=category_1129
mapfunction=no

// 215
[mapelement_215]
text=Mort'ton
size=1
colour=16777215
category=category_1129
mapfunction=no

// 216
[mapelement_216]
text=The<br>Hollows
size=0
colour=16777215
category=category_1129
mapfunction=no

// 217
[mapelement_217]
text=Poison Waste
size=1
colour=16777215
category=category_1129
mapfunction=no

// 218
[mapelement_218]
text=Castle Wars
size=0
colour=16777215
category=category_1129
mapfunction=no

// 219
[mapelement_219]
text=Champions'<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 220
[mapelement_220]
text=Rellekka
size=1
colour=16777215
category=category_1129
mapfunction=no

// 221
[mapelement_221]
text=Golden<br>Apple Tree
size=0
colour=16777215
category=category_1129
mapfunction=no

// 222
[mapelement_222]
text=Lighthouse
size=0
colour=16777215
category=category_1129
mapfunction=no

// 223
[mapelement_223]
text=Fremennik<br>Province
size=2
colour=16750623
category=category_1129
mapfunction=no

// 224
[mapelement_224]
text=Crafting<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 225
[mapelement_225]
text=Haunted<br>Woods
size=1
colour=16777215
category=category_1129
mapfunction=no

// 226
[mapelement_226]
text=Miscellania
size=1
colour=16777215
category=category_1129
mapfunction=no

// 227
[mapelement_227]
text=Etceteria
size=1
colour=16777215
category=category_1129
mapfunction=no

// 228
[mapelement_228]
text=Ape Atoll
size=2
colour=16750623
category=category_1129
mapfunction=no

// 229
[mapelement_229]
text=Crash<br>Island
size=0
colour=16777215
category=category_1129
mapfunction=no

// 230
[mapelement_230]
text=Marim
size=1
colour=16777215
category=category_1129
mapfunction=no

// 231
[mapelement_231]
text=Fenkenstrain's<br>Castle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 232
[mapelement_232]
text=Mausoleum
size=0
colour=16777215
category=category_1129
mapfunction=no

// 233
[mapelement_233]
text=Trollweiss<br>Mountain
size=1
colour=16777215
category=category_1129
mapfunction=no

// 234
[mapelement_234]
text=Abandoned<br>Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 235
[mapelement_235]
text=Ruins of<br>Uzer
size=1
colour=16777215
category=category_1129
mapfunction=no

// 236
[mapelement_236]
text=River<br>Elid
size=0
colour=16777215
category=category_1129
mapfunction=no

// 237
[mapelement_237]
text=Kalphite<br>Lair
size=0
colour=16777215
category=category_1129
mapfunction=no

// 238
[mapelement_238]
text=Pollnivneach
size=1
colour=16777215
category=category_1129
mapfunction=no

// 239
[mapelement_239]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 240
[mapelement_240]
text=Menaphos
size=1
colour=16777215
category=category_1129
mapfunction=no

// 241
[mapelement_241]
text=Sophanem
size=1
colour=16777215
category=category_1129
mapfunction=no

// 242
[mapelement_242]
text=Jaleustrophos<br>Pyramid
size=0
colour=16777215
category=category_1129
mapfunction=no

// 243
[mapelement_243]
text=Graveyard
size=0
colour=16777215
category=category_1129
mapfunction=no

// 244
[mapelement_244]
text=Port<br>Phasmatys
size=1
colour=16777215
category=category_1129
mapfunction=no

// 245
[mapelement_245]
text=Ectofuntus
size=0
colour=16777215
category=category_1129
mapfunction=no

// 246
[mapelement_246]
text=Mountain<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 247
[mapelement_247]
text=Kharidian<br>Desert
size=2
colour=16750623
category=category_1129
mapfunction=no

// 248
[mapelement_248]
text=Ice path
size=0
colour=16777215
category=category_1129
mapfunction=no

// 249
[mapelement_249]
text=God Wars<br>Dungeon
size=0
colour=16777215
category=category_1129
mapfunction=no

// 250
[mapelement_250]
text=Barrows
size=0
colour=16777215
category=category_1129
mapfunction=no

// 251
[mapelement_251]
text=Jiggig
size=0
colour=16777215
category=category_1129
mapfunction=no

// 252
[mapelement_252]
text=Mudskipper<br>Point
size=0
colour=16777215
category=category_1129
mapfunction=no

// 253
[mapelement_253]
text=Nardah
size=1
colour=16777215
category=category_1129
mapfunction=no

// 254
[mapelement_254]
text=Mage<br>Training<br>Arena
size=0
colour=16777215
category=category_1129
mapfunction=no

// 255
[mapelement_255]
text=Keldagrim<br>Entrance
size=0
colour=16777215
category=category_1129
mapfunction=no

// 256
[mapelement_256]
text=Waterbirth<br>Island
size=0
colour=16777215
category=category_1129
mapfunction=no

// 257
[mapelement_257]
text=Lletya
size=1
colour=16777215
category=category_1129
mapfunction=no

// 258
[mapelement_258]
text=Burgh de Rott
size=1
colour=16777215
category=category_1129
mapfunction=no

// 259
[mapelement_259]
text=Lizards
size=0
colour=16777215
category=category_1129
mapfunction=no

// 260
[mapelement_260]
text=Quarry
size=0
colour=16777215
category=category_1129
mapfunction=no

// 261
[mapelement_261]
text=Outpost
size=0
colour=16777215
category=category_1129
mapfunction=no

// 262
[mapelement_262]
text=Mos Le'Harmless
size=2
colour=16750623
category=category_1129
mapfunction=no

// 263
[mapelement_263]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 264
[mapelement_264]
text=Ranging<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 265
[mapelement_265]
text=Dragontooth<br>Island
size=0
colour=16777215
category=category_1129
mapfunction=no

// 266
[mapelement_266]
text=Piscatoris<br>Fishing<br>Colony
size=0
colour=16777215
category=category_1129
mapfunction=no

// 267
[mapelement_267]
text=Here be<br>penguins
size=0
colour=16777215
category=category_1129
mapfunction=no

// 268
[mapelement_268]
text=Void Knights'<br>Outpost
size=1
colour=16777215
category=category_1129
mapfunction=no

// 269
[mapelement_269]
text=Lunar Isle
size=2
colour=16750623
category=category_1129
mapfunction=no

// 270
[mapelement_270]
text=Pirates' Cove
size=0
colour=16777215
category=category_1129
mapfunction=no

// 271
[mapelement_271]
text=Vultures
size=0
colour=16777215
category=category_1129
mapfunction=no

// 272
[mapelement_272]
text=Port<br>Tyras
size=0
colour=16777215
category=category_1129
mapfunction=no

// 273
[mapelement_273]
text=Castle<br>Drakan
size=0
colour=16777215
category=category_1129
mapfunction=no

// 274
[mapelement_274]
category=category_1250
graphic="mapfunction,88"
mapfunction=yes
vis=3

// 275
[mapelement_275]
text=Meiyerditch
size=1
colour=16777215
category=category_1129
mapfunction=no

// 276
[mapelement_276]
text=Witchaven
size=0
colour=16777215
category=category_1129
mapfunction=no

// 277
[mapelement_277]
text=Warriors'<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 278
[mapelement_278]
text=Musa Point
size=0
colour=16777215
category=category_1129
mapfunction=no

// 279
[mapelement_279]
text=Eagles'<br>Peak
size=1
colour=16777215
category=category_1129
mapfunction=no

// 280
[mapelement_280]
text=Falconer
size=0
colour=16777215
category=category_1129
mapfunction=no

// 281
[mapelement_281]
text=Barbarian<br>Assault
size=0
colour=16777215
category=category_1129
mapfunction=no

// 282
[mapelement_282]
text=Iceberg
size=1
colour=16777215
category=category_1129
mapfunction=no

// 283
[mapelement_283]
text=Pest<br>Control
size=0
colour=16777215
category=category_1129
mapfunction=no

// 284
[mapelement_284]
text=Neitiznot
size=1
colour=16777215
category=category_1129
mapfunction=no

// 285
[mapelement_285]
text=Jatizso
size=1
colour=16777215
category=category_1129
mapfunction=no

// 286
[mapelement_286]
text=Fremennik Isles
size=2
colour=16750623
category=category_1129
mapfunction=no

// 287
[mapelement_287]
text=Tower of<br>Life
size=0
colour=16777215
category=category_1129
mapfunction=no

// 288
[mapelement_288]
text=Clock Tower
size=0
colour=16777215
category=category_1129
mapfunction=no

// 289
[mapelement_289]
text=Harmony
size=1
colour=16777215
category=category_1129
mapfunction=no

// 290
[mapelement_290]
text=Trawler
size=0
colour=16777215
category=category_1129
mapfunction=no

// 291
[mapelement_291]
text=Otto's<br>Grotto
size=0
colour=16777215
category=category_1129
mapfunction=no

// 292
[mapelement_292]
text=Clan Wars
size=0
colour=16777215
category=category_1129
mapfunction=no

// 293
[mapelement_293]
text=Zul-Andra
size=0
colour=16777215
category=category_1129
mapfunction=no

// 294
[mapelement_294]
text=Zulrah's<br>shrine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 295
[mapelement_295]
text=Silvarea
size=0
colour=16777215
category=category_1129
mapfunction=no

// 296
[mapelement_296]
text=Kingdom of<br>Great Kourend
size=2
colour=16750623
category=category_1129
mapfunction=no

// 297
[mapelement_297]
text=Arceuus
size=1
colour=16777215
category=category_1129
mapfunction=no

// 298
[mapelement_298]
text=Hosidius
size=1
colour=16777215
category=category_1129
mapfunction=no

// 299
[mapelement_299]
text=Lovakengj
size=1
colour=16777215
category=category_1129
mapfunction=no

// 300
[mapelement_300]
text=Port<br>Piscarilius
size=1
colour=16777215
category=category_1129
mapfunction=no

// 301
[mapelement_301]
text=Shayzien
size=1
colour=16777215
category=category_1129
mapfunction=no

// 302
[mapelement_302]
text=Library
size=0
colour=16777215
category=category_1129
mapfunction=no

// 303
[mapelement_303]
text=Dark<br>Altar
size=0
colour=16777215
category=category_1129
mapfunction=no

// 304
[mapelement_304]
text=Sulphur<br>Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 305
[mapelement_305]
text=Blast Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 306
[mapelement_306]
text=Lovakite<br>Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 307
[mapelement_307]
text=Tower of<br>Magic
size=0
colour=16777215
category=category_1129
mapfunction=no

// 308
[mapelement_308]
text=Mess
size=0
colour=16777215
category=category_1129
mapfunction=no

// 309
[mapelement_309]
text=Saltpetre
size=0
colour=16777215
category=category_1129
mapfunction=no

// 310
[mapelement_310]
text=Tithe Farm
size=0
colour=16777215
category=category_1129
mapfunction=no

// 311
[mapelement_311]
text=Charcoal<br>Burners
size=0
colour=16777215
category=category_1129
mapfunction=no

// 312
[mapelement_312]
text=Infirmary
size=0
colour=16777215
category=category_1129
mapfunction=no

// 313
[mapelement_313]
text=Lizardman<br>Canyon
size=0
colour=16777215
category=category_1129
mapfunction=no

// 314
[mapelement_314]
text=Combat<br>Ring
size=0
colour=16777215
category=category_1129
mapfunction=no

// 315
[mapelement_315]
text=Graveyard of<br>Heroes
size=0
colour=16777215
category=category_1129
mapfunction=no

// 316
[mapelement_316]
text=Shamans
size=0
colour=16777215
category=category_1129
mapfunction=no

// 317
[mapelement_317]
text=Vinery
size=0
colour=16777215
category=category_1129
mapfunction=no

// 318
[mapelement_318]
text=Woodcutting<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 319
[mapelement_319]
text=Doors of<br>Dinh
size=0
colour=16777215
category=category_1129
mapfunction=no

// 320
[mapelement_320]
text=The<br>Wintertodt
size=0
colour=16777215
category=category_1129
mapfunction=no

// 321
[mapelement_321]
text=Settlement<br>Ruins
size=0
colour=16777215
category=category_1129
mapfunction=no

// 322
[mapelement_322]
text=Fishing Hamlet
size=0
colour=16777215
category=category_1129
mapfunction=no

// 323
[mapelement_323]
text=Land's<br>End
size=0
colour=16777215
category=category_1129
mapfunction=no

// 324
[mapelement_324]
text=Xeric's<br>Look out
size=0
colour=16777215
category=category_1129
mapfunction=no

// 325
[mapelement_325]
text=Kourend<br>Woodland
size=1
colour=16777215
category=category_1129
mapfunction=no

// 326
[mapelement_326]
text=Unmarked<br>Grave
size=0
colour=16777215
category=category_1129
mapfunction=no

// 327
[mapelement_327]
text=Crabclaw<br>Isle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 328
[mapelement_328]
text=Shayziens'<br>Wall
size=0
colour=16777215
category=category_1129
mapfunction=no

// 329
[mapelement_329]
text=Lacerta<br>Falls
size=0
colour=16777215
category=category_1129
mapfunction=no

// 330
[mapelement_330]
text=Xeric's<br>Shrine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 331
[mapelement_331]
text=Lizardman<br>Settlement
size=0
colour=16777215
category=category_1129
mapfunction=no

// 332
[mapelement_332]
text=Mount<br>Quidamortem
size=1
colour=16777215
category=category_1129
mapfunction=no

// 333
[mapelement_333]
text=Chasm of Fire
size=0
colour=16777215
category=category_1129
mapfunction=no

// 334
[mapelement_334]
text=Lower level
size=1
colour=16776960
category=category_1129
mapfunction=no

// 335
[mapelement_335]
text=Middle level
size=1
colour=16776960
category=category_1129
mapfunction=no

// 336
[mapelement_336]
text=Upper level
size=1
colour=16776960
category=category_1129
mapfunction=no

// 337
[mapelement_337]
text=Waterfiends
size=0
colour=16777215
category=category_1129
mapfunction=no

// 338
[mapelement_338]
text=Mithril<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 339
[mapelement_339]
text=Brutal green<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 340
[mapelement_340]
text=Shadow<br>warriors
size=0
colour=16777215
category=category_1129
mapfunction=no

// 341
[mapelement_341]
text=Pit scorpions
size=0
colour=16777215
category=category_1129
mapfunction=no

// 342
[mapelement_342]
text=Hobgoblins
size=0
colour=16777215
category=category_1129
mapfunction=no

// 343
[mapelement_343]
text=Ardougne<br>Sewers
size=0
colour=16777215
category=category_1129
mapfunction=no

// 344
[mapelement_344]
text=Zombies & rocks
size=0
colour=16777215
category=category_1129
mapfunction=no

// 345
[mapelement_345]
text=Rat Pits
size=0
colour=16777215
category=category_1129
mapfunction=no

// 346
[mapelement_346]
text=Bats
size=0
colour=16777215
category=category_1129
mapfunction=no

// 347
[mapelement_347]
text=Ogres
size=0
colour=16777215
category=category_1129
mapfunction=no

// 348
[mapelement_348]
text=Dungeon<br>rats
size=0
colour=16777215
category=category_1129
mapfunction=no

// 349
[mapelement_349]
text=Spiders
size=0
colour=16777215
category=category_1129
mapfunction=no

// 350
[mapelement_350]
text=Here be<br>goblins
size=0
colour=16777215
category=category_1129
mapfunction=no

// 351
[mapelement_351]
text=Skeletal wyverns
size=0
colour=16777215
category=category_1129
mapfunction=no

// 352
[mapelement_352]
text=Pirates
size=0
colour=16777215
category=category_1129
mapfunction=no

// 353
[mapelement_353]
text=Muggers
size=0
colour=16777215
category=category_1129
mapfunction=no

// 354
[mapelement_354]
text=Ice warriors<br>& giants
size=0
colour=16777215
category=category_1129
mapfunction=no

// 355
[mapelement_355]
text=Distillery
size=0
colour=16777215
category=category_1129
mapfunction=no

// 356
[mapelement_356]
text=Dead people
size=0
colour=16777215
category=category_1129
mapfunction=no

// 357
[mapelement_357]
text=Nothing<br>interesting<br>happens<br>here
size=1
colour=16777215
category=category_1129
mapfunction=no

// 358
[mapelement_358]
text=Agility course
size=0
colour=16777215
category=category_1129
mapfunction=no

// 359
[mapelement_359]
text=Wire<br>machine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 360
[mapelement_360]
text=Bone<br>collector
size=0
colour=16777215
category=category_1129
mapfunction=no

// 361
[mapelement_361]
text=Oldak's<br>teleportation<br>laboratory
size=0
colour=16777215
category=category_1129
mapfunction=no

// 362
[mapelement_362]
text=Station
size=0
colour=16777215
category=category_1129
mapfunction=no

// 363
[mapelement_363]
text=Council<br>chamber
size=0
colour=16777215
category=category_1129
mapfunction=no

// 364
[mapelement_364]
text=Ur-tag
size=0
colour=16777215
category=category_1129
mapfunction=no

// 365
[mapelement_365]
text=Ur-meg
size=0
colour=16777215
category=category_1129
mapfunction=no

// 366
[mapelement_366]
text=Ur-zek & Ur-taal
size=0
colour=16777215
category=category_1129
mapfunction=no

// 367
[mapelement_367]
text=Tegdak
size=0
colour=16777215
category=category_1129
mapfunction=no

// 368
[mapelement_368]
text=Ur-vass
size=0
colour=16777215
category=category_1129
mapfunction=no

// 369
[mapelement_369]
text=Nursery
size=0
colour=16777215
category=category_1129
mapfunction=no

// 370
[mapelement_370]
text=Zanik's<br>bedroom
size=0
colour=16777215
category=category_1129
mapfunction=no

// 371
[mapelement_371]
text=Beware of<br>the scorpions
size=0
colour=16777215
category=category_1129
mapfunction=no

// 372
[mapelement_372]
text=Mining Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 373
[mapelement_373]
text=Access to<br>Falador
size=0
colour=16777215
category=category_1129
mapfunction=no

// 374
[mapelement_374]
text=Hammerspike's<br>hangout
size=0
colour=16777215
category=category_1129
mapfunction=no

// 375
[mapelement_375]
text=Boot
size=0
colour=16777215
category=category_1129
mapfunction=no

// 376
[mapelement_376]
text=Kurask
size=0
colour=16777215
category=category_1129
mapfunction=no

// 377
[mapelement_377]
text=Cave crawlers
size=0
colour=16777215
category=category_1129
mapfunction=no

// 378
[mapelement_378]
text=Turoth
size=0
colour=16777215
category=category_1129
mapfunction=no

// 379
[mapelement_379]
text=Basilisks
size=0
colour=16777215
category=category_1129
mapfunction=no

// 380
[mapelement_380]
text=Rock<br>slugs
size=0
colour=16777215
category=category_1129
mapfunction=no

// 381
[mapelement_381]
text=Cockatrice
size=0
colour=16777215
category=category_1129
mapfunction=no

// 382
[mapelement_382]
text=Pyrefiends
size=0
colour=16777215
category=category_1129
mapfunction=no

// 383
[mapelement_383]
text=Jellies
size=0
colour=16777215
category=category_1129
mapfunction=no

// 384
[mapelement_384]
text=Saradomin's<br>Encampment
size=1
colour=16777215
category=category_1129
mapfunction=no

// 385
[mapelement_385]
text=Zamorak's<br>Fortress
size=1
colour=16777215
category=category_1129
mapfunction=no

// 386
[mapelement_386]
text=Armadyl's<br>Eyrie
size=1
colour=16777215
category=category_1129
mapfunction=no

// 387
[mapelement_387]
text=Bandos's<br>Stronghold
size=1
colour=16777215
category=category_1129
mapfunction=no

// 388
[mapelement_388]
text=Queen's<br>Chamber
size=0
colour=16777215
category=category_1129
mapfunction=no

// 389
[mapelement_389]
text=Soldiers
size=0
colour=16777215
category=category_1129
mapfunction=no

// 390
[mapelement_390]
text=Guardians
size=0
colour=16777215
category=category_1129
mapfunction=no

// 391
[mapelement_391]
text=Moss giants
size=0
colour=16777215
category=category_1129
mapfunction=no

// 392
[mapelement_392]
text=Dogs
size=0
colour=16777215
category=category_1129
mapfunction=no

// 393
[mapelement_393]
text=Fire<br>giants
size=0
colour=16777215
category=category_1129
mapfunction=no

// 394
[mapelement_394]
text=Red dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 395
[mapelement_395]
text=Bronze<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 396
[mapelement_396]
text=Iron & steel<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 397
[mapelement_397]
text=Bronze, iron &<br>steel dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 398
[mapelement_398]
text=Greater demons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 399
[mapelement_399]
text=Jogres
size=0
colour=16777215
category=category_1129
mapfunction=no

// 400
[mapelement_400]
text=Elvarg
size=0
colour=16777215
category=category_1129
mapfunction=no

// 401
[mapelement_401]
text=Lesser demons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 402
[mapelement_402]
text=Baby green<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 403
[mapelement_403]
text=Black demons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 404
[mapelement_404]
text=Black<br>demons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 405
[mapelement_405]
text=Red Spiders
size=0
colour=16777215
category=category_1129
mapfunction=no

// 406
[mapelement_406]
text=Skeletons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 407
[mapelement_407]
text=River Kelda
size=0
colour=16777215
category=category_1129
mapfunction=no

// 408
[mapelement_408]
text=Dondakan's<br>rock
size=0
colour=16777215
category=category_1129
mapfunction=no

// 409
[mapelement_409]
text=Minecarts
size=0
colour=16777215
category=category_1129
mapfunction=no

// 410
[mapelement_410]
text=Blast<br>Furnace
size=0
colour=16777215
category=category_1129
mapfunction=no

// 411
[mapelement_411]
text=Brewery
size=0
colour=16777215
category=category_1129
mapfunction=no

// 412
[mapelement_412]
text=Black<br>Guard<br>H.Q.
size=0
colour=16777215
category=category_1129
mapfunction=no

// 413
[mapelement_413]
text=Trolls
size=0
colour=16777215
category=category_1129
mapfunction=no

// 414
[mapelement_414]
text=Exit
size=0
colour=16777215
category=category_1129
mapfunction=no

// 415
[mapelement_415]
text=Terror dogs
size=0
colour=16777215
category=category_1129
mapfunction=no

// 416
[mapelement_416]
text=Essence<br>Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 417
[mapelement_417]
text=Miscellania<br>Expansion
size=0
colour=16777215
category=category_1129
mapfunction=no

// 418
[mapelement_418]
text=Sea snakes
size=0
colour=16777215
category=category_1129
mapfunction=no

// 419
[mapelement_419]
text=H.A.M. Cult
size=0
colour=16777215
category=category_1129
mapfunction=no

// 420
[mapelement_420]
text=Draynor Sewers
size=0
colour=16777215
category=category_1129
mapfunction=no

// 421
[mapelement_421]
text=Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 422
[mapelement_422]
text=Watermill<br>cellar
size=0
colour=16777215
category=category_1129
mapfunction=no

// 423
[mapelement_423]
text=Champions'<br>Challenge
size=0
colour=16777215
category=category_1129
mapfunction=no

// 424
[mapelement_424]
text=Draynor Manor<br>basement
size=0
colour=16777215
category=category_1129
mapfunction=no

// 425
[mapelement_425]
text=VTAM Corporation
size=0
colour=16777215
category=category_1129
mapfunction=no

// 426
[mapelement_426]
text=Bank vault
size=0
colour=16777215
category=category_1129
mapfunction=no

// 427
[mapelement_427]
text=Goblin Maze
size=0
colour=16777215
category=category_1129
mapfunction=no

// 428
[mapelement_428]
text=Chasm of<br>Tears
size=0
colour=16777215
category=category_1129
mapfunction=no

// 429
[mapelement_429]
text=Tears of<br>Guthix
size=0
colour=16777215
category=category_1129
mapfunction=no

// 430
[mapelement_430]
text=Lumbridge<br>Castle<br>cellar
size=0
colour=16777215
category=category_1129
mapfunction=no

// 431
[mapelement_431]
text=Giant frogs
size=0
colour=16777215
category=category_1129
mapfunction=no

// 432
[mapelement_432]
text=Hill giants
size=0
colour=16777215
category=category_1129
mapfunction=no

// 433
[mapelement_433]
text=Chronozon
size=0
colour=16777215
category=category_1129
mapfunction=no

// 434
[mapelement_434]
text=Here be<br>dead stuff
size=0
colour=16777215
category=category_1129
mapfunction=no

// 435
[mapelement_435]
text=Thugs
size=0
colour=16777215
category=category_1129
mapfunction=no

// 436
[mapelement_436]
text=Dave's<br>Basement<br>of Doom
size=0
colour=16777215
category=category_1129
mapfunction=no

// 437
[mapelement_437]
text=Poison spiders
size=0
colour=16777215
category=category_1129
mapfunction=no

// 438
[mapelement_438]
text=Poison<br>spiders
size=0
colour=16777215
category=category_1129
mapfunction=no

// 439
[mapelement_439]
text=Zombies
size=0
colour=16777215
category=category_1129
mapfunction=no

// 440
[mapelement_440]
text=Skeletons<br>& zombies
size=0
colour=16777215
category=category_1129
mapfunction=no

// 441
[mapelement_441]
text=Earth warriors
size=0
colour=16777215
category=category_1129
mapfunction=no

// 442
[mapelement_442]
text=Chaos<br>druids
size=0
colour=16777215
category=category_1129
mapfunction=no

// 443
[mapelement_443]
text=Rats
size=0
colour=16777215
category=category_1129
mapfunction=no

// 444
[mapelement_444]
text=Here be a<br>big mole
size=1
colour=16777215
category=category_1129
mapfunction=no

// 445
[mapelement_445]
text=Motherlode Mine
size=1
colour=16777215
category=category_1129
mapfunction=no

// 446
[mapelement_446]
text=Obstacle<br>course
size=0
colour=16777215
category=category_1129
mapfunction=no

// 447
[mapelement_447]
text=Skullball
size=0
colour=16777215
category=category_1129
mapfunction=no

// 448
[mapelement_448]
text=Shades
size=0
colour=16777215
category=category_1129
mapfunction=no

// 449
[mapelement_449]
text=Here be odd stuff
size=0
colour=16777215
category=category_1129
mapfunction=no

// 450
[mapelement_450]
text=Nechryael
size=0
colour=16777215
category=category_1129
mapfunction=no

// 451
[mapelement_451]
text=Abyssal<br>demons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 452
[mapelement_452]
text=Bloodvelds
size=0
colour=16777215
category=category_1129
mapfunction=no

// 453
[mapelement_453]
text=Gargoyles
size=0
colour=16777215
category=category_1129
mapfunction=no

// 454
[mapelement_454]
text=Aberrant<br>Spectres
size=0
colour=16777215
category=category_1129
mapfunction=no

// 455
[mapelement_455]
text=Ankou
size=0
colour=16777215
category=category_1129
mapfunction=no

// 456
[mapelement_456]
text=Cave horrors<br>&<br>albino bats
size=0
colour=16777215
category=category_1129
mapfunction=no

// 457
[mapelement_457]
text=Altar
size=0
colour=16777215
category=category_1129
mapfunction=no

// 458
[mapelement_458]
text=Lizards &<br>Zamorak fighters
size=0
colour=16777215
category=category_1129
mapfunction=no

// 459
[mapelement_459]
text=War
size=1
colour=16777215
category=category_1129
mapfunction=no

// 460
[mapelement_460]
text=Gift of<br>Peace
size=0
colour=16777215
category=category_1129
mapfunction=no

// 461
[mapelement_461]
text=Famine
size=1
colour=16777215
category=category_1129
mapfunction=no

// 462
[mapelement_462]
text=Grain of<br>Plenty
size=0
colour=16777215
category=category_1129
mapfunction=no

// 463
[mapelement_463]
text=Pestilence
size=1
colour=16777215
category=category_1129
mapfunction=no

// 464
[mapelement_464]
text=Box of<br>Health
size=0
colour=16777215
category=category_1129
mapfunction=no

// 465
[mapelement_465]
text=Death
size=1
colour=16777215
category=category_1129
mapfunction=no

// 466
[mapelement_466]
text=Cradle of<br>Life
size=0
colour=16777215
category=category_1129
mapfunction=no

// 467
[mapelement_467]
text=Cauldron of<br>Thunder
size=0
colour=16777215
category=category_1129
mapfunction=no

// 468
[mapelement_468]
text=Black Knights'<br>Base
size=1
colour=16777215
category=category_1129
mapfunction=no

// 469
[mapelement_469]
text=Hellhounds
size=0
colour=16777215
category=category_1129
mapfunction=no

// 470
[mapelement_470]
text=Fire Obelisk
size=0
colour=16777215
category=category_1129
mapfunction=no

// 471
[mapelement_471]
text=Black dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 472
[mapelement_472]
text=Black<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 473
[mapelement_473]
text=Dramen Tree
size=0
colour=16777215
category=category_1129
mapfunction=no

// 474
[mapelement_474]
text=Animated<br>axes
size=0
colour=16777215
category=category_1129
mapfunction=no

// 475
[mapelement_475]
text=Chaos<br>dwarves
size=0
colour=16777215
category=category_1129
mapfunction=no

// 476
[mapelement_476]
text=Blue<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 477
[mapelement_477]
text=Poisonous<br>scorpions
size=0
colour=16777215
category=category_1129
mapfunction=no

// 478
[mapelement_478]
text=Cyclopes
size=0
colour=16777215
category=category_1129
mapfunction=no

// 479
[mapelement_479]
text=Cyclopes<br>& Axes
size=0
colour=16777215
category=category_1129
mapfunction=no

// 480
[mapelement_480]
text=Ice Queen's<br>Lair
size=0
colour=16777215
category=category_1129
mapfunction=no

// 481
[mapelement_481]
text=Fountain<br>of Heroes
size=0
colour=16777215
category=category_1129
mapfunction=no

// 482
[mapelement_482]
text=Mountain<br>dwarves
size=0
colour=16777215
category=category_1129
mapfunction=no

// 483
[mapelement_483]
text=Nora T. Hagg's<br>cellar
size=0
colour=16777215
category=category_1129
mapfunction=no

// 484
[mapelement_484]
text=Key Master
size=0
colour=16777215
category=category_1129
mapfunction=no

// 485
[mapelement_485]
text=Beware of<br>the dog
size=1
colour=16777215
category=category_1129
mapfunction=no

// 486
[mapelement_486]
text=Anger
size=0
colour=16777215
category=category_1129
mapfunction=no

// 487
[mapelement_487]
text=Hopelessness
size=0
colour=16777215
category=category_1129
mapfunction=no

// 488
[mapelement_488]
text=Confusion
size=0
colour=16777215
category=category_1129
mapfunction=no

// 489
[mapelement_489]
text=Fear
size=0
colour=16777215
category=category_1129
mapfunction=no

// 490
[mapelement_490]
text=Goutweed<br>store
size=0
colour=16777215
category=category_1129
mapfunction=no

// 491
[mapelement_491]
text=Troll<br>generals
size=0
colour=16777215
category=category_1129
mapfunction=no

// 492
[mapelement_492]
text=Burntmeat's<br>Kitchen
size=0
colour=16777215
category=category_1129
mapfunction=no

// 493
[mapelement_493]
text=Fight Pit
size=0
colour=16777215
category=category_1129
mapfunction=no

// 494
[mapelement_494]
text=Fight Cave
size=0
colour=16777215
category=category_1129
mapfunction=no

// 495
[mapelement_495]
text=Sub-level 1
size=1
colour=16776960
category=category_1129
mapfunction=no

// 496
[mapelement_496]
text=Sub-level 2
size=1
colour=16776960
category=category_1129
mapfunction=no

// 497
[mapelement_497]
text=Sub-level 3
size=1
colour=16776960
category=category_1129
mapfunction=no

// 498
[mapelement_498]
text=Sub-level 4
size=1
colour=16776960
category=category_1129
mapfunction=no

// 499
[mapelement_499]
text=Sub-level 5
size=1
colour=16776960
category=category_1129
mapfunction=no

// 500
[mapelement_500]
text=Sub-level 6
size=1
colour=16776960
category=category_1129
mapfunction=no

// 501
[mapelement_501]
text=Dagannoth
size=0
colour=16777215
category=category_1129
mapfunction=no

// 502
[mapelement_502]
text=Giant rock crabs
size=0
colour=16777215
category=category_1129
mapfunction=no

// 503
[mapelement_503]
text=Giant<br>rock crabs
size=0
colour=16777215
category=category_1129
mapfunction=no

// 504
[mapelement_504]
text=Rock lobsters
size=0
colour=16777215
category=category_1129
mapfunction=no

// 505
[mapelement_505]
text=Rock<br>lobsters
size=0
colour=16777215
category=category_1129
mapfunction=no

// 506
[mapelement_506]
text=Wallasalki
size=0
colour=16777215
category=category_1129
mapfunction=no

// 507
[mapelement_507]
text=Dagannoth Kings
size=0
colour=16777215
category=category_1129
mapfunction=no

// 508
[mapelement_508]
text=Shadow<br>spiders
size=0
colour=16777215
category=category_1129
mapfunction=no

// 509
[mapelement_509]
text=Agility<br>course<br>spikes
size=0
colour=16777215
category=category_1129
mapfunction=no

// 510
[mapelement_510]
text=Mage Arena<br>bank
size=0
colour=16777215
category=category_1129
mapfunction=no

// 511
[mapelement_511]
text=King<br>Black<br>Dragon
size=0
colour=16777215
category=category_1129
mapfunction=no

// 512
[mapelement_512]
text=Corporeal<br>Beast
size=0
colour=16777215
category=category_1129
mapfunction=no

// 513
[mapelement_513]
text=Salarin the<br>Twisted
size=0
colour=16777215
category=category_1129
mapfunction=no

// 514
[mapelement_514]
text=Smoke devils
size=0
colour=16777215
category=category_1129
mapfunction=no

// 515
[mapelement_515]
text=Thermonuclear<br>Smoke Devil
size=0
colour=16777215
category=category_1129
mapfunction=no

// 516
[mapelement_516]
text=Throne room
size=0
colour=16777215
category=category_1129
mapfunction=no

// 517
[mapelement_517]
text=Beware of the<br>mushrooms
size=0
colour=16777215
category=category_1129
mapfunction=no

// 518
[mapelement_518]
text=Shrine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 519
[mapelement_519]
text=Otherworldly<br>beings
size=0
colour=16777215
category=category_1129
mapfunction=no

// 520
[mapelement_520]
text=Puro-puro
size=0
colour=16777215
category=category_1129
mapfunction=no

// 521
[mapelement_521]
text=Tanglefeet
size=0
colour=16777215
category=category_1129
mapfunction=no

// 522
[mapelement_522]
text=Brimstail
size=0
colour=16777215
category=category_1129
mapfunction=no

// 523
[mapelement_523]
text=Voice of Yama
size=0
colour=16777215
category=category_1129
mapfunction=no

// 524
[mapelement_524]
text=Ents
size=0
colour=16777215
category=category_1129
mapfunction=no

// 525
[mapelement_525]
text=Brutal black, blue<br>& red dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 526
[mapelement_526]
text=Bronze & iron<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 527
[mapelement_527]
text=Steel<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 528
[mapelement_528]
text=Dark<br>beasts
size=0
colour=16777215
category=category_1129
mapfunction=no

// 529
[mapelement_529]
text=Ghosts
size=0
colour=16777215
category=category_1129
mapfunction=no

// 530
[mapelement_530]
text=Dust devils
size=0
colour=16777215
category=category_1129
mapfunction=no

// 531
[mapelement_531]
text=Sand<br>crabs
size=0
colour=16777215
category=category_1129
mapfunction=no

// 532
[mapelement_532]
text=Spectres
size=0
colour=16777215
category=category_1129
mapfunction=no

// 533
[mapelement_533]
text=Banshees
size=0
colour=16777215
category=category_1129
mapfunction=no

// 534
[mapelement_534]
text=Mor Ul Rek
size=1
colour=16777215
category=category_1129
mapfunction=no

// 535
[mapelement_535]
text=The Inferno
size=0
colour=16777215
category=category_1129
mapfunction=no

// 536
[mapelement_536]
text=Lizardman<br>Caves
size=0
colour=16777215
category=category_1129
mapfunction=no

// 537
[mapelement_537]
text=Underwater
size=1
colour=16777215
category=category_1129
mapfunction=no

// 538
[mapelement_538]
text=Wyverns
size=0
colour=16777215
category=category_1129
mapfunction=no

// 539
[mapelement_539]
text=Wyverns<br>Task Only
size=0
colour=16777215
category=category_1129
mapfunction=no

// 540
[mapelement_540]
text=Volcano Mine
size=1
colour=16777215
category=category_1129
mapfunction=no

// 541
[mapelement_541]
text=A
size=0
colour=16777215
category=category_1129
mapfunction=no
vis=3

// 542
[mapelement_542]
text=B
size=0
colour=16777215
category=category_1129
mapfunction=no
vis=3

// 543
[mapelement_543]
text=C
size=0
colour=16777215
category=category_1129
mapfunction=no
vis=3

// 544
[mapelement_544]
text=Fossil<br>Island
size=2
colour=16750623
category=category_1129
mapfunction=no

// 545
[mapelement_545]
text=Museum<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 546
[mapelement_546]
text=The Warrens
size=0
colour=16777215
category=category_1129
mapfunction=no

// 547
[mapelement_547]
text=Mushroom<br>Forest
size=0
colour=16777215
category=category_1129
mapfunction=no

// 548
[mapelement_548]
text=House<br>on the<br>Hill
size=0
colour=16777215
category=category_1129
mapfunction=no

// 549
[mapelement_549]
text=Volcano
size=0
colour=16777215
category=category_1129
mapfunction=no

// 550
[mapelement_550]
text=Tar<br>Swamp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 551
[mapelement_551]
text=Crabclaw Caves
size=0
colour=16777215
category=category_1129
mapfunction=no

// 552
[mapelement_552]
text=Wilderness<br>Emblem Trader
size=0
colour=16777215
category=category_1129
mapfunction=no

// 553
[mapelement_553]
text=Ice giants
size=0
colour=16777215
category=category_1129
mapfunction=no

// 554
[mapelement_554]
text=Greater<br>demons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 555
[mapelement_555]
text=Green dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 556
[mapelement_556]
text=Green<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 557
[mapelement_557]
text=Revenants
size=0
colour=16777215
category=category_1129
mapfunction=no

// 558
[mapelement_558]
text=Myths'<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 559
[mapelement_559]
text=Corsair<br>Cove
size=1
colour=16777215
category=category_1129
mapfunction=no

// 560
[mapelement_560]
text=Ancient<br>Forge
size=0
colour=16777215
category=category_1129
mapfunction=no

// 561
[mapelement_561]
text=Ogresses
size=0
colour=16777215
category=category_1129
mapfunction=no

// 562
[mapelement_562]
text=Chinchompas
size=0
colour=16777215
category=category_1129
mapfunction=no

// 563
[mapelement_563]
text=Dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 564
[mapelement_564]
text=Baby dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 565
[mapelement_565]
text=Chapel
size=0
colour=16777215
category=category_1129
mapfunction=no

// 566
[mapelement_566]
text=Ungael
size=0
colour=16777215
category=category_1129
mapfunction=no

// 567
[mapelement_567]
text=Lithkren
size=0
colour=16777215
category=category_1129
mapfunction=no

// 568
[mapelement_568]
text=War Tent
size=0
colour=16777215
category=category_1129
mapfunction=no

// 569
[mapelement_569]
text=Foodhall
size=0
colour=16777215
category=category_1129
mapfunction=no

// 570
[mapelement_570]
text=Kourend<br>Castle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 571
[mapelement_571]
text=Kebos<br>Lowlands
size=2
colour=16750623
category=category_1129
mapfunction=no

// 572
[mapelement_572]
text=Paterdomus<br>Temple
size=0
colour=16777215
category=category_1129
mapfunction=no

// 573
[mapelement_573]
text=Darkmeyer
size=1
colour=16777215
category=category_1129
mapfunction=no

// 574
[mapelement_574]
text=Slepe
size=1
colour=16777215
category=category_1129
mapfunction=no

// 575
[mapelement_575]
text=Ver Sinhaza
size=0
colour=16777215
category=category_1129
mapfunction=no

// 576
[mapelement_576]
category=category_1251
graphic="mapfunction,89"
mapfunction=yes
vis=3

// 577
[mapelement_577]
category=category_1252
graphic="mapfunction,90"
mapfunction=yes
vis=3

// 578
[mapelement_578]
category=category_1253
graphic="mapfunction,91"
mapfunction=yes
vis=3

// 579
[mapelement_579]
category=category_1254
graphic="mapfunction,92"
mapfunction=yes
vis=3

// 580
[mapelement_580]
category=category_1255
graphic="mapfunction,93"
mapfunction=yes
vis=3

// 581
[mapelement_581]
category=category_1256
graphic="mapfunction,94"
mapfunction=yes
vis=3

// 582
[mapelement_582]
category=category_1257
graphic="mapfunction,95"
mapfunction=yes
vis=3

// 583
[mapelement_583]
category=category_1258
graphic="mapfunction,96"
mapfunction=yes
vis=3

// 584
[mapelement_584]
category=category_1259
graphic="mapfunction,97"
mapfunction=yes
vis=3

// 585
[mapelement_585]
category=category_1260
graphic="mapfunction,98"
mapfunction=yes
vis=3

// 586
[mapelement_586]
category=category_1261
graphic="mapfunction,99"
mapfunction=yes
vis=3

// 587
[mapelement_587]
category=category_1262
graphic="mapfunction,100"
mapfunction=yes
vis=3

// 588
[mapelement_588]
category=category_1263
graphic="mapfunction,101"
mapfunction=yes
vis=3

// 589
[mapelement_589]
category=category_1264
graphic="mapfunction,103"
mapfunction=yes
vis=3

// 590
[mapelement_590]
category=category_1265
graphic="mapfunction,115"
mapfunction=yes
vis=3

// 591
[mapelement_591]
category=category_1266
graphic="mapfunction,106"
mapfunction=yes
vis=3

// 592
[mapelement_592]
category=category_1267
graphic="mapfunction,107"
mapfunction=yes
vis=3

// 593
[mapelement_593]
category=category_1268
graphic="mapfunction,108"
mapfunction=yes
vis=3

// 594
[mapelement_594]
category=category_1269
graphic="mapfunction,110"
mapfunction=yes
vis=3

// 595
[mapelement_595]
category=category_1270
graphic="mapfunction,111"
mapfunction=yes
vis=3

// 596
[mapelement_596]
category=category_1271
graphic="mapfunction,112"
mapfunction=yes
vis=3

// 597
[mapelement_597]
category=category_1272
graphic="mapfunction,113"
mapfunction=yes
vis=3

// 598
[mapelement_598]
category=category_1273
graphic="mapfunction,114"
mapfunction=yes
vis=3

// 599
[mapelement_599]
category=category_1274
graphic="mapfunction,116"
mapfunction=yes
vis=3

// 600
[mapelement_600]
category=category_1275
graphic="mapfunction,117"
mapfunction=yes
vis=3

// 601
[mapelement_601]
text=Kalphite<br>Cave
size=0
colour=16777215
category=category_1129
mapfunction=no

// 602
[mapelement_602]
text=Lovakengj<br>Assembly
size=0
colour=16777215
category=category_1129
mapfunction=no

// 603
[mapelement_603]
text=The Forsaken<br>Tower
size=0
colour=16777215
category=category_1129
mapfunction=no

// 604
[mapelement_604]
text=Mount<br>Karuulm
size=1
colour=16777215
category=category_1129
mapfunction=no

// 605
[mapelement_605]
text=Farming Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 606
[mapelement_606]
text=Battlefront
size=0
colour=16777215
category=category_1129
mapfunction=no

// 607
[mapelement_607]
text=Molch
size=1
colour=16777215
category=category_1129
mapfunction=no

// 608
[mapelement_608]
text=Kebos Swamp
size=1
colour=16777215
category=category_1129
mapfunction=no

// 609
[mapelement_609]
text=Lake Molch
size=0
colour=16777215
category=category_1129
mapfunction=no

// 610
[mapelement_610]
text=River Molch
size=0
colour=16777215
category=category_1129
mapfunction=no

// 611
[mapelement_611]
text=Wyrms
size=0
colour=16777215
category=category_1129
mapfunction=no

// 612
[mapelement_612]
text=Drakes
size=0
colour=16777215
category=category_1129
mapfunction=no

// 613
[mapelement_613]
text=Hydras
size=0
colour=16777215
category=category_1129
mapfunction=no

// 614
[mapelement_614]
text=Alchemical<br>Hydra
size=0
colour=16777215
category=category_1129
mapfunction=no

// 615
[mapelement_615]
text=Sulphur<br>lizards
size=0
colour=16777215
category=category_1129
mapfunction=no

// 616
[mapelement_616]
text=Tasakaal
size=0
colour=16777215
category=category_1129
mapfunction=no

// 617
[mapelement_617]
text=Hespori
size=0
colour=16777215
category=category_1129
mapfunction=no

// 618
[mapelement_618]
text=Lizardman<br>Temple
size=0
colour=16777215
category=category_1129
mapfunction=no

// 619
[mapelement_619]
category=category_1317
graphic="mapfunction,118"
mapfunction=yes
vis=3

// 620
[mapelement_620]
text=Forthos Ruin
size=0
colour=16777215
category=category_1129
mapfunction=no

// 621
[mapelement_621]
text=Kingstown
size=1
colour=16777215
category=category_1129
mapfunction=no

// 622
[mapelement_622]
text=Wine of<br>Zamorak
size=0
colour=16777215
category=category_1129
mapfunction=no

// 623
[mapelement_623]
text=Larran's<br>Chest
size=0
colour=16777215
category=category_1129
mapfunction=no

// 624
[mapelement_624]
text=River<br>Dougne
size=0
colour=16777215
category=category_1129
mapfunction=no

// 625
[mapelement_625]
text=River<br>Hos
size=0
colour=16777215
category=category_1129
mapfunction=no

// 626
[mapelement_626]
text=Undead<br>druids
size=0
colour=16777215
category=category_1129
mapfunction=no

// 627
[mapelement_627]
text=Bone<br>Burner
size=0
colour=16777215
category=category_1129
mapfunction=no

// 628
[mapelement_628]
text=Temple Spiders
size=0
colour=16777215
category=category_1129
mapfunction=no

// 629
[mapelement_629]
text=Sarachnis
size=0
colour=16777215
category=category_1129
mapfunction=no

// 630
[mapelement_630]
category=category_1070
graphic="mapfunction,109"
mapfunction=yes
vis=3

// 631
[mapelement_631]
category=category_1396
graphic="mapfunction,119"
mapfunction=yes
vis=3

// 632
[mapelement_632]
text=Moss<br>giants
size=0
colour=16777215
category=category_1129
mapfunction=no

// 633
[mapelement_633]
text=Trahaearn<br>Mine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 634
[mapelement_634]
text=Zalcano
size=0
colour=16777215
category=category_1129
mapfunction=no

// 635
[mapelement_635]
text=The Gauntlet
size=0
colour=16777215
category=category_1129
mapfunction=no

// 636
[mapelement_636]
text=Gwenith
size=1
colour=16777215
category=category_1129
mapfunction=no

// 637
[mapelement_637]
text=Last Man<br>Standing
size=0
colour=16777215
category=category_1129
mapfunction=no

// 638
[mapelement_638]
text=The Mountain
size=0
colour=16777215
category=category_1129
mapfunction=no

// 639
[mapelement_639]
text=Trinity<br>Outpost
size=0
colour=16777215
category=category_1129
mapfunction=no

// 640
[mapelement_640]
text=Debtor<br>Hideout
size=0
colour=16777215
category=category_1129
mapfunction=no

// 641
[mapelement_641]
text=Moser<br>Settlement
size=0
colour=16777215
category=category_1129
mapfunction=no

// 642
[mapelement_642]
text=Rocky<br>Outcrop
size=0
colour=16777215
category=category_1129
mapfunction=no

// 643
[mapelement_643]
text=Island<br>of Stone
size=0
colour=16777215
category=category_1129
mapfunction=no

// 644
[mapelement_644]
text=Basilisk<br>Knights
size=0
colour=16777215
category=category_1129
mapfunction=no

// 645
[mapelement_645]
category=category_176
graphic="mapfunction,123"
mapfunction=yes
vis=3

// 646
[mapelement_646]
text=Lesser<br>demons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 647
[mapelement_647]
text=The<br>Nightmare
size=0
colour=16777215
category=category_1129
mapfunction=no

// 648
[mapelement_648]
text=Shura
size=0
colour=16777215
category=category_1129
mapfunction=no

// 649
[mapelement_649]
text=Elves
size=0
colour=16777215
category=category_1129
mapfunction=no

// 650
[mapelement_650]
category=category_1425
graphic="mapfunction,124"
mapfunction=yes
vis=3

// 651
[mapelement_651]
text=Icyene<br>Graveyard
size=0
colour=16777215
category=category_1129
mapfunction=no

// 652
[mapelement_652]
category=category_1459
graphic="mapfunction,125"
mapfunction=yes
vis=3

// 653
[mapelement_653]
text=Crypt
size=0
colour=16777215
category=category_1129
mapfunction=no

// 654
[mapelement_654]
text=Ferox<br>Enclave
size=1
colour=16777215
category=category_1129
mapfunction=no

// 655
[mapelement_655]
text=Citharede<br>Abbey
size=0
colour=16777215
category=category_1129
mapfunction=no

// 656
[mapelement_656]
text=South Falador<br>Farm
size=0
colour=16777215
category=category_1129
mapfunction=no

// 657
[mapelement_657]
text=Sourhog Cave
size=0
colour=16777215
category=category_1129
mapfunction=no

// 658
[mapelement_658]
text=Isle of Souls
size=2
colour=16750623
category=category_1129
mapfunction=no

// 659
[mapelement_659]
text=Soul Wars<br>Arena
size=1
colour=16777215
category=category_1129
mapfunction=no

// 660
[mapelement_660]
text=Soul Wars<br>Lobby
size=1
colour=16777215
category=category_1129
mapfunction=no

// 661
[mapelement_661]
text=Soul<br>Obelisk
size=0
colour=16777215
category=category_1129
mapfunction=no

// 662
[mapelement_662]
text=Western<br>Graveyard
size=0
colour=16777215
category=category_1129
mapfunction=no

// 663
[mapelement_663]
text=Eastern<br>Graveyard
size=0
colour=16777215
category=category_1129
mapfunction=no

// 664
[mapelement_664]
text=Blue<br>Base
size=0
colour=16777215
category=category_1129
mapfunction=no

// 665
[mapelement_665]
text=Red<br>Base
size=0
colour=16777215
category=category_1129
mapfunction=no

// 666
[mapelement_666]
text=Avatar of<br>Creation
size=0
colour=16777215
category=category_1129
mapfunction=no

// 667
[mapelement_667]
text=Avatar of<br>Destruction
size=0
colour=16777215
category=category_1129
mapfunction=no

// 668
[mapelement_668]
text=Iron<br>dragons
size=0
colour=16777215
category=category_1129
mapfunction=no

// 669
[mapelement_669]
text=Desert Island
size=2
colour=16750623
category=category_1129
mapfunction=no

// 670
[mapelement_670]
text=Wild Varrock
size=2
colour=16750623
category=category_1129
mapfunction=no

// 671
[mapelement_671]
text=Hut
size=0
colour=16777215
category=category_1129
mapfunction=no

// 672
[mapelement_672]
text=Stone Circle
size=0
colour=16777215
category=category_1129
mapfunction=no

// 673
[mapelement_673]
text=Court of Chaos
size=0
colour=16777215
category=category_1129
mapfunction=no

// 674
[mapelement_674]
text=Old Manor
size=0
colour=16777215
category=category_1129
mapfunction=no

// 675
[mapelement_675]
text=Town Center
size=0
colour=16777215
category=category_1129
mapfunction=no

// 676
[mapelement_676]
text=Blank Tower
size=0
colour=16777215
category=category_1129
mapfunction=no

// 677
[mapelement_677]
text=Trading Post
size=0
colour=16777215
category=category_1129
mapfunction=no

// 678
[mapelement_678]
text=Dark Warrior's<br>Palace
size=1
colour=16777215
category=category_1129
mapfunction=no

// 679
[mapelement_679]
text=Pillars of Sacrifice
size=0
colour=16777215
category=category_1129
mapfunction=no

// 680
[mapelement_680]
category=category_1499
graphic="mapfunction,126"
mapfunction=yes
vis=3

// 681
[mapelement_681]
text=Ruins of<br>Unkah
size=1
colour=16777215
category=category_1129
mapfunction=no

// 682
[mapelement_682]
text=Sea Spirit<br>Dock
size=0
colour=16777215
category=category_1129
mapfunction=no

// 683
[mapelement_683]
text=Tempoross<br>Cove
size=1
colour=16777215
category=category_1129
mapfunction=no

// 684
[mapelement_684]
text=Camdozaal<br>Vault
size=1
colour=16777215
category=category_1129
mapfunction=no

// 685
[mapelement_685]
text=Ramarno
size=0
colour=16777215
category=category_1129
mapfunction=no

// 686
[mapelement_686]
text=Offering<br>Altar
size=1
colour=16777215
category=category_1129
mapfunction=no

// 687
[mapelement_687]
text=Golem<br>Workshop
size=1
colour=16777215
category=category_1129
mapfunction=no

// 688
[mapelement_688]
text=Camdozaal<br>Mines
size=1
colour=16777215
category=category_1129
mapfunction=no

// 689
[mapelement_689]
text=Ancient<br>Vault
size=0
colour=16777215
category=category_1129
mapfunction=no

// 690
[mapelement_690]
category=category_1551
graphic="mapfunction,127"
mapfunction=yes
vis=3

// 691
[mapelement_691]
text=Shayzien<br>Encampment
size=1
colour=16777215
category=category_1129
mapfunction=no

// 692
[mapelement_692]
text=Giant<br>Pit
size=0
colour=16777215
category=category_1129
mapfunction=no

// 693
[mapelement_693]
text=Ruins<br>of Morra
size=0
colour=16777215
category=category_1129
mapfunction=no

// 694
[mapelement_694]
text=Shayzia<br>Ruin
size=0
colour=16777215
category=category_1129
mapfunction=no

// 695
[mapelement_695]
text=Northern<br>Tundras
size=1
colour=16777215
category=category_1129
mapfunction=no

// 696
[mapelement_696]
text=River<br>of Souls
size=0
colour=16777215
category=category_1129
mapfunction=no

// 697
[mapelement_697]
category=category_1579
graphic="mapfunction,128"
mapfunction=yes
vis=3

// 698
[mapelement_698]
text=Sire
size=0
colour=16777215
category=category_1129
mapfunction=no

// 699
[mapelement_699]
text=Here be<br>spiders
size=0
colour=16777215
category=category_1129
mapfunction=no

// 700
[mapelement_700]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 701
[mapelement_701]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 702
[mapelement_702]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 703
[mapelement_703]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 704
[mapelement_704]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 705
[mapelement_705]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 706
[mapelement_706]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 707
[mapelement_707]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 708
[mapelement_708]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 709
[mapelement_709]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 710
[mapelement_710]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 711
[mapelement_711]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 712
[mapelement_712]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 713
[mapelement_713]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 714
[mapelement_714]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 715
[mapelement_715]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 716
[mapelement_716]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 717
[mapelement_717]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 718
[mapelement_718]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 719
[mapelement_719]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 720
[mapelement_720]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 721
[mapelement_721]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 722
[mapelement_722]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 723
[mapelement_723]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 724
[mapelement_724]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 725
[mapelement_725]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 726
[mapelement_726]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 727
[mapelement_727]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 728
[mapelement_728]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 729
[mapelement_729]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 730
[mapelement_730]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 731
[mapelement_731]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 732
[mapelement_732]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 733
[mapelement_733]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 734
[mapelement_734]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 735
[mapelement_735]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 736
[mapelement_736]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 737
[mapelement_737]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 738
[mapelement_738]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 739
[mapelement_739]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 740
[mapelement_740]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 741
[mapelement_741]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 742
[mapelement_742]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 743
[mapelement_743]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 744
[mapelement_744]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 745
[mapelement_745]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 746
[mapelement_746]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 747
[mapelement_747]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 748
[mapelement_748]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 749
[mapelement_749]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 750
[mapelement_750]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 751
[mapelement_751]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 752
[mapelement_752]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 753
[mapelement_753]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 754
[mapelement_754]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 755
[mapelement_755]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 756
[mapelement_756]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 757
[mapelement_757]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 758
[mapelement_758]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 759
[mapelement_759]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 760
[mapelement_760]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 761
[mapelement_761]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 762
[mapelement_762]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 763
[mapelement_763]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 764
[mapelement_764]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 765
[mapelement_765]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 766
[mapelement_766]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 767
[mapelement_767]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 768
[mapelement_768]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 769
[mapelement_769]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 770
[mapelement_770]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 771
[mapelement_771]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 772
[mapelement_772]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 773
[mapelement_773]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 774
[mapelement_774]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 775
[mapelement_775]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 776
[mapelement_776]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 777
[mapelement_777]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 778
[mapelement_778]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 779
[mapelement_779]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 780
[mapelement_780]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 781
[mapelement_781]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 782
[mapelement_782]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 783
[mapelement_783]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 784
[mapelement_784]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 785
[mapelement_785]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 786
[mapelement_786]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 787
[mapelement_787]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 788
[mapelement_788]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 789
[mapelement_789]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 790
[mapelement_790]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 791
[mapelement_791]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 792
[mapelement_792]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 793
[mapelement_793]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 794
[mapelement_794]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 795
[mapelement_795]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 796
[mapelement_796]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 797
[mapelement_797]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 798
[mapelement_798]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 799
[mapelement_799]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 800
[mapelement_800]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 801
[mapelement_801]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 802
[mapelement_802]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 803
[mapelement_803]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 804
[mapelement_804]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 805
[mapelement_805]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 806
[mapelement_806]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 807
[mapelement_807]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 808
[mapelement_808]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 809
[mapelement_809]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 810
[mapelement_810]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 811
[mapelement_811]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 812
[mapelement_812]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 813
[mapelement_813]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 814
[mapelement_814]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 815
[mapelement_815]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 816
[mapelement_816]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 817
[mapelement_817]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 818
[mapelement_818]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 819
[mapelement_819]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 820
[mapelement_820]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 821
[mapelement_821]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 822
[mapelement_822]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 823
[mapelement_823]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 824
[mapelement_824]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 825
[mapelement_825]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 826
[mapelement_826]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 827
[mapelement_827]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 828
[mapelement_828]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 829
[mapelement_829]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 830
[mapelement_830]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 831
[mapelement_831]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 832
[mapelement_832]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 833
[mapelement_833]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 834
[mapelement_834]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 835
[mapelement_835]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 836
[mapelement_836]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 837
[mapelement_837]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 838
[mapelement_838]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 839
[mapelement_839]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 840
[mapelement_840]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 841
[mapelement_841]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 842
[mapelement_842]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 843
[mapelement_843]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 844
[mapelement_844]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 845
[mapelement_845]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 846
[mapelement_846]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 847
[mapelement_847]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 848
[mapelement_848]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 849
[mapelement_849]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 850
[mapelement_850]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 851
[mapelement_851]
text=Ancient<br>Prison
size=1
colour=16777215
category=category_1129
mapfunction=no

// 852
[mapelement_852]
text=Greater<br>nechryael
size=0
colour=16777215
category=category_1129
mapfunction=no

// 853
[mapelement_853]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 854
[mapelement_854]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 855
[mapelement_855]
text=Ruins of<br>Ullek
size=1
colour=16777215
category=category_1129
mapfunction=no

// 856
[mapelement_856]
text=Necropolis
size=0
colour=16777215
category=category_1129
mapfunction=no

// 857
[mapelement_857]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 858
[mapelement_858]
category=category_1641
graphic="mapfunction,129"
mapfunction=yes
vis=3

// 859
[mapelement_859]
category=category_1642
graphic="mapfunction,130"
mapfunction=yes
vis=3

// 860
[mapelement_860]
category=category_1643
graphic="mapfunction,131"
mapfunction=yes
vis=3

// 861
[mapelement_861]
text=Kovac
size=0
colour=16777215
category=category_1129
mapfunction=no

// 862
[mapelement_862]
text=Giants'<br>Plateau
size=1
colour=16777215
category=category_1129
mapfunction=no

// 863
[mapelement_863]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 864
[mapelement_864]
text=Emir's<br>Arena
size=1
colour=16777215
category=category_1129
mapfunction=no

// 865
[mapelement_865]
text=Kalphite<br>Lair
size=1
colour=16777215
category=category_1129
mapfunction=no

// 866
[mapelement_866]
text=Kalphite<br>Cave
size=1
colour=16777215
category=category_1129
mapfunction=no

// 867
[mapelement_867]
text=Trouble<br>Brewing
size=0
colour=16777215
category=category_1129
mapfunction=no

// 868
[mapelement_868]
text=Piscatoris
size=1
colour=16777215
category=category_1129
mapfunction=no

// 869
[mapelement_869]
text=Troll<br>Country
size=2
colour=16750623
category=category_1129
mapfunction=no

// 870
[mapelement_870]
text=Uzer<br>Oasis
size=0
colour=16777215
category=category_1129
mapfunction=no

// 871
[mapelement_871]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 872
[mapelement_872]
text=Skeleton
size=0
colour=16777215
category=category_1129
mapfunction=no

// 873
[mapelement_873]
text=Callisto's Den
size=0
colour=16777215
category=category_1129
mapfunction=no

// 874
[mapelement_874]
text=Silk Chasm
size=0
colour=16777215
category=category_1129
mapfunction=no

// 875
[mapelement_875]
text=Vet'ion's Rest
size=0
colour=16777215
category=category_1129
mapfunction=no

// 876
[mapelement_876]
text=Hunter's End
size=0
colour=16777215
category=category_1129
mapfunction=no

// 877
[mapelement_877]
text=Web Chasm
size=0
colour=16777215
category=category_1129
mapfunction=no

// 878
[mapelement_878]
text=Skeletal Tomb
size=0
colour=16777215
category=category_1129
mapfunction=no

// 879
[mapelement_879]
text=Jaldraocht<br>Pyramid
size=0
colour=16777215
category=category_1129
mapfunction=no

// 880
[mapelement_880]
text=Jalsavrah<br>Pyramid
size=0
colour=16777215
category=category_1129
mapfunction=no

// 881
[mapelement_881]
text=Jaltevas<br>Pyramid
size=0
colour=16777215
category=category_1129
mapfunction=no

// 882
[mapelement_882]
text=Daimon's<br>Crater
size=1
colour=16777215
category=category_1129
mapfunction=no

// 883
[mapelement_883]
text=Frozen Temple
size=0
colour=16777215
category=category_1129
mapfunction=no

// 884
[mapelement_884]
text=Huntsman's<br>Wood
size=0
colour=16777215
category=category_1129
mapfunction=no

// 885
[mapelement_885]
text=Tower of<br>Bounty
size=0
colour=16777215
category=category_1129
mapfunction=no

// 886
[mapelement_886]
text=Bounty Hunter
size=0
colour=16777215
category=category_1129
mapfunction=no

// 887
[mapelement_887]
category=category_1790
graphic="mapfunction,133"
mapfunction=yes
vis=3

// 888
[mapelement_888]
text=The<br>Stranglewood
size=1
colour=16777215
category=category_1129
mapfunction=no

// 889
[mapelement_889]
text=Temple
size=0
colour=16777215
category=category_1129
mapfunction=no

// 890
[mapelement_890]
text=Ritual<br>Site
size=0
colour=16777215
category=category_1129
mapfunction=no

// 891
[mapelement_891]
text=Main<br>Block
size=0
colour=16777215
category=category_1129
mapfunction=no

// 892
[mapelement_892]
text=Administration
size=0
colour=16777215
category=category_1129
mapfunction=no

// 893
[mapelement_893]
text=Refugee<br>Camp
size=0
colour=16777215
category=category_1129
mapfunction=no

// 894
[mapelement_894]
text=Science<br>District
size=0
colour=16777215
category=category_1129
mapfunction=no

// 895
[mapelement_895]
text=Residential<br>District
size=0
colour=16777215
category=category_1129
mapfunction=no

// 896
[mapelement_896]
text=Sunken<br>Cathedral
size=0
colour=16777215
category=category_1129
mapfunction=no

// 897
[mapelement_897]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 898
[mapelement_898]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 899
[mapelement_899]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 900
[mapelement_900]
text=Party Room
size=0
colour=16777215
category=category_1129
mapfunction=no

// 901
[mapelement_901]
category=category_2002
graphic="mapfunction,134"
mapfunction=yes
vis=3

// 902
[mapelement_902]
text=Kingdom of<br>Varlamore
size=2
colour=16750623
category=category_1129
mapfunction=no

// 903
[mapelement_903]
text=Civitas illa<br>Fortis
size=1
colour=16777215
category=category_1129
mapfunction=no

// 904
[mapelement_904]
text=Avium<br>Savannah
size=1
colour=16777215
category=category_1129
mapfunction=no

// 905
[mapelement_905]
text=Ralos'<br>Rise
size=1
colour=16777215
category=category_1129
mapfunction=no

// 906
[mapelement_906]
text=Sunset<br>Coast
size=1
colour=16777215
category=category_1129
mapfunction=no

// 907
[mapelement_907]
text=Fortis<br>Colosseum
size=0
colour=16777215
category=category_1129
mapfunction=no

// 908
[mapelement_908]
text=Fortis<br>Cothon
size=0
colour=16777215
category=category_1129
mapfunction=no

// 909
[mapelement_909]
text=Bazaar
size=0
colour=16777215
category=category_1129
mapfunction=no

// 910
[mapelement_910]
text=Sunrise<br>Palace
size=0
colour=16777215
category=category_1129
mapfunction=no

// 911
[mapelement_911]
text=Grand<br>Museum
size=0
colour=16777215
category=category_1129
mapfunction=no

// 912
[mapelement_912]
text=Kualti<br>Headquarters
size=0
colour=16777215
category=category_1129
mapfunction=no

// 913
[mapelement_913]
text=Outer Fortis
size=0
colour=16777215
category=category_1129
mapfunction=no

// 914
[mapelement_914]
text=Fortis Aqueduct
size=0
colour=16777215
category=category_1129
mapfunction=no

// 915
[mapelement_915]
text=Ortus<br>Farm
size=0
colour=16777215
category=category_1129
mapfunction=no

// 916
[mapelement_916]
text=The<br>Teomat
size=0
colour=16777215
category=category_1129
mapfunction=no

// 917
[mapelement_917]
text=Cam Torum<br>Entrance
size=0
colour=16777215
category=category_1129
mapfunction=no

// 918
[mapelement_918]
text=Hunter<br>Guild
size=0
colour=16777215
category=category_1129
mapfunction=no

// 919
[mapelement_919]
text=Locus<br>Oasis
size=0
colour=16777215
category=category_1129
mapfunction=no

// 920
[mapelement_920]
text=Stonecutter<br>Outpost
size=0
colour=16777215
category=category_1129
mapfunction=no

// 921
[mapelement_921]
text=Colossal Wyrm<br>Remains
size=0
colour=16777215
category=category_1129
mapfunction=no

// 922
[mapelement_922]
text=River<br>Varla
size=0
colour=16777215
category=category_1129
mapfunction=no

// 923
[mapelement_923]
text=River Ortus
size=0
colour=16777215
category=category_1129
mapfunction=no

// 924
[mapelement_924]
text=Barracks
size=0
colour=16777215
category=category_1129
mapfunction=no

// 925
[mapelement_925]
text=Cam Torum
size=1
colour=16777215
category=category_1129
mapfunction=no

// 926
[mapelement_926]
text=City<br>Entrance
size=0
colour=16777215
category=category_1129
mapfunction=no

// 927
[mapelement_927]
text=Neypotzli<br>Entrance
size=0
colour=16777215
category=category_1129
mapfunction=no

// 928
[mapelement_928]
text=The<br>Blood Moon
size=0
colour=16777215
category=category_1129
mapfunction=no

// 929
[mapelement_929]
text=The<br>Blue Moon
size=0
colour=16777215
category=category_1129
mapfunction=no

// 930
[mapelement_930]
text=The<br>Eclipse Moon
size=0
colour=16777215
category=category_1129
mapfunction=no

// 931
[mapelement_931]
text=Earthbound<br>Cavern
size=0
colour=16777215
category=category_1129
mapfunction=no

// 932
[mapelement_932]
text=Streambound<br>Cavern
size=0
colour=16777215
category=category_1129
mapfunction=no

// 933
[mapelement_933]
text=Antechamber
size=0
colour=16777215
category=category_1129
mapfunction=no

// 934
[mapelement_934]
text=Ancient<br>Prison
size=0
colour=16777215
category=category_1129
mapfunction=no

// 935
[mapelement_935]
text=Ancient<br>Shrine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 936
[mapelement_936]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 937
[mapelement_937]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 938
[mapelement_938]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 939
[mapelement_939]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 940
[mapelement_940]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 941
[mapelement_941]
text=Araxxor
size=0
colour=16777215
category=category_1129
mapfunction=no

// 942
[mapelement_942]
text=Aldarin
size=1
colour=16777215
category=category_1129
mapfunction=no

// 943
[mapelement_943]
text=Mistrock
size=1
colour=16777215
category=category_1129
mapfunction=no

// 944
[mapelement_944]
text=Quetzacalli<br>Gorge
size=1
colour=16777215
category=category_1129
mapfunction=no

// 945
[mapelement_945]
text=The<br>Proudspire
size=1
colour=16777215
category=category_1129
mapfunction=no

// 946
[mapelement_946]
text=The<br>Darkfrost
size=1
colour=16777215
category=category_1129
mapfunction=no

// 947
[mapelement_947]
text=Mons<br>Gratia
size=1
colour=16777215
category=category_1129
mapfunction=no

// 948
[mapelement_948]
text=Salvager<br>Overlook
size=1
colour=16777215
category=category_1129
mapfunction=no

// 949
[mapelement_949]
text=Moonrise Brewery<br>and Winery
size=0
colour=16777215
category=category_1129
mapfunction=no

// 950
[mapelement_950]
text=Twilight<br>Temple
size=0
colour=16777215
category=category_1129
mapfunction=no

// 951
[mapelement_951]
text=Tower of<br>Ascension
size=0
colour=16777215
category=category_1129
mapfunction=no

// 952
[mapelement_952]
text=Shipwreck<br>Cove
size=0
colour=16777215
category=category_1129
mapfunction=no

// 953
[mapelement_953]
text=Darkmoon<br>Ravine
size=0
colour=16777215
category=category_1129
mapfunction=no

// 954
[mapelement_954]
text=Villa<br>Lucens
size=0
colour=16777215
category=category_1129
mapfunction=no

// 955
[mapelement_955]
text=Alchemical<br>Society
size=0
colour=16777215
category=category_1129
mapfunction=no

// 956
[mapelement_956]
text=Wolf<br>Den
size=0
colour=16777215
category=category_1129
mapfunction=no

// 957
[mapelement_957]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 958
[mapelement_958]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 959
[mapelement_959]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 960
[mapelement_960]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 961
[mapelement_961]
category=category_1056
graphic="mapfunction,6"
mapfunction=yes
vis=3

// 962
[mapelement_962]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 963
[mapelement_963]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 964
[mapelement_964]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 965
[mapelement_965]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 966
[mapelement_966]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 967
[mapelement_967]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 968
[mapelement_968]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 969
[mapelement_969]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 970
[mapelement_970]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 971
[mapelement_971]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 972
[mapelement_972]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 973
[mapelement_973]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 974
[mapelement_974]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 975
[mapelement_975]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 976
[mapelement_976]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 977
[mapelement_977]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 978
[mapelement_978]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 979
[mapelement_979]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 980
[mapelement_980]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 981
[mapelement_981]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 982
[mapelement_982]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 983
[mapelement_983]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 984
[mapelement_984]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 985
[mapelement_985]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 986
[mapelement_986]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 987
[mapelement_987]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 988
[mapelement_988]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 989
[mapelement_989]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 990
[mapelement_990]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 991
[mapelement_991]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 992
[mapelement_992]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 993
[mapelement_993]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 994
[mapelement_994]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 995
[mapelement_995]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 996
[mapelement_996]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 997
[mapelement_997]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 998
[mapelement_998]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 999
[mapelement_999]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1000
[mapelement_1000]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1001
[mapelement_1001]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1002
[mapelement_1002]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1003
[mapelement_1003]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1004
[mapelement_1004]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1005
[mapelement_1005]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1006
[mapelement_1006]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1007
[mapelement_1007]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1008
[mapelement_1008]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1009
[mapelement_1009]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1010
[mapelement_1010]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1011
[mapelement_1011]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1012
[mapelement_1012]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1013
[mapelement_1013]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1014
[mapelement_1014]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1015
[mapelement_1015]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1016
[mapelement_1016]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1017
[mapelement_1017]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1018
[mapelement_1018]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1019
[mapelement_1019]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1020
[mapelement_1020]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1021
[mapelement_1021]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1022
[mapelement_1022]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1023
[mapelement_1023]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1024
[mapelement_1024]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1025
[mapelement_1025]
category=category_1104
graphic="mapfunction,56"
mapfunction=yes
vis=3

// 1026
[mapelement_1026]
text=Yama
size=0
colour=16777215
category=category_1129
mapfunction=no

