// 0
[mapelement_0]
category=category_1049
sprite="mapfunction,0"
mapfunction=yes
show=both

// 1
[mapelement_1]
category=category_1050
sprite="mapfunction,1"
mapfunction=yes
show=both

// 2
[mapelement_2]
category=category_1052
sprite="mapfunction,2"
mapfunction=yes
show=both

// 3
[mapelement_3]
category=category_1053
sprite="mapfunction,3"
mapfunction=yes
show=both

// 4
[mapelement_4]
category=category_1054
sprite="mapfunction,4"
mapfunction=yes
show=both

// 5
[mapelement_5]
category=category_1055
sprite="mapfunction,5"
mapfunction=yes
show=both

// 6
[mapelement_6]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 7
[mapelement_7]
category=category_1057
sprite="mapfunction,7"
mapfunction=yes
show=both

// 8
[mapelement_8]
category=category_1058
sprite="mapfunction,8"
mapfunction=yes
show=both

// 9
[mapelement_9]
category=category_1059
sprite="mapfunction,9"
mapfunction=yes
show=both

// 10
[mapelement_10]
category=category_1060
sprite="mapfunction,10"
mapfunction=yes
show=both

// 11
[mapelement_11]
category=category_1061
sprite="mapfunction,11"
mapfunction=yes
show=both

// 12
[mapelement_12]
category=category_1062
sprite="mapfunction,12"
mapfunction=yes
show=both

// 13
[mapelement_13]
category=category_1062
sprite="mapfunction,86"
op1=Open
mapfunction=no
show=both
opbase=Map

// 14
[mapelement_14]
category=category_1063
sprite="mapfunction,87"
op1=Open
mapfunction=no
opbase=Map

// 15
[mapelement_15]
category=category_1064
sprite="mapfunction,13"
mapfunction=yes
show=both

// 16
[mapelement_16]
category=category_1065
sprite="mapfunction,14"
mapfunction=yes
show=both

// 17
[mapelement_17]
category=category_1066
sprite="mapfunction,15"
mapfunction=yes
show=both

// 18
[mapelement_18]
category=category_1067
sprite="mapfunction,16"
mapfunction=yes
show=both

// 19
[mapelement_19]
category=category_1068
sprite="mapfunction,17"
mapfunction=yes
show=both

// 20
[mapelement_20]
category=category_1069
sprite="mapfunction,18"
mapfunction=yes
show=both

// 21
[mapelement_21]
category=category_1070
sprite="mapfunction,19"
mapfunction=yes
show=both

// 22
[mapelement_22]
category=category_1071
sprite="mapfunction,20"
mapfunction=yes
show=both

// 23
[mapelement_23]
category=category_1072
sprite="mapfunction,21"
mapfunction=yes
show=both

// 24
[mapelement_24]
category=category_1073
sprite="mapfunction,22"
mapfunction=yes
show=both

// 25
[mapelement_25]
category=category_1074
sprite="mapfunction,23"
mapfunction=yes
show=both

// 26
[mapelement_26]
category=category_1075
sprite="mapfunction,24"
mapfunction=yes
show=both

// 27
[mapelement_27]
category=category_1076
sprite="mapfunction,25"
mapfunction=yes
show=both

// 28
[mapelement_28]
category=category_1077
sprite="mapfunction,26"
mapfunction=yes
show=both

// 29
[mapelement_29]
category=category_1078
sprite="mapfunction,27"
mapfunction=yes
show=both

// 30
[mapelement_30]
category=category_1079
sprite="mapfunction,28"
mapfunction=yes
show=both

// 31
[mapelement_31]
category=category_1080
sprite="mapfunction,29"
mapfunction=yes
show=both

// 32
[mapelement_32]
category=category_1081
sprite="mapfunction,30"
mapfunction=yes
show=both

// 33
[mapelement_33]
category=category_1082
sprite="mapfunction,31"
mapfunction=yes
show=both

// 34
[mapelement_34]
category=category_1083
sprite="mapfunction,32"
mapfunction=yes
show=both

// 35
[mapelement_35]
category=category_1084
sprite="mapfunction,33"
mapfunction=yes
show=both

// 36
[mapelement_36]
category=category_1085
sprite="mapfunction,34"
mapfunction=yes
show=both

// 37
[mapelement_37]
category=category_1086
sprite="mapfunction,35"
mapfunction=yes
show=both

// 38
[mapelement_38]
category=category_1081
sprite="mapfunction,36"
mapfunction=yes
show=both

// 39
[mapelement_39]
category=category_1081
sprite="mapfunction,37"
mapfunction=yes
show=both

// 40
[mapelement_40]
category=category_1087
sprite="mapfunction,38"
mapfunction=yes
show=both

// 41
[mapelement_41]
category=category_1088
sprite="mapfunction,39"
mapfunction=yes
show=both

// 42
[mapelement_42]
category=category_1089
sprite="mapfunction,40"
mapfunction=yes
show=both

// 43
[mapelement_43]
category=category_1090
sprite="mapfunction,41"
mapfunction=yes
show=both

// 44
[mapelement_44]
category=category_1091
sprite="mapfunction,42"
mapfunction=yes
show=both

// 45
[mapelement_45]
category=category_1092
sprite="mapfunction,43"
mapfunction=yes
show=both

// 46
[mapelement_46]
category=category_1093
sprite="mapfunction,44"
mapfunction=yes
show=both

// 47
[mapelement_47]
category=category_1094
sprite="mapfunction,45"
mapfunction=yes
show=both

// 48
[mapelement_48]
category=category_1095
sprite="mapfunction,46"
mapfunction=yes
show=both

// 49
[mapelement_49]
category=category_1096
sprite="mapfunction,47"
mapfunction=yes
show=both

// 50
[mapelement_50]
category=category_1097
sprite="mapfunction,48"
mapfunction=yes
show=both

// 51
[mapelement_51]
category=category_1098
sprite="mapfunction,49"
mapfunction=yes
show=both

// 52
[mapelement_52]
category=category_1081
sprite="mapfunction,50"
mapfunction=yes
show=both

// 53
[mapelement_53]
category=category_1099
sprite="mapfunction,51"
mapfunction=yes
show=both

// 54
[mapelement_54]
category=category_1100
sprite="mapfunction,52"
mapfunction=yes
show=both

// 55
[mapelement_55]
category=category_1101
sprite="mapfunction,53"
mapfunction=yes
show=both

// 56
[mapelement_56]
category=category_1102
sprite="mapfunction,54"
mapfunction=yes
show=both

// 57
[mapelement_57]
category=category_1103
sprite="mapfunction,55"
mapfunction=yes
show=both

// 58
[mapelement_58]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 59
[mapelement_59]
category=category_1105
sprite="mapfunction,57"
mapfunction=yes
show=both

// 60
[mapelement_60]
category=category_1106
sprite="mapfunction,58"
mapfunction=yes
show=both

// 61
[mapelement_61]
category=category_1107
sprite="mapfunction,59"
mapfunction=yes
show=both

// 62
[mapelement_62]
category=category_1108
sprite="mapfunction,60"
mapfunction=yes
show=both

// 63
[mapelement_63]
category=category_1109
sprite="mapfunction,61"
mapfunction=yes
show=both

// 64
[mapelement_64]
category=category_1110
sprite="mapfunction,62"
mapfunction=yes
show=both

// 65
[mapelement_65]
category=category_1111
sprite="mapfunction,63"
mapfunction=yes
show=both

// 66
[mapelement_66]
category=category_1112
sprite="mapfunction,64"
mapfunction=yes
show=both

// 67
[mapelement_67]
category=category_1113
sprite="mapfunction,65"
mapfunction=yes
show=both

// 68
[mapelement_68]
category=category_1114
sprite="mapfunction,67"
mapfunction=yes
show=both

// 69
[mapelement_69]
category=category_1115
sprite="mapfunction,68"
mapfunction=yes
show=both

// 70
[mapelement_70]
category=category_1116
sprite="mapfunction,69"
mapfunction=yes
show=both

// 71
[mapelement_71]
category=category_1117
sprite="mapfunction,70"
mapfunction=yes
show=both

// 72
[mapelement_72]
category=category_1118
sprite="mapfunction,71"
mapfunction=yes
show=both

// 73
[mapelement_73]
category=category_1119
sprite="mapfunction,72"
mapfunction=yes
show=both

// 74
[mapelement_74]
category=category_1120
sprite="mapfunction,73"
mapfunction=yes
show=both

// 75
[mapelement_75]
category=category_1121
sprite="mapfunction,74"
mapfunction=yes
show=both

// 76
[mapelement_76]
category=category_1122
sprite="mapfunction,75"
mapfunction=yes
show=both

// 77
[mapelement_77]
category=category_1123
sprite="mapfunction,76"
mapfunction=yes
show=both

// 78
[mapelement_78]
category=category_1124
sprite="mapfunction,77"
mapfunction=yes
show=both

// 79
[mapelement_79]
category=category_1125
sprite="mapfunction,78"
mapfunction=yes
show=both

// 80
[mapelement_80]
category=category_1125
sprite="mapfunction,79"
mapfunction=yes
show=both

// 81
[mapelement_81]
category=category_1125
sprite="mapfunction,80"
mapfunction=yes
show=both

// 82
[mapelement_82]
category=category_1125
sprite="mapfunction,81"
mapfunction=yes
show=both

// 83
[mapelement_83]
category=category_1125
sprite="mapfunction,82"
mapfunction=yes
show=both

// 84
[mapelement_84]
category=category_1126
sprite="mapfunction,83"
mapfunction=yes
show=both

// 85
[mapelement_85]
category=category_1127
sprite="mapfunction,84"
mapfunction=yes
show=both

// 86
[mapelement_86]
category=category_1128
sprite="mapfunction,85"
mapfunction=yes
show=both

// 87
[mapelement_87]
text=Lumbridge
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 88
[mapelement_88]
text=Varrock
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 89
[mapelement_89]
text=Kingdom of<br>Misthalin
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 90
[mapelement_90]
text=Al Kharid
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 91
[mapelement_91]
text=Duel<br>Arena
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 92
[mapelement_92]
text=Shantay<br>Pass
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 93
[mapelement_93]
text=Toll<br>Gate
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 94
[mapelement_94]
text=Tutorial Island
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 95
[mapelement_95]
text=Port<br>Sarim
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 96
[mapelement_96]
text=Falador
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 97
[mapelement_97]
text=Edgeville
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 98
[mapelement_98]
text=Brimhaven
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 99
[mapelement_99]
text=Karamja
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 100
[mapelement_100]
text=Crandor
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 101
[mapelement_101]
text=Entrana
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 102
[mapelement_102]
text=Draynor<br>Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 103
[mapelement_103]
text=Jail
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 104
[mapelement_104]
text=Market
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 105
[mapelement_105]
text=Draynor Manor
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 106
[mapelement_106]
text=Barbarian<br>Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 107
[mapelement_107]
text=Desert Mining<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 108
[mapelement_108]
text=Bedabin<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 109
[mapelement_109]
text=Exam Centre
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 110
[mapelement_110]
text=Digsite
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 111
[mapelement_111]
text=Lumber Yard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 112
[mapelement_112]
text=Palace
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 113
[mapelement_113]
text=Grand Exchange
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 114
[mapelement_114]
text=Cooks'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 115
[mapelement_115]
text=Monastery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 116
[mapelement_116]
text=Dwarven<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 117
[mapelement_117]
text=Ice<br>Mountain
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 118
[mapelement_118]
text=Black Knights'<br>Fortress
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 119
[mapelement_119]
text=Goblin<br>Village
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 120
[mapelement_120]
text=White Knights'<br>Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 121
[mapelement_121]
text=Park
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 122
[mapelement_122]
text=Kingdom of<br>Asgarnia
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 123
[mapelement_123]
text=Dark Wizards'<br>Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 124
[mapelement_124]
text=Slayer<br>Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 125
[mapelement_125]
text=Melzar's<br>Maze
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 126
[mapelement_126]
text=Rimmington
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 127
[mapelement_127]
text=Wizards' Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 128
[mapelement_128]
text=Lumbridge<br>Swamp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 129
[mapelement_129]
text=Fishing<br>Platform
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 130
[mapelement_130]
text=Tai Bwo Wannai
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 131
[mapelement_131]
text=Shilo Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 132
[mapelement_132]
text=Ship Yard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 133
[mapelement_133]
text=Cairn Isle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 134
[mapelement_134]
text=Kharazi Jungle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 135
[mapelement_135]
text=Chaos<br>Temple
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 136
[mapelement_136]
text=Graveyard of<br>Shadows
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 137
[mapelement_137]
text=Bandit<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 138
[mapelement_138]
text=Dark Warriors'<br>Fortress
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 139
[mapelement_139]
text=Ruins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 140
[mapelement_140]
text=The Forgotten<br>Cemetery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 141
[mapelement_141]
text=Bone Yard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 142
[mapelement_142]
text=Lava Dragon<br>Isle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 143
[mapelement_143]
text=Wilderness
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 144
[mapelement_144]
text=Lava Maze
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 145
[mapelement_145]
text=Frozen Waste<br>Plateau
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 146
[mapelement_146]
text=Agility Training<br>Area
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 147
[mapelement_147]
text=Pirates'<br>Hideout
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 148
[mapelement_148]
text=Mage Arena
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 149
[mapelement_149]
text=Deserted<br>Keep
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 150
[mapelement_150]
text=Resource Area
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 151
[mapelement_151]
text=Scorpion<br>Pit
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 152
[mapelement_152]
text=Rogues' Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 153
[mapelement_153]
text=Demonic<br>Ruins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 154
[mapelement_154]
text=Fountain<br>of Rune
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 155
[mapelement_155]
text=Bear
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 156
[mapelement_156]
text=Spider
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 157
[mapelement_157]
text=Heroes'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 158
[mapelement_158]
text=Druids'<br>Circle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 159
[mapelement_159]
text=Taverley
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 160
[mapelement_160]
text=White Wolf<br>Mountain
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 161
[mapelement_161]
text=Catherby
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 162
[mapelement_162]
text=Camelot<br>Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 163
[mapelement_163]
text=Seers'<br>Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 164
[mapelement_164]
text=Sinclair Mansion
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 165
[mapelement_165]
text=Flax
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 166
[mapelement_166]
text=Beehives
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 167
[mapelement_167]
text=Sorcerer's Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 168
[mapelement_168]
text=Keep<br>Le Faye
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 169
[mapelement_169]
text=Legends'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 170
[mapelement_170]
text=Hemenster
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 171
[mapelement_171]
text=McGrubor's<br>Wood
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 172
[mapelement_172]
text=Coal<br>Trucks
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 173
[mapelement_173]
text=Fishing<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 174
[mapelement_174]
text=Kingdom of<br>Kandarin
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 175
[mapelement_175]
text=East<br>Ardougne
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 176
[mapelement_176]
text=West<br>Ardougne
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 177
[mapelement_177]
text=Combat<br>Training<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 178
[mapelement_178]
text=Agility<br>Training<br>Area
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 179
[mapelement_179]
text=Tree Gnome<br>Stronghold
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 180
[mapelement_180]
text=Grand Tree
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 181
[mapelement_181]
text=Swamp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 182
[mapelement_182]
text=Gnome Ball<br>Field
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 183
[mapelement_183]
text=Barbarian<br>Outpost
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 184
[mapelement_184]
text=Underground<br>Pass
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 185
[mapelement_185]
text=Battlefield
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 186
[mapelement_186]
text=Baxtorian<br>Falls
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 187
[mapelement_187]
text=Tree Gnome<br>Village
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 188
[mapelement_188]
text=Fight<br>Arena
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 189
[mapelement_189]
text=Port<br>Khazard
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 190
[mapelement_190]
text=Yanille
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 191
[mapelement_191]
text=Wizards'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 192
[mapelement_192]
text=Nightmare<br>Zone
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 193
[mapelement_193]
text=Observatory
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 194
[mapelement_194]
text=Necromancer
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 195
[mapelement_195]
text=Gu'Tanoth
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 196
[mapelement_196]
text=Feldip<br>Hills
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 197
[mapelement_197]
text=Ardougne<br>Zoo
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 198
[mapelement_198]
text=Morytania
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 199
[mapelement_199]
text=Mort Myre<br>Swamp
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 200
[mapelement_200]
text=Canifis
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 201
[mapelement_201]
text=River<br>Salve
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 202
[mapelement_202]
text=River Lum
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 203
[mapelement_203]
text=Temple
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 204
[mapelement_204]
text=Agility<br>Arena
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 205
[mapelement_205]
text=Burthorpe
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 206
[mapelement_206]
text=Death<br>Plateau
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 207
[mapelement_207]
text=Tirannwn
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 208
[mapelement_208]
text=Isafdar
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 209
[mapelement_209]
text=Arandar
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 210
[mapelement_210]
text=Prifddinas
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 211
[mapelement_211]
text=Tyras<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 212
[mapelement_212]
text=Elf<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 213
[mapelement_213]
text=Trollheim
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 214
[mapelement_214]
text=Troll<br>Stronghold
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 215
[mapelement_215]
text=Mort'ton
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 216
[mapelement_216]
text=The<br>Hollows
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 217
[mapelement_217]
text=Poison Waste
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 218
[mapelement_218]
text=Castle Wars
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 219
[mapelement_219]
text=Champions'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 220
[mapelement_220]
text=Rellekka
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 221
[mapelement_221]
text=Golden<br>Apple Tree
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 222
[mapelement_222]
text=Lighthouse
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 223
[mapelement_223]
text=Fremennik<br>Province
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 224
[mapelement_224]
text=Crafting<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 225
[mapelement_225]
text=Haunted<br>Woods
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 226
[mapelement_226]
text=Miscellania
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 227
[mapelement_227]
text=Etceteria
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 228
[mapelement_228]
text=Ape Atoll
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 229
[mapelement_229]
text=Crash<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 230
[mapelement_230]
text=Marim
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 231
[mapelement_231]
text=Fenkenstrain's<br>Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 232
[mapelement_232]
text=Mausoleum
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 233
[mapelement_233]
text=Trollweiss<br>Mountain
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 234
[mapelement_234]
text=Abandoned<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 235
[mapelement_235]
text=Ruins of<br>Uzer
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 236
[mapelement_236]
text=River<br>Elid
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 237
[mapelement_237]
text=Kalphite<br>Lair
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 238
[mapelement_238]
text=Pollnivneach
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 239
[mapelement_239]
text=Pyramid
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 240
[mapelement_240]
text=Menaphos
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 241
[mapelement_241]
text=Sophanem
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 242
[mapelement_242]
text=Agility<br>Pyramid
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 243
[mapelement_243]
text=Graveyard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 244
[mapelement_244]
text=Port<br>Phasmatys
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 245
[mapelement_245]
text=Ectofuntus
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 246
[mapelement_246]
text=Mountain<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 247
[mapelement_247]
text=Kharidian<br>Desert
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 248
[mapelement_248]
text=Ice path
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 249
[mapelement_249]
text=God Wars<br>Dungeon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 250
[mapelement_250]
text=Barrows
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 251
[mapelement_251]
text=Jiggig
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 252
[mapelement_252]
text=Mudskipper<br>Point
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 253
[mapelement_253]
text=Nardah
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 254
[mapelement_254]
text=Mage<br>Training<br>Arena
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 255
[mapelement_255]
text=Keldagrim<br>Entrance
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 256
[mapelement_256]
text=Waterbirth<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 257
[mapelement_257]
text=Lletya
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 258
[mapelement_258]
text=Burgh de Rott
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 259
[mapelement_259]
text=Lizards
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 260
[mapelement_260]
text=Quarry
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 261
[mapelement_261]
text=Outpost
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 262
[mapelement_262]
text=Mos Le'Harmless
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 263
[mapelement_263]
text=Distilleries
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 264
[mapelement_264]
text=Ranging<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 265
[mapelement_265]
text=Dragontooth<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 266
[mapelement_266]
text=Piscatoris<br>Fishing<br>Colony
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 267
[mapelement_267]
text=Here be<br>penguins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 268
[mapelement_268]
text=Void Knights'<br>Outpost
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 269
[mapelement_269]
text=Lunar Isle
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 270
[mapelement_270]
text=Pirates' Cove
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 271
[mapelement_271]
text=Vultures
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 272
[mapelement_272]
text=Port<br>Tyras
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 273
[mapelement_273]
text=Castle<br>Drakan
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 274
[mapelement_274]
text=Sanguinesti<br>region
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 275
[mapelement_275]
text=Meiyerditch
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 276
[mapelement_276]
text=Witchaven
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 277
[mapelement_277]
text=Warriors'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 278
[mapelement_278]
text=Musa Point
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 279
[mapelement_279]
text=Eagles'<br>Peak
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 280
[mapelement_280]
text=Falconer
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 281
[mapelement_281]
text=Barbarian<br>Assault
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 282
[mapelement_282]
text=Iceberg
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 283
[mapelement_283]
text=Pest<br>Control
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 284
[mapelement_284]
text=Neitiznot
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 285
[mapelement_285]
text=Jatizso
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 286
[mapelement_286]
text=Fremennik Isles
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 287
[mapelement_287]
text=Tower of<br>Life
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 288
[mapelement_288]
text=Clocktower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 289
[mapelement_289]
text=Harmony
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 290
[mapelement_290]
text=Trawler
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 291
[mapelement_291]
text=Otto's<br>Grotto
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 292
[mapelement_292]
text=Clan Wars
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 293
[mapelement_293]
text=Zul-Andra
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 294
[mapelement_294]
text=Zulrah's<br>shrine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 295
[mapelement_295]
text=Zeah
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 296
[mapelement_296]
text=Kingdom of<br>Great Kourend
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 297
[mapelement_297]
text=Arceuus<br>House
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 298
[mapelement_298]
text=Hosidius House
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 299
[mapelement_299]
text=Lovakengj<br>House
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 300
[mapelement_300]
text=Piscarilius<br>House
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 301
[mapelement_301]
text=Shayzien<br>House
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 302
[mapelement_302]
text=Library
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 303
[mapelement_303]
text=Dark<br>Altar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 304
[mapelement_304]
text=Sulphur<br>mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 305
[mapelement_305]
text=Blast mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 306
[mapelement_306]
text=Lovakite<br>mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 307
[mapelement_307]
text=Tower of<br>Magic
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 308
[mapelement_308]
text=Mess
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 309
[mapelement_309]
text=Saltpetre
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 310
[mapelement_310]
text=Tithe farm
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 311
[mapelement_311]
text=Charcoal<br>burners
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 312
[mapelement_312]
text=Infirmary
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 313
[mapelement_313]
text=Lizardman<br>Canyon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 314
[mapelement_314]
text=Combat<br>ring
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 315
[mapelement_315]
text=Graveyard of<br>Heroes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 316
[mapelement_316]
text=Shamans
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 317
[mapelement_317]
text=Vinery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 318
[mapelement_318]
text=Woodcutting<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 319
[mapelement_319]
text=Doors of<br>Dinh
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 320
[mapelement_320]
text=Wintertodt
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 321
[mapelement_321]
text=Settlement<br>Ruins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 322
[mapelement_322]
text=Fishing Hamlet
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 323
[mapelement_323]
text=Land's<br>End
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 324
[mapelement_324]
text=Xeric's<br>Look out
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 325
[mapelement_325]
text=Kourend<br>Woodland
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 326
[mapelement_326]
text=Unmarked<br>Grave
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 327
[mapelement_327]
text=Crabclaw<br>Isle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 328
[mapelement_328]
text=Shayziens'<br>Wall
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 329
[mapelement_329]
text=Lacerta<br>Falls
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 330
[mapelement_330]
text=Xeric's<br>Shrine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 331
[mapelement_331]
text=Lizardman<br>Settlement
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 332
[mapelement_332]
text=Mount<br>Quidamortem
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 333
[mapelement_333]
text=Chasm of Fire
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 334
[mapelement_334]
text=Lower level
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 335
[mapelement_335]
text=Middle level
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 336
[mapelement_336]
text=Upper level
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 337
[mapelement_337]
text=Waterfiends
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 338
[mapelement_338]
text=Mithril<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 339
[mapelement_339]
text=Brutal green<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 340
[mapelement_340]
text=Shadow<br>warriors
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 341
[mapelement_341]
text=Pit scorpions
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 342
[mapelement_342]
text=Hobgoblins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 343
[mapelement_343]
text=Ardougne<br>Sewers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 344
[mapelement_344]
text=Zombies & rocks
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 345
[mapelement_345]
text=Rat Pits
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 346
[mapelement_346]
text=Bats
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 347
[mapelement_347]
text=Ogres
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 348
[mapelement_348]
text=Dungeon<br>rats
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 349
[mapelement_349]
text=Spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 350
[mapelement_350]
text=Here be<br>goblins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 351
[mapelement_351]
text=Skeletal wyverns
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 352
[mapelement_352]
text=Pirates
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 353
[mapelement_353]
text=Muggers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 354
[mapelement_354]
text=Ice warriors<br>& giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 355
[mapelement_355]
text=Distillery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 356
[mapelement_356]
text=Dead people
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 357
[mapelement_357]
text=Nothing<br>interesting<br>happens<br>here
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 358
[mapelement_358]
text=Agility course
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 359
[mapelement_359]
text=Wire<br>machine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 360
[mapelement_360]
text=Bone<br>collector
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 361
[mapelement_361]
text=Oldak's<br>teleportation<br>laboratory
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 362
[mapelement_362]
text=Station
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 363
[mapelement_363]
text=Council<br>chamber
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 364
[mapelement_364]
text=Ur-tag
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 365
[mapelement_365]
text=Ur-meg
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 366
[mapelement_366]
text=Ur-zek & Ur-taal
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 367
[mapelement_367]
text=Tegdak
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 368
[mapelement_368]
text=Ur-vass
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 369
[mapelement_369]
text=Nursery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 370
[mapelement_370]
text=Zanik's<br>bedroom
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 371
[mapelement_371]
text=Beware of<br>the scorpions
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 372
[mapelement_372]
text=Mining Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 373
[mapelement_373]
text=Access to<br>Falador
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 374
[mapelement_374]
text=Hammerspike's<br>hangout
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 375
[mapelement_375]
text=Boot
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 376
[mapelement_376]
text=Kurask
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 377
[mapelement_377]
text=Cave crawlers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 378
[mapelement_378]
text=Turoth
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 379
[mapelement_379]
text=Basilisks
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 380
[mapelement_380]
text=Rock<br>slugs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 381
[mapelement_381]
text=Cockatrice
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 382
[mapelement_382]
text=Pyrefiends
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 383
[mapelement_383]
text=Jellies
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 384
[mapelement_384]
text=Saradomin's<br>Encampment
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 385
[mapelement_385]
text=Zamorak's<br>Fortress
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 386
[mapelement_386]
text=Armadyl's<br>Eyrie
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 387
[mapelement_387]
text=Bandos's<br>Stronghold
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 388
[mapelement_388]
text=Queen's<br>Chamber
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 389
[mapelement_389]
text=Soldiers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 390
[mapelement_390]
text=Guardians
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 391
[mapelement_391]
text=Moss giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 392
[mapelement_392]
text=Dogs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 393
[mapelement_393]
text=Fire<br>giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 394
[mapelement_394]
text=Red dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 395
[mapelement_395]
text=Bronze<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 396
[mapelement_396]
text=Iron & steel<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 397
[mapelement_397]
text=Bronze, iron &<br>steel dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 398
[mapelement_398]
text=Greater demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 399
[mapelement_399]
text=Jogres
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 400
[mapelement_400]
text=Elvarg
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 401
[mapelement_401]
text=Lesser demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 402
[mapelement_402]
text=Baby green<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 403
[mapelement_403]
text=Black demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 404
[mapelement_404]
text=Black<br>demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 405
[mapelement_405]
text=Red Spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 406
[mapelement_406]
text=Skeletons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 407
[mapelement_407]
text=River Kelda
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 408
[mapelement_408]
text=Dondakan's<br>rock
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 409
[mapelement_409]
text=Minecarts
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 410
[mapelement_410]
text=Blast<br>Furnace
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 411
[mapelement_411]
text=Brewery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 412
[mapelement_412]
text=Black<br>Guard<br>H.Q.
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 413
[mapelement_413]
text=Trolls
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 414
[mapelement_414]
text=Exit
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 415
[mapelement_415]
text=Terror dogs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 416
[mapelement_416]
text=Essence<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 417
[mapelement_417]
text=Miscellania<br>Expansion
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 418
[mapelement_418]
text=Sea snakes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 419
[mapelement_419]
text=H.A.M. Cult
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 420
[mapelement_420]
text=Draynor Sewers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 421
[mapelement_421]
text=Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 422
[mapelement_422]
text=Watermill<br>cellar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 423
[mapelement_423]
text=Champions'<br>Challenge
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 424
[mapelement_424]
text=Draynor Manor<br>basement
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 425
[mapelement_425]
text=VTAM Corporation
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 426
[mapelement_426]
text=Bank vault
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 427
[mapelement_427]
text=Goblin Maze
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 428
[mapelement_428]
text=Chasm of<br>Tears
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 429
[mapelement_429]
text=Tears of<br>Guthix
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 430
[mapelement_430]
text=Lumbridge<br>Castle<br>cellar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 431
[mapelement_431]
text=Giant frogs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 432
[mapelement_432]
text=Hill giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 433
[mapelement_433]
text=Chronozon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 434
[mapelement_434]
text=Here be<br>dead stuff
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 435
[mapelement_435]
text=Thugs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 436
[mapelement_436]
text=Dave's<br>Basement<br>of Doom
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 437
[mapelement_437]
text=Poison spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 438
[mapelement_438]
text=Poison<br>spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 439
[mapelement_439]
text=Zombies
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 440
[mapelement_440]
text=Skeletons<br>& zombies
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 441
[mapelement_441]
text=Earth warriors
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 442
[mapelement_442]
text=Chaos<br>druids
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 443
[mapelement_443]
text=Rats
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 444
[mapelement_444]
text=Here be a<br>big mole
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 445
[mapelement_445]
text=Motherlode Mine
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 446
[mapelement_446]
text=Obstacle<br>course
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 447
[mapelement_447]
text=Skullball
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 448
[mapelement_448]
text=Shades
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 449
[mapelement_449]
text=Here be odd stuff
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 450
[mapelement_450]
text=Nechryael
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 451
[mapelement_451]
text=Abyssal<br>demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 452
[mapelement_452]
text=Bloodvelds
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 453
[mapelement_453]
text=Gargoyles
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 454
[mapelement_454]
text=Aberrant<br>Spectres
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 455
[mapelement_455]
text=Ankou
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 456
[mapelement_456]
text=Cave horrors<br>&<br>albino bats
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 457
[mapelement_457]
text=Altar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 458
[mapelement_458]
text=Lizards &<br>Zamorak fighters
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 459
[mapelement_459]
text=War
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 460
[mapelement_460]
text=Gift of<br>Peace
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 461
[mapelement_461]
text=Famine
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 462
[mapelement_462]
text=Grain of<br>Plenty
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 463
[mapelement_463]
text=Pestilence
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 464
[mapelement_464]
text=Box of<br>Health
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 465
[mapelement_465]
text=Death
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 466
[mapelement_466]
text=Cradle of<br>Life
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 467
[mapelement_467]
text=Cauldron of<br>Thunder
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 468
[mapelement_468]
text=Black Knights'<br>Base
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 469
[mapelement_469]
text=Hellhounds
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 470
[mapelement_470]
text=Fire Obelisk
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 471
[mapelement_471]
text=Black dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 472
[mapelement_472]
text=Black<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 473
[mapelement_473]
text=Dramen Tree
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 474
[mapelement_474]
text=Animated<br>axes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 475
[mapelement_475]
text=Chaos<br>dwarves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 476
[mapelement_476]
text=Blue<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 477
[mapelement_477]
text=Poisonous<br>scorpions
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 478
[mapelement_478]
text=Cyclopes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 479
[mapelement_479]
text=Cyclopes<br>& Axes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 480
[mapelement_480]
text=Ice Queen's<br>Lair
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 481
[mapelement_481]
text=Fountain<br>of Heroes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 482
[mapelement_482]
text=Mountain<br>dwarves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 483
[mapelement_483]
text=Nora T. Hagg's<br>cellar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 484
[mapelement_484]
text=Key Master
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 485
[mapelement_485]
text=Beware of<br>the dog
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 486
[mapelement_486]
text=Anger
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 487
[mapelement_487]
text=Hopelessness
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 488
[mapelement_488]
text=Confusion
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 489
[mapelement_489]
text=Fear
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 490
[mapelement_490]
text=Goutweed<br>store
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 491
[mapelement_491]
text=Troll<br>generals
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 492
[mapelement_492]
text=Burntmeat's<br>Kitchen
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 493
[mapelement_493]
text=Fight Pit
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 494
[mapelement_494]
text=Fight Cave
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 495
[mapelement_495]
text=Sub-level 1
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 496
[mapelement_496]
text=Sub-level 2
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 497
[mapelement_497]
text=Sub-level 3
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 498
[mapelement_498]
text=Sub-level 4
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 499
[mapelement_499]
text=Sub-level 5
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 500
[mapelement_500]
text=Sub-level 6
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 501
[mapelement_501]
text=Dagannoth
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 502
[mapelement_502]
text=Giant rock crabs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 503
[mapelement_503]
text=Giant<br>rock crabs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 504
[mapelement_504]
text=Rock lobsters
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 505
[mapelement_505]
text=Rock<br>lobsters
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 506
[mapelement_506]
text=Wallasalki
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 507
[mapelement_507]
text=Dagannoth Kings
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 508
[mapelement_508]
text=Shadow<br>spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 509
[mapelement_509]
text=Agility<br>course<br>spikes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 510
[mapelement_510]
text=Mage Arena<br>bank
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 511
[mapelement_511]
text=King<br>Black<br>Dragon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 512
[mapelement_512]
text=Corporeal<br>Beast
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 513
[mapelement_513]
text=Salarin the<br>Twisted
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 514
[mapelement_514]
text=Smoke devils
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 515
[mapelement_515]
text=Thermonuclear<br>Smoke Devil
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 516
[mapelement_516]
text=Throne room
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 517
[mapelement_517]
text=Beware of the<br>mushrooms
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 518
[mapelement_518]
text=Shrine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 519
[mapelement_519]
text=Otherworldly<br>beings
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 520
[mapelement_520]
text=Puro-puro
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 521
[mapelement_521]
text=Tanglefeet
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 522
[mapelement_522]
text=Brimstail
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 523
[mapelement_523]
text=Voice of Yama
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 524
[mapelement_524]
text=Ents
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 525
[mapelement_525]
text=Black, blue &<br>red dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 526
[mapelement_526]
text=Bronze & iron<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 527
[mapelement_527]
text=Steel<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 528
[mapelement_528]
text=Dark<br>beasts
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 529
[mapelement_529]
text=Ghosts
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 530
[mapelement_530]
text=Dust devils
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 531
[mapelement_531]
text=Sand<br>crabs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 532
[mapelement_532]
text=Spectres
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 533
[mapelement_533]
text=Banshees
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 534
[mapelement_534]
text=Mor Ul Rek
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 535
[mapelement_535]
text=The Inferno
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 536
[mapelement_536]
text=Lizardman<br>Caves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 537
[mapelement_537]
text=Underwater
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 538
[mapelement_538]
text=Wyverns
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 539
[mapelement_539]
text=Wyverns<br>(Task Only)
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 540
[mapelement_540]
text=Volcano Mine
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 541
[mapelement_541]
text=A
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no
show=both

// 542
[mapelement_542]
text=B
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no
show=both

// 543
[mapelement_543]
text=C
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no
show=both

// 544
[mapelement_544]
text=Fossil<br>Island
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 545
[mapelement_545]
text=Museum<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 546
[mapelement_546]
text=The Warrens
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 547
[mapelement_547]
text=Mushroom<br>Forest
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 548
[mapelement_548]
text=House<br>on the<br>Hill
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 549
[mapelement_549]
text=Volcano
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 550
[mapelement_550]
text=Tar<br>Swamp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 551
[mapelement_551]
text=Crabclaw Caves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 552
[mapelement_552]
text=Wilderness<br>Emblem Trader
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 553
[mapelement_553]
text=Ice giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 554
[mapelement_554]
text=Greater<br>demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 555
[mapelement_555]
text=Green dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 556
[mapelement_556]
text=Green<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 557
[mapelement_557]
text=Revenants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 558
[mapelement_558]
text=Myths'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 559
[mapelement_559]
text=Corsair<br>Cove
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 560
[mapelement_560]
text=Ancient<br>Forge
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 561
[mapelement_561]
text=Ogresses
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 562
[mapelement_562]
text=Chinchompas
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 563
[mapelement_563]
text=Dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 564
[mapelement_564]
text=Baby dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 565
[mapelement_565]
text=Chapel
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

