// 0
[mapelement_0]
category=category_1049
sprite="mapfunction,0"
mapfunction=yes
show=both

// 1
[mapelement_1]
category=category_1050
sprite="mapfunction,1"
mapfunction=yes
show=both

// 2
[mapelement_2]
category=category_1052
sprite="mapfunction,2"
mapfunction=yes
show=both

// 3
[mapelement_3]
category=category_1053
sprite="mapfunction,3"
mapfunction=yes
show=both

// 4
[mapelement_4]
category=category_1054
sprite="mapfunction,4"
mapfunction=yes
show=both

// 5
[mapelement_5]
category=category_1055
sprite="mapfunction,5"
mapfunction=yes
show=both

// 6
[mapelement_6]
text=The Node
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 7
[mapelement_7]
category=category_1057
sprite="mapfunction,7"
mapfunction=yes
show=both

// 8
[mapelement_8]
category=category_1058
sprite="mapfunction,8"
mapfunction=yes
show=both

// 9
[mapelement_9]
category=category_1059
sprite="mapfunction,9"
mapfunction=yes
show=both

// 10
[mapelement_10]
category=category_1060
sprite="mapfunction,10"
mapfunction=yes
show=both

// 11
[mapelement_11]
category=category_1061
sprite="mapfunction,11"
mapfunction=yes
show=both

// 12
[mapelement_12]
category=category_1062
sprite="mapfunction,12"
mapfunction=yes
show=both

// 13
[mapelement_13]
category=category_1062
sprite="mapfunction,86"
op1=Open
mapfunction=no
show=both
opbase=Map

// 14
[mapelement_14]
category=category_1063
sprite="mapfunction,87"
op1=Open
mapfunction=no
opbase=Map

// 15
[mapelement_15]
category=category_1064
sprite="mapfunction,13"
mapfunction=yes
show=both

// 16
[mapelement_16]
category=category_1065
sprite="mapfunction,14"
mapfunction=yes
show=both

// 17
[mapelement_17]
category=category_1066
sprite="mapfunction,15"
mapfunction=yes
show=both

// 18
[mapelement_18]
category=category_1067
sprite="mapfunction,16"
mapfunction=yes
show=both

// 19
[mapelement_19]
category=category_1068
sprite="mapfunction,17"
mapfunction=yes
show=both

// 20
[mapelement_20]
category=category_1069
sprite="mapfunction,18"
mapfunction=yes
show=both

// 21
[mapelement_21]
category=category_1070
sprite="mapfunction,19"
mapfunction=yes
show=both

// 22
[mapelement_22]
category=category_1071
sprite="mapfunction,20"
mapfunction=yes
show=both

// 23
[mapelement_23]
category=category_1072
sprite="mapfunction,21"
mapfunction=yes
show=both

// 24
[mapelement_24]
category=category_1073
sprite="mapfunction,22"
mapfunction=yes
show=both

// 25
[mapelement_25]
category=category_1074
sprite="mapfunction,23"
mapfunction=yes
show=both

// 26
[mapelement_26]
category=category_1075
sprite="mapfunction,24"
mapfunction=yes
show=both

// 27
[mapelement_27]
category=category_1076
sprite="mapfunction,25"
mapfunction=yes
show=both

// 28
[mapelement_28]
category=category_1077
sprite="mapfunction,26"
mapfunction=yes
show=both

// 29
[mapelement_29]
category=category_1078
sprite="mapfunction,27"
mapfunction=yes
show=both

// 30
[mapelement_30]
category=category_1079
sprite="mapfunction,28"
mapfunction=yes
show=both

// 31
[mapelement_31]
category=category_1080
sprite="mapfunction,29"
mapfunction=yes
show=both

// 32
[mapelement_32]
category=category_1081
sprite="mapfunction,30"
mapfunction=yes
show=both

// 33
[mapelement_33]
category=category_1082
sprite="mapfunction,31"
mapfunction=yes
show=both

// 34
[mapelement_34]
category=category_1083
sprite="mapfunction,32"
mapfunction=yes
show=both

// 35
[mapelement_35]
category=category_1084
sprite="mapfunction,33"
mapfunction=yes
show=both

// 36
[mapelement_36]
category=category_1085
sprite="mapfunction,34"
mapfunction=yes
show=both

// 37
[mapelement_37]
category=category_1086
sprite="mapfunction,35"
mapfunction=yes
show=both

// 38
[mapelement_38]
category=category_1081
sprite="mapfunction,36"
mapfunction=yes
show=both

// 39
[mapelement_39]
category=category_1081
sprite="mapfunction,37"
mapfunction=yes
show=both

// 40
[mapelement_40]
category=category_1087
sprite="mapfunction,38"
mapfunction=yes
show=both

// 41
[mapelement_41]
category=category_1088
sprite="mapfunction,39"
mapfunction=yes
show=both

// 42
[mapelement_42]
category=category_1089
sprite="mapfunction,40"
mapfunction=yes
show=both

// 43
[mapelement_43]
category=category_1090
sprite="mapfunction,41"
mapfunction=yes
show=both

// 44
[mapelement_44]
category=category_1091
sprite="mapfunction,42"
mapfunction=yes
show=both

// 45
[mapelement_45]
category=category_1092
sprite="mapfunction,43"
mapfunction=yes
show=both

// 46
[mapelement_46]
category=category_1093
sprite="mapfunction,44"
mapfunction=yes
show=both

// 47
[mapelement_47]
category=category_1094
sprite="mapfunction,45"
mapfunction=yes
show=both

// 48
[mapelement_48]
category=category_1095
sprite="mapfunction,46"
mapfunction=yes
show=both

// 49
[mapelement_49]
category=category_1096
sprite="mapfunction,47"
mapfunction=yes
show=both

// 50
[mapelement_50]
category=category_1097
sprite="mapfunction,48"
mapfunction=yes
show=both

// 51
[mapelement_51]
category=category_1098
sprite="mapfunction,49"
mapfunction=yes
show=both

// 52
[mapelement_52]
category=category_1081
sprite="mapfunction,50"
mapfunction=yes
show=both

// 53
[mapelement_53]
category=category_1099
sprite="mapfunction,51"
mapfunction=yes
show=both

// 54
[mapelement_54]
category=category_1100
sprite="mapfunction,52"
mapfunction=yes
show=both

// 55
[mapelement_55]
category=category_1101
sprite="mapfunction,53"
mapfunction=yes
show=both

// 56
[mapelement_56]
category=category_1102
sprite="mapfunction,54"
mapfunction=yes
show=both

// 57
[mapelement_57]
text=Weiss
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 58
[mapelement_58]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 59
[mapelement_59]
category=category_1105
sprite="mapfunction,57"
mapfunction=yes
show=both

// 60
[mapelement_60]
category=category_1106
sprite="mapfunction,58"
mapfunction=yes
show=both

// 61
[mapelement_61]
category=category_1107
sprite="mapfunction,59"
mapfunction=yes
show=both

// 62
[mapelement_62]
category=category_1108
sprite="mapfunction,60"
mapfunction=yes
show=both

// 63
[mapelement_63]
category=category_1109
sprite="mapfunction,61"
mapfunction=yes
show=both

// 64
[mapelement_64]
category=category_1110
sprite="mapfunction,62"
mapfunction=yes
show=both

// 65
[mapelement_65]
category=category_1111
sprite="mapfunction,63"
mapfunction=yes
show=both

// 66
[mapelement_66]
category=category_1112
sprite="mapfunction,64"
mapfunction=yes
show=both

// 67
[mapelement_67]
category=category_1113
sprite="mapfunction,65"
mapfunction=yes
show=both

// 68
[mapelement_68]
category=category_1114
sprite="mapfunction,67"
mapfunction=yes
show=both

// 69
[mapelement_69]
category=category_1115
sprite="mapfunction,68"
mapfunction=yes
show=both

// 70
[mapelement_70]
category=category_1116
sprite="mapfunction,69"
mapfunction=yes
show=both

// 71
[mapelement_71]
category=category_1117
sprite="mapfunction,70"
mapfunction=yes
show=both

// 72
[mapelement_72]
category=category_1118
sprite="mapfunction,71"
mapfunction=yes
show=both

// 73
[mapelement_73]
category=category_1119
sprite="mapfunction,72"
mapfunction=yes
show=both

// 74
[mapelement_74]
category=category_1120
sprite="mapfunction,73"
mapfunction=yes
show=both

// 75
[mapelement_75]
category=category_1121
sprite="mapfunction,74"
mapfunction=yes
show=both

// 76
[mapelement_76]
category=category_1122
sprite="mapfunction,75"
mapfunction=yes
show=both

// 77
[mapelement_77]
category=category_1123
sprite="mapfunction,76"
mapfunction=yes
show=both

// 78
[mapelement_78]
text=Salt Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 79
[mapelement_79]
category=category_1125
sprite="mapfunction,78"
mapfunction=yes
show=both

// 80
[mapelement_80]
category=category_1125
sprite="mapfunction,79"
mapfunction=yes
show=both

// 81
[mapelement_81]
category=category_1125
sprite="mapfunction,80"
mapfunction=yes
show=both

// 82
[mapelement_82]
category=category_1125
sprite="mapfunction,81"
mapfunction=yes
show=both

// 83
[mapelement_83]
category=category_1125
sprite="mapfunction,82"
mapfunction=yes
show=both

// 84
[mapelement_84]
category=category_1126
sprite="mapfunction,83"
mapfunction=yes
show=both

// 85
[mapelement_85]
text=Scurrius<br>The Rat King
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 86
[mapelement_86]
category=category_1128
sprite="mapfunction,132"
mapfunction=yes
show=both

// 87
[mapelement_87]
text=Lumbridge
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 88
[mapelement_88]
text=Varrock
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 89
[mapelement_89]
text=Kingdom of<br>Misthalin
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 90
[mapelement_90]
text=Al Kharid
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 91
[mapelement_91]
category=category_1716
sprite="mapfunction,85"
mapfunction=yes
show=both

// 92
[mapelement_92]
text=Shantay<br>Pass
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 93
[mapelement_93]
text=Toll<br>Gate
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 94
[mapelement_94]
text=Tutorial Island
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 95
[mapelement_95]
text=Port<br>Sarim
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 96
[mapelement_96]
text=Falador
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 97
[mapelement_97]
text=Edgeville
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 98
[mapelement_98]
text=Brimhaven
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 99
[mapelement_99]
text=Karamja
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 100
[mapelement_100]
text=Crandor
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 101
[mapelement_101]
text=Entrana
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 102
[mapelement_102]
text=Draynor<br>Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 103
[mapelement_103]
text=Jail
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 104
[mapelement_104]
text=Market
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 105
[mapelement_105]
text=Draynor<br>Manor
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 106
[mapelement_106]
text=Barbarian<br>Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 107
[mapelement_107]
text=Desert Mining<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 108
[mapelement_108]
text=Bedabin<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 109
[mapelement_109]
text=Exam Centre
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 110
[mapelement_110]
text=Digsite
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 111
[mapelement_111]
text=Lumber Yard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 112
[mapelement_112]
text=Palace
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 113
[mapelement_113]
text=Grand Exchange
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 114
[mapelement_114]
text=Cooks'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 115
[mapelement_115]
text=Monastery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 116
[mapelement_116]
text=Dwarven<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 117
[mapelement_117]
text=Ice<br>Mountain
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 118
[mapelement_118]
text=Black Knights'<br>Fortress
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 119
[mapelement_119]
text=Goblin<br>Village
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 120
[mapelement_120]
text=White Knights'<br>Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 121
[mapelement_121]
text=Park
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 122
[mapelement_122]
text=Kingdom of<br>Asgarnia
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 123
[mapelement_123]
text=Dark Wizards'<br>Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 124
[mapelement_124]
text=Slayer<br>Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 125
[mapelement_125]
text=Melzar's<br>Maze
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 126
[mapelement_126]
text=Rimmington
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 127
[mapelement_127]
text=Wizards' Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 128
[mapelement_128]
text=Lumbridge<br>Swamp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 129
[mapelement_129]
text=Fishing<br>Platform
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 130
[mapelement_130]
text=Tai Bwo<br>Wannai
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 131
[mapelement_131]
text=Shilo Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 132
[mapelement_132]
text=Shipyard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 133
[mapelement_133]
text=Cairn Isle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 134
[mapelement_134]
text=Kharazi Jungle
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 135
[mapelement_135]
text=Chaos<br>Temple
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 136
[mapelement_136]
text=Graveyard of<br>Shadows
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 137
[mapelement_137]
text=Bandit<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 138
[mapelement_138]
text=Dark Warriors'<br>Fortress
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 139
[mapelement_139]
text=Ruins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 140
[mapelement_140]
text=The Forgotten<br>Cemetery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 141
[mapelement_141]
text=Bone Yard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 142
[mapelement_142]
text=Lava Dragon<br>Isle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 143
[mapelement_143]
text=Wilderness
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 144
[mapelement_144]
text=Lava Maze
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 145
[mapelement_145]
text=Frozen Waste<br>Plateau
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 146
[mapelement_146]
text=Slepe<br>Sound
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 147
[mapelement_147]
text=Pirates'<br>Hideout
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 148
[mapelement_148]
text=Mage Arena
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 149
[mapelement_149]
text=Deserted<br>Keep
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 150
[mapelement_150]
text=Resource<br>Area
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 151
[mapelement_151]
text=Scorpion<br>Pit
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 152
[mapelement_152]
text=Rogues'<br>Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 153
[mapelement_153]
text=Demonic<br>Ruins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 154
[mapelement_154]
text=Fountain<br>of Rune
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 155
[mapelement_155]
text=Bear
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 156
[mapelement_156]
text=Spider
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 157
[mapelement_157]
text=Heroes'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 158
[mapelement_158]
text=Druids'<br>Circle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 159
[mapelement_159]
text=Taverley
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 160
[mapelement_160]
text=White Wolf<br>Mountain
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 161
[mapelement_161]
text=Catherby
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 162
[mapelement_162]
text=Camelot<br>Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 163
[mapelement_163]
text=Seers'<br>Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 164
[mapelement_164]
text=Sinclair<br>Mansion
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 165
[mapelement_165]
category=category_2505
sprite="mapfunction,146"
mapfunction=no
show=both

// 166
[mapelement_166]
category=category_2505
sprite="mapfunction,146"
mapfunction=no
show=both

// 167
[mapelement_167]
text=Sorcerer's<br>Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 168
[mapelement_168]
text=Keep<br>Le Faye
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 169
[mapelement_169]
text=Legends'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 170
[mapelement_170]
text=Hemenster
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 171
[mapelement_171]
text=McGrubor's<br>Wood
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 172
[mapelement_172]
text=Coal<br>Trucks
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 173
[mapelement_173]
text=Fishing<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 174
[mapelement_174]
text=Kingdom of<br>Kandarin
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 175
[mapelement_175]
text=East<br>Ardougne
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 176
[mapelement_176]
text=West<br>Ardougne
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 177
[mapelement_177]
text=Combat<br>Training<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 178
[mapelement_178]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 179
[mapelement_179]
text=Tree Gnome<br>Stronghold
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 180
[mapelement_180]
text=Grand Tree
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 181
[mapelement_181]
text=Swamp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 182
[mapelement_182]
text=Gnomeball<br>Field
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 183
[mapelement_183]
text=Barbarian<br>Outpost
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 184
[mapelement_184]
text=Underground<br>Pass
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 185
[mapelement_185]
text=Battlefield
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 186
[mapelement_186]
text=Baxtorian<br>Falls
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 187
[mapelement_187]
text=Tree Gnome<br>Village
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 188
[mapelement_188]
text=Fight<br>Arena
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 189
[mapelement_189]
text=Port<br>Khazard
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 190
[mapelement_190]
text=Yanille
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 191
[mapelement_191]
text=Wizards'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 192
[mapelement_192]
text=Nightmare<br>Zone
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 193
[mapelement_193]
text=Observatory
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 194
[mapelement_194]
text=Necromancer's<br>Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 195
[mapelement_195]
text=Gu'Tanoth
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 196
[mapelement_196]
text=Feldip<br>Hills
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 197
[mapelement_197]
text=Ardougne<br>Zoo
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 198
[mapelement_198]
text=Morytania
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 199
[mapelement_199]
text=Mort Myre<br>Swamp
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 200
[mapelement_200]
text=Canifis
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 201
[mapelement_201]
text=River<br>Salve
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 202
[mapelement_202]
text=River Lum
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 203
[mapelement_203]
text=Crombwick<br>Manor
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 204
[mapelement_204]
text=Agility<br>Arena
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 205
[mapelement_205]
text=Burthorpe
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 206
[mapelement_206]
text=Death<br>Plateau
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 207
[mapelement_207]
text=Tirannwn
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 208
[mapelement_208]
text=Isafdar
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 209
[mapelement_209]
text=Arandar
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 210
[mapelement_210]
text=Prifddinas
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 211
[mapelement_211]
text=Tyras<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 212
[mapelement_212]
text=Iorwerth<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 213
[mapelement_213]
text=Trollheim
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 214
[mapelement_214]
text=Troll<br>Stronghold
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 215
[mapelement_215]
text=Mort'ton
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 216
[mapelement_216]
text=The<br>Hollows
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 217
[mapelement_217]
text=Poison Waste
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 218
[mapelement_218]
text=Castle Wars
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 219
[mapelement_219]
text=Champions'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 220
[mapelement_220]
text=Rellekka
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 221
[mapelement_221]
text=Golden<br>Apple Tree
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 222
[mapelement_222]
text=Lighthouse
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 223
[mapelement_223]
text=Fremennik<br>Province
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 224
[mapelement_224]
text=Crafting<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 225
[mapelement_225]
text=Haunted<br>Woods
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 226
[mapelement_226]
text=Miscellania
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 227
[mapelement_227]
text=Etceteria
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 228
[mapelement_228]
text=Ape Atoll
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 229
[mapelement_229]
text=Crash<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 230
[mapelement_230]
text=Marim
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 231
[mapelement_231]
text=Fenkenstrain's<br>Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 232
[mapelement_232]
text=Mausoleum
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 233
[mapelement_233]
text=Trollweiss<br>Mountain
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 234
[mapelement_234]
text=Abandoned<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 235
[mapelement_235]
text=Ruins of<br>Uzer
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 236
[mapelement_236]
text=River<br>Elid
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 237
[mapelement_237]
text=Kalphite<br>Lair
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 238
[mapelement_238]
text=Pollnivneach
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 239
[mapelement_239]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 240
[mapelement_240]
text=Menaphos
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 241
[mapelement_241]
text=Sophanem
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 242
[mapelement_242]
text=Jaleustrophos<br>Pyramid
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 243
[mapelement_243]
text=Graveyard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 244
[mapelement_244]
text=Port<br>Phasmatys
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 245
[mapelement_245]
text=Ectofuntus
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 246
[mapelement_246]
text=Mountain<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 247
[mapelement_247]
text=Kharidian<br>Desert
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 248
[mapelement_248]
text=Ice path
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 249
[mapelement_249]
text=God Wars<br>Dungeon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 250
[mapelement_250]
text=Barrows
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 251
[mapelement_251]
text=Jiggig
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 252
[mapelement_252]
text=Mudskipper<br>Point
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 253
[mapelement_253]
text=Nardah
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 254
[mapelement_254]
text=Mage<br>Training<br>Arena
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 255
[mapelement_255]
text=Keldagrim<br>Entrance
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 256
[mapelement_256]
text=Waterbirth<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 257
[mapelement_257]
text=Lletya
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 258
[mapelement_258]
text=Burgh de Rott
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 259
[mapelement_259]
text=Lizards
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 260
[mapelement_260]
text=Quarry
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 261
[mapelement_261]
text=Outpost
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 262
[mapelement_262]
text=Mos Le'Harmless
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 263
[mapelement_263]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 264
[mapelement_264]
text=Ranging<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 265
[mapelement_265]
text=Dragontooth<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 266
[mapelement_266]
text=Piscatoris<br>Fishing<br>Colony
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 267
[mapelement_267]
text=Here be<br>penguins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 268
[mapelement_268]
text=Void Knights'<br>Outpost
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 269
[mapelement_269]
text=Lunar Isle
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 270
[mapelement_270]
text=Pirates' Cove
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 271
[mapelement_271]
text=Vultures
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 272
[mapelement_272]
text=Port<br>Tyras
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 273
[mapelement_273]
text=Castle<br>Drakan
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 274
[mapelement_274]
category=category_1250
sprite="mapfunction,88"
mapfunction=yes
show=both

// 275
[mapelement_275]
text=Meiyerditch
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 276
[mapelement_276]
text=Witchaven
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 277
[mapelement_277]
text=Warriors'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 278
[mapelement_278]
text=Musa Point
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 279
[mapelement_279]
text=Eagles'<br>Peak
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 280
[mapelement_280]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 281
[mapelement_281]
text=Barbarian<br>Assault
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 282
[mapelement_282]
text=Iceberg
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 283
[mapelement_283]
text=Pest<br>Control
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 284
[mapelement_284]
text=Neitiznot
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 285
[mapelement_285]
text=Jatizso
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 286
[mapelement_286]
text=Fremennik Isles
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 287
[mapelement_287]
text=Tower of<br>Life
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 288
[mapelement_288]
text=Clock Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 289
[mapelement_289]
text=Harmony
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 290
[mapelement_290]
text=Trawler
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 291
[mapelement_291]
text=Otto's<br>Grotto
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 292
[mapelement_292]
text=Clan<br>Wars
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 293
[mapelement_293]
text=Zul-Andra
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 294
[mapelement_294]
text=Zulrah's<br>shrine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 295
[mapelement_295]
text=Silvarea
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 296
[mapelement_296]
text=Kingdom of<br>Great Kourend
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 297
[mapelement_297]
text=Arceuus
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 298
[mapelement_298]
text=Hosidius
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 299
[mapelement_299]
text=Lovakengj
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 300
[mapelement_300]
text=Port<br>Piscarilius
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 301
[mapelement_301]
text=Shayzien
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 302
[mapelement_302]
text=Library
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 303
[mapelement_303]
text=Dark<br>Altar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 304
[mapelement_304]
text=Sulphur<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 305
[mapelement_305]
text=Blast Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 306
[mapelement_306]
text=Lovakite<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 307
[mapelement_307]
text=Tower of<br>Magic
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 308
[mapelement_308]
text=Mess
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 309
[mapelement_309]
text=Saltpetre
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 310
[mapelement_310]
text=Tithe Farm
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 311
[mapelement_311]
text=Charcoal<br>Burners
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 312
[mapelement_312]
text=Infirmary
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 313
[mapelement_313]
text=Lizardman<br>Canyon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 314
[mapelement_314]
text=Combat<br>Ring
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 315
[mapelement_315]
text=Graveyard of<br>Heroes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 316
[mapelement_316]
text=Shamans
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 317
[mapelement_317]
text=Vinery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 318
[mapelement_318]
text=Woodcutting<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 319
[mapelement_319]
text=Doors of<br>Dinh
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 320
[mapelement_320]
text=The<br>Wintertodt
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 321
[mapelement_321]
text=Settlement<br>Ruins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 322
[mapelement_322]
text=Fishing Hamlet
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 323
[mapelement_323]
text=Land's<br>End
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 324
[mapelement_324]
text=Xeric's<br>Look out
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 325
[mapelement_325]
text=Kourend<br>Woodland
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 326
[mapelement_326]
text=Unmarked<br>Grave
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 327
[mapelement_327]
text=Crabclaw<br>Isle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 328
[mapelement_328]
text=Shayziens'<br>Wall
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 329
[mapelement_329]
text=Lacerta<br>Falls
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 330
[mapelement_330]
text=Xeric's<br>Shrine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 331
[mapelement_331]
text=Lizardman<br>Settlement
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 332
[mapelement_332]
text=Mount<br>Quidamortem
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 333
[mapelement_333]
text=Chasm of Fire
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 334
[mapelement_334]
text=Lower level
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 335
[mapelement_335]
text=Middle level
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 336
[mapelement_336]
text=Upper level
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 337
[mapelement_337]
text=Waterfiends
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 338
[mapelement_338]
text=Mithril<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 339
[mapelement_339]
text=Brutal green<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 340
[mapelement_340]
text=Shadow<br>warriors
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 341
[mapelement_341]
text=Pit scorpions
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 342
[mapelement_342]
text=Hobgoblins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 343
[mapelement_343]
text=Ardougne<br>Sewers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 344
[mapelement_344]
text=Zombies & rocks
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 345
[mapelement_345]
text=Rat Pits
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 346
[mapelement_346]
text=Bats
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 347
[mapelement_347]
text=Ogres
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 348
[mapelement_348]
text=Dungeon<br>rats
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 349
[mapelement_349]
text=Spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 350
[mapelement_350]
text=Here be<br>goblins
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 351
[mapelement_351]
text=Skeletal wyverns
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 352
[mapelement_352]
text=Pirates
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 353
[mapelement_353]
text=Muggers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 354
[mapelement_354]
text=Ice warriors<br>& giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 355
[mapelement_355]
text=Distillery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 356
[mapelement_356]
text=Dead people
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 357
[mapelement_357]
text=Nothing<br>interesting<br>happens<br>here
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 358
[mapelement_358]
text=Agility course
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 359
[mapelement_359]
text=Wire<br>machine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 360
[mapelement_360]
text=Bone<br>collector
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 361
[mapelement_361]
text=Oldak's<br>teleportation<br>laboratory
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 362
[mapelement_362]
text=Station
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 363
[mapelement_363]
text=Council<br>chamber
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 364
[mapelement_364]
text=Ur-tag
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 365
[mapelement_365]
text=Ur-meg
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 366
[mapelement_366]
text=Ur-zek & Ur-taal
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 367
[mapelement_367]
text=Tegdak
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 368
[mapelement_368]
text=Ur-vass
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 369
[mapelement_369]
text=Nursery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 370
[mapelement_370]
text=Zanik's<br>bedroom
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 371
[mapelement_371]
text=Beware of<br>the scorpions
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 372
[mapelement_372]
text=Mining Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 373
[mapelement_373]
text=Access to<br>Falador
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 374
[mapelement_374]
text=Hammerspike's<br>hangout
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 375
[mapelement_375]
text=Boot
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 376
[mapelement_376]
text=Kurask
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 377
[mapelement_377]
text=Cave crawlers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 378
[mapelement_378]
text=Turoth
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 379
[mapelement_379]
text=Basilisks
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 380
[mapelement_380]
text=Rock<br>slugs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 381
[mapelement_381]
text=Cockatrice
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 382
[mapelement_382]
text=Pyrefiends
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 383
[mapelement_383]
text=Jellies
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 384
[mapelement_384]
text=Saradomin's<br>Encampment
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 385
[mapelement_385]
text=Zamorak's<br>Fortress
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 386
[mapelement_386]
text=Armadyl's<br>Eyrie
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 387
[mapelement_387]
text=Bandos's<br>Stronghold
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 388
[mapelement_388]
text=Queen's<br>Chamber
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 389
[mapelement_389]
text=Soldiers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 390
[mapelement_390]
text=Guardians
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 391
[mapelement_391]
text=Moss giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 392
[mapelement_392]
text=Dogs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 393
[mapelement_393]
text=Fire<br>giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 394
[mapelement_394]
text=Red dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 395
[mapelement_395]
text=Bronze<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 396
[mapelement_396]
text=Iron & steel<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 397
[mapelement_397]
text=Bronze, iron &<br>steel dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 398
[mapelement_398]
text=Greater demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 399
[mapelement_399]
text=Jogres
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 400
[mapelement_400]
text=Elvarg
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 401
[mapelement_401]
text=Lesser demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 402
[mapelement_402]
text=Baby green<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 403
[mapelement_403]
text=Black demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 404
[mapelement_404]
text=Black<br>demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 405
[mapelement_405]
text=Red Spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 406
[mapelement_406]
text=Skeletons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 407
[mapelement_407]
text=River Kelda
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 408
[mapelement_408]
text=Dondakan's<br>rock
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 409
[mapelement_409]
text=Minecarts
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 410
[mapelement_410]
text=Blast<br>Furnace
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 411
[mapelement_411]
text=Brewery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 412
[mapelement_412]
text=Black<br>Guard<br>H.Q.
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 413
[mapelement_413]
text=Trolls
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 414
[mapelement_414]
text=Exit
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 415
[mapelement_415]
text=Terror dogs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 416
[mapelement_416]
text=Essence<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 417
[mapelement_417]
text=Miscellania<br>Expansion
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 418
[mapelement_418]
text=Sea snakes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 419
[mapelement_419]
text=H.A.M. Cult
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 420
[mapelement_420]
text=Draynor Sewers
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 421
[mapelement_421]
text=Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 422
[mapelement_422]
text=Watermill<br>cellar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 423
[mapelement_423]
text=Champions'<br>Challenge
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 424
[mapelement_424]
text=Draynor Manor<br>basement
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 425
[mapelement_425]
text=VTAM Corporation
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 426
[mapelement_426]
text=Bank vault
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 427
[mapelement_427]
text=Goblin Maze
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 428
[mapelement_428]
text=Chasm of<br>Tears
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 429
[mapelement_429]
text=Tears of<br>Guthix
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 430
[mapelement_430]
text=Lumbridge<br>Castle<br>cellar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 431
[mapelement_431]
text=Giant frogs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 432
[mapelement_432]
text=Hill giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 433
[mapelement_433]
text=Chronozon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 434
[mapelement_434]
text=Here be<br>dead stuff
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 435
[mapelement_435]
text=Thugs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 436
[mapelement_436]
text=Dave's<br>Basement<br>of Doom
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 437
[mapelement_437]
text=Poison spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 438
[mapelement_438]
text=Poison<br>spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 439
[mapelement_439]
text=Zombies
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 440
[mapelement_440]
text=Skeletons<br>& zombies
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 441
[mapelement_441]
text=Earth warriors
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 442
[mapelement_442]
text=Chaos<br>druids
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 443
[mapelement_443]
text=Rats
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 444
[mapelement_444]
text=Here be a<br>big mole
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 445
[mapelement_445]
text=Motherlode Mine
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 446
[mapelement_446]
text=Obstacle<br>course
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 447
[mapelement_447]
text=Skullball
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 448
[mapelement_448]
text=Shades
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 449
[mapelement_449]
text=Here be odd stuff
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 450
[mapelement_450]
text=Nechryael
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 451
[mapelement_451]
text=Abyssal<br>demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 452
[mapelement_452]
text=Bloodvelds
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 453
[mapelement_453]
text=Gargoyles
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 454
[mapelement_454]
text=Aberrant<br>Spectres
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 455
[mapelement_455]
text=Ankou
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 456
[mapelement_456]
text=Cave horrors<br>&<br>albino bats
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 457
[mapelement_457]
text=Altar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 458
[mapelement_458]
text=Lizards &<br>Zamorak fighters
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 459
[mapelement_459]
text=War
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 460
[mapelement_460]
text=Gift of<br>Peace
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 461
[mapelement_461]
text=Famine
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 462
[mapelement_462]
text=Grain of<br>Plenty
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 463
[mapelement_463]
text=Pestilence
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 464
[mapelement_464]
text=Box of<br>Health
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 465
[mapelement_465]
text=Death
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 466
[mapelement_466]
text=Cradle of<br>Life
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 467
[mapelement_467]
text=Cauldron of<br>Thunder
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 468
[mapelement_468]
text=Black Knights'<br>Base
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 469
[mapelement_469]
text=Hellhounds
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 470
[mapelement_470]
text=Fire Obelisk
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 471
[mapelement_471]
text=Black dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 472
[mapelement_472]
text=Black<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 473
[mapelement_473]
text=Dramen Tree
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 474
[mapelement_474]
text=Animated<br>axes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 475
[mapelement_475]
text=Chaos<br>dwarves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 476
[mapelement_476]
text=Blue<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 477
[mapelement_477]
text=Poisonous<br>scorpions
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 478
[mapelement_478]
text=Cyclopes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 479
[mapelement_479]
text=Cyclopes<br>& Axes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 480
[mapelement_480]
text=Ice Queen's<br>Lair
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 481
[mapelement_481]
text=Fountain<br>of Heroes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 482
[mapelement_482]
text=Mountain<br>dwarves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 483
[mapelement_483]
text=Nora T. Hagg's<br>cellar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 484
[mapelement_484]
text=Key Master
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 485
[mapelement_485]
text=Beware of<br>the dog
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 486
[mapelement_486]
text=Anger
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 487
[mapelement_487]
text=Hopelessness
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 488
[mapelement_488]
text=Confusion
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 489
[mapelement_489]
text=Fear
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 490
[mapelement_490]
text=Goutweed<br>store
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 491
[mapelement_491]
text=Troll<br>generals
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 492
[mapelement_492]
text=Burntmeat's<br>Kitchen
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 493
[mapelement_493]
text=Fight Pit
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 494
[mapelement_494]
text=Fight Cave
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 495
[mapelement_495]
text=Sub-level 1
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 496
[mapelement_496]
text=Sub-level 2
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 497
[mapelement_497]
text=Sub-level 3
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 498
[mapelement_498]
text=Sub-level 4
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 499
[mapelement_499]
text=Sub-level 5
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 500
[mapelement_500]
text=Sub-level 6
textsize=1
textcolour=0xffff00
category=category_1129
mapfunction=no

// 501
[mapelement_501]
text=Dagannoth
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 502
[mapelement_502]
text=Giant rock crabs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 503
[mapelement_503]
text=Giant<br>rock crabs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 504
[mapelement_504]
text=Rock lobsters
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 505
[mapelement_505]
text=Rock<br>lobsters
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 506
[mapelement_506]
text=Wallasalki
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 507
[mapelement_507]
text=Dagannoth Kings
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 508
[mapelement_508]
text=Shadow<br>spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 509
[mapelement_509]
text=Agility<br>course<br>spikes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 510
[mapelement_510]
text=Mage Arena<br>bank
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 511
[mapelement_511]
text=King<br>Black<br>Dragon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 512
[mapelement_512]
text=Corporeal<br>Beast
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 513
[mapelement_513]
text=Salarin the<br>Twisted
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 514
[mapelement_514]
text=Smoke devils
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 515
[mapelement_515]
text=Thermonuclear<br>Smoke Devil
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 516
[mapelement_516]
text=Throne room
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 517
[mapelement_517]
text=Beware of the<br>mushrooms
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 518
[mapelement_518]
text=Shrine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 519
[mapelement_519]
text=Otherworldly<br>beings
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 520
[mapelement_520]
text=Puro-puro
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 521
[mapelement_521]
text=Tanglefeet
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 522
[mapelement_522]
text=Brimstail
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 523
[mapelement_523]
text=Voice of Yama
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 524
[mapelement_524]
text=Ents
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 525
[mapelement_525]
text=Brutal black, blue<br>& red dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 526
[mapelement_526]
text=Bronze & iron<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 527
[mapelement_527]
text=Steel<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 528
[mapelement_528]
text=Dark<br>beasts
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 529
[mapelement_529]
text=Ghosts
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 530
[mapelement_530]
text=Dust devils
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 531
[mapelement_531]
text=Sand<br>crabs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 532
[mapelement_532]
text=Spectres
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 533
[mapelement_533]
text=Banshees
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 534
[mapelement_534]
text=Mor Ul Rek
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 535
[mapelement_535]
text=The Inferno
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 536
[mapelement_536]
text=Lizardman<br>Caves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 537
[mapelement_537]
text=Underwater
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 538
[mapelement_538]
text=Wyverns
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 539
[mapelement_539]
text=Wyverns<br>Task Only
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 540
[mapelement_540]
text=Volcano Mine
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 541
[mapelement_541]
text=A
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no
show=both

// 542
[mapelement_542]
text=B
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no
show=both

// 543
[mapelement_543]
text=C
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no
show=both

// 544
[mapelement_544]
text=Fossil<br>Island
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 545
[mapelement_545]
text=Museum<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 546
[mapelement_546]
text=The Warrens
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 547
[mapelement_547]
text=Mushroom<br>Forest
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 548
[mapelement_548]
text=House<br>on the<br>Hill
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 549
[mapelement_549]
text=Volcano
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 550
[mapelement_550]
text=Tar<br>Swamp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 551
[mapelement_551]
text=Crabclaw Caves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 552
[mapelement_552]
text=Wilderness<br>Emblem Trader
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 553
[mapelement_553]
text=Ice giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 554
[mapelement_554]
text=Greater<br>demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 555
[mapelement_555]
text=Green dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 556
[mapelement_556]
text=Green<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 557
[mapelement_557]
text=Revenants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 558
[mapelement_558]
text=Myths'<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 559
[mapelement_559]
text=Corsair<br>Cove
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 560
[mapelement_560]
text=Ancient<br>Forge
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 561
[mapelement_561]
text=Ogresses
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 562
[mapelement_562]
text=Chinchompas
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 563
[mapelement_563]
text=Dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 564
[mapelement_564]
text=Baby dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 565
[mapelement_565]
text=Chapel
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 566
[mapelement_566]
text=Ungael
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 567
[mapelement_567]
text=Lithkren
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 568
[mapelement_568]
text=War Tent
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 569
[mapelement_569]
text=Foodhall
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 570
[mapelement_570]
text=Kourend<br>Castle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 571
[mapelement_571]
text=Kebos<br>Lowlands
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 572
[mapelement_572]
text=Paterdomus<br>Temple
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 573
[mapelement_573]
text=Darkmeyer
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 574
[mapelement_574]
text=Slepe
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 575
[mapelement_575]
text=Ver Sinhaza
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 576
[mapelement_576]
category=category_1251
sprite="mapfunction,89"
mapfunction=yes
show=both

// 577
[mapelement_577]
category=category_1252
sprite="mapfunction,90"
mapfunction=yes
show=both

// 578
[mapelement_578]
category=category_1253
sprite="mapfunction,91"
mapfunction=yes
show=both

// 579
[mapelement_579]
category=category_1254
sprite="mapfunction,92"
mapfunction=yes
show=both

// 580
[mapelement_580]
category=category_1255
sprite="mapfunction,93"
mapfunction=yes
show=both

// 581
[mapelement_581]
category=category_1256
sprite="mapfunction,94"
mapfunction=yes
show=both

// 582
[mapelement_582]
category=category_1257
sprite="mapfunction,95"
mapfunction=yes
show=both

// 583
[mapelement_583]
category=category_1258
sprite="mapfunction,96"
mapfunction=yes
show=both

// 584
[mapelement_584]
category=category_1259
sprite="mapfunction,97"
mapfunction=yes
show=both

// 585
[mapelement_585]
category=category_1260
sprite="mapfunction,98"
mapfunction=yes
show=both

// 586
[mapelement_586]
category=category_1261
sprite="mapfunction,99"
mapfunction=yes
show=both

// 587
[mapelement_587]
category=category_1262
sprite="mapfunction,100"
mapfunction=yes
show=both

// 588
[mapelement_588]
category=category_1263
sprite="mapfunction,101"
mapfunction=yes
show=both

// 589
[mapelement_589]
category=category_1264
sprite="mapfunction,103"
mapfunction=yes
show=both

// 590
[mapelement_590]
category=category_1265
sprite="mapfunction,115"
mapfunction=yes
show=both

// 591
[mapelement_591]
category=category_1266
sprite="mapfunction,106"
mapfunction=yes
show=both

// 592
[mapelement_592]
category=category_1267
sprite="mapfunction,107"
mapfunction=yes
show=both

// 593
[mapelement_593]
category=category_1268
sprite="mapfunction,108"
mapfunction=yes
show=both

// 594
[mapelement_594]
category=category_1269
sprite="mapfunction,110"
mapfunction=yes
show=both

// 595
[mapelement_595]
category=category_1270
sprite="mapfunction,111"
mapfunction=yes
show=both

// 596
[mapelement_596]
category=category_1271
sprite="mapfunction,112"
mapfunction=yes
show=both

// 597
[mapelement_597]
category=category_1272
sprite="mapfunction,113"
mapfunction=yes
show=both

// 598
[mapelement_598]
category=category_1273
sprite="mapfunction,114"
mapfunction=yes
show=both

// 599
[mapelement_599]
category=category_1274
sprite="mapfunction,116"
mapfunction=yes
show=both

// 600
[mapelement_600]
category=category_1275
sprite="mapfunction,117"
mapfunction=yes
show=both

// 601
[mapelement_601]
text=Kalphite<br>Cave
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 602
[mapelement_602]
text=Lovakengj<br>Assembly
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 603
[mapelement_603]
text=The Forsaken<br>Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 604
[mapelement_604]
text=Mount<br>Karuulm
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 605
[mapelement_605]
text=Farming Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 606
[mapelement_606]
text=Battlefront
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 607
[mapelement_607]
text=Molch
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 608
[mapelement_608]
text=Kebos Swamp
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 609
[mapelement_609]
text=Lake Molch
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 610
[mapelement_610]
text=River Molch
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 611
[mapelement_611]
text=Wyrms
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 612
[mapelement_612]
text=Drakes
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 613
[mapelement_613]
text=Hydras
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 614
[mapelement_614]
text=Alchemical<br>Hydra
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 615
[mapelement_615]
text=Sulphur<br>lizards
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 616
[mapelement_616]
text=Tasakaal
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 617
[mapelement_617]
text=Hespori
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 618
[mapelement_618]
text=Lizardman<br>Temple
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 619
[mapelement_619]
category=category_1317
sprite="mapfunction,118"
mapfunction=yes
show=both

// 620
[mapelement_620]
text=Forthos Ruin
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 621
[mapelement_621]
text=Kingstown
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 622
[mapelement_622]
text=Wine of<br>Zamorak
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 623
[mapelement_623]
text=Larran's<br>Chest
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 624
[mapelement_624]
text=River<br>Dougne
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 625
[mapelement_625]
text=River<br>Hos
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 626
[mapelement_626]
text=Undead<br>druids
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 627
[mapelement_627]
text=Bone<br>Burner
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 628
[mapelement_628]
text=Temple Spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 629
[mapelement_629]
text=Sarachnis
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 630
[mapelement_630]
category=category_1070
sprite="mapfunction,109"
mapfunction=yes
show=both

// 631
[mapelement_631]
category=category_1396
sprite="mapfunction,119"
mapfunction=yes
show=both

// 632
[mapelement_632]
text=Moss<br>giants
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 633
[mapelement_633]
text=Trahaearn<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 634
[mapelement_634]
text=Zalcano
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 635
[mapelement_635]
text=The Gauntlet
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 636
[mapelement_636]
text=Gwenith
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 637
[mapelement_637]
text=Last Man<br>Standing
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 638
[mapelement_638]
text=The Mountain
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 639
[mapelement_639]
text=Trinity<br>Outpost
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 640
[mapelement_640]
text=Debtor<br>Hideout
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 641
[mapelement_641]
text=Moser<br>Settlement
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 642
[mapelement_642]
text=Rocky<br>Outcrop
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 643
[mapelement_643]
text=Island<br>of Stone
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 644
[mapelement_644]
text=Basilisk<br>Knights
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 645
[mapelement_645]
category=category_176
sprite="mapfunction,123"
mapfunction=yes
show=both

// 646
[mapelement_646]
text=Lesser<br>demons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 647
[mapelement_647]
text=The<br>Nightmare
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 648
[mapelement_648]
text=Shura
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 649
[mapelement_649]
text=Elves
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 650
[mapelement_650]
category=category_1425
sprite="mapfunction,124"
mapfunction=yes
show=both

// 651
[mapelement_651]
text=Icyene<br>Graveyard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 652
[mapelement_652]
category=category_1459
sprite="mapfunction,125"
mapfunction=yes
show=both

// 653
[mapelement_653]
text=Crypt
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 654
[mapelement_654]
text=Ferox<br>Enclave
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 655
[mapelement_655]
text=Citharede<br>Abbey
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 656
[mapelement_656]
text=South Falador<br>Farm
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 657
[mapelement_657]
text=Sourhog Cave
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 658
[mapelement_658]
text=Isle of Souls
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 659
[mapelement_659]
text=Soul Wars<br>Arena
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 660
[mapelement_660]
text=Soul Wars<br>Lobby
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 661
[mapelement_661]
text=Soul<br>Obelisk
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 662
[mapelement_662]
text=Western<br>Graveyard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 663
[mapelement_663]
text=Eastern<br>Graveyard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 664
[mapelement_664]
text=Blue<br>Base
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 665
[mapelement_665]
text=Red<br>Base
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 666
[mapelement_666]
text=Avatar of<br>Creation
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 667
[mapelement_667]
text=Avatar of<br>Destruction
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 668
[mapelement_668]
text=Iron<br>dragons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 669
[mapelement_669]
text=Desert Island
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 670
[mapelement_670]
text=Wild Varrock
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 671
[mapelement_671]
text=Hut
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 672
[mapelement_672]
text=Stone Circle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 673
[mapelement_673]
text=Court of Chaos
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 674
[mapelement_674]
text=Old Manor
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 675
[mapelement_675]
text=Town Center
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 676
[mapelement_676]
text=Blank Tower
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 677
[mapelement_677]
text=Trading Post
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 678
[mapelement_678]
text=Dark Warrior's<br>Palace
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 679
[mapelement_679]
text=Pillars of Sacrifice
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 680
[mapelement_680]
category=category_1499
sprite="mapfunction,126"
mapfunction=yes
show=both

// 681
[mapelement_681]
text=Ruins of<br>Unkah
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 682
[mapelement_682]
text=Sea Spirit<br>Dock
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 683
[mapelement_683]
text=Tempoross<br>Cove
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 684
[mapelement_684]
text=Camdozaal<br>Vault
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 685
[mapelement_685]
text=Ramarno
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 686
[mapelement_686]
text=Offering<br>Altar
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 687
[mapelement_687]
text=Golem<br>Workshop
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 688
[mapelement_688]
text=Camdozaal<br>Mines
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 689
[mapelement_689]
text=Ancient<br>Vault
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 690
[mapelement_690]
category=category_1551
sprite="mapfunction,127"
mapfunction=yes
show=both

// 691
[mapelement_691]
text=Shayzien<br>Encampment
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 692
[mapelement_692]
text=Giant<br>Pit
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 693
[mapelement_693]
text=Ruins<br>of Morra
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 694
[mapelement_694]
text=Shayzia<br>Ruin
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 695
[mapelement_695]
text=Northern<br>Tundras
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 696
[mapelement_696]
text=River<br>of Souls
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 697
[mapelement_697]
category=category_1579
sprite="mapfunction,128"
mapfunction=yes
show=both

// 698
[mapelement_698]
text=Sire
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 699
[mapelement_699]
text=Here be<br>spiders
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 700
[mapelement_700]
text=Sangvesti
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 701
[mapelement_701]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 702
[mapelement_702]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 703
[mapelement_703]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 704
[mapelement_704]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 705
[mapelement_705]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 706
[mapelement_706]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 707
[mapelement_707]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 708
[mapelement_708]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 709
[mapelement_709]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 710
[mapelement_710]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 711
[mapelement_711]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 712
[mapelement_712]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 713
[mapelement_713]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 714
[mapelement_714]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 715
[mapelement_715]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 716
[mapelement_716]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 717
[mapelement_717]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 718
[mapelement_718]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 719
[mapelement_719]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 720
[mapelement_720]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 721
[mapelement_721]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 722
[mapelement_722]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 723
[mapelement_723]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 724
[mapelement_724]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 725
[mapelement_725]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 726
[mapelement_726]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 727
[mapelement_727]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 728
[mapelement_728]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 729
[mapelement_729]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 730
[mapelement_730]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 731
[mapelement_731]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 732
[mapelement_732]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 733
[mapelement_733]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 734
[mapelement_734]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 735
[mapelement_735]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 736
[mapelement_736]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 737
[mapelement_737]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 738
[mapelement_738]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 739
[mapelement_739]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 740
[mapelement_740]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 741
[mapelement_741]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 742
[mapelement_742]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 743
[mapelement_743]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 744
[mapelement_744]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 745
[mapelement_745]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 746
[mapelement_746]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 747
[mapelement_747]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 748
[mapelement_748]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 749
[mapelement_749]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 750
[mapelement_750]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 751
[mapelement_751]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 752
[mapelement_752]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 753
[mapelement_753]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 754
[mapelement_754]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 755
[mapelement_755]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 756
[mapelement_756]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 757
[mapelement_757]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 758
[mapelement_758]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 759
[mapelement_759]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 760
[mapelement_760]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 761
[mapelement_761]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 762
[mapelement_762]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 763
[mapelement_763]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 764
[mapelement_764]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 765
[mapelement_765]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 766
[mapelement_766]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 767
[mapelement_767]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 768
[mapelement_768]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 769
[mapelement_769]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 770
[mapelement_770]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 771
[mapelement_771]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 772
[mapelement_772]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 773
[mapelement_773]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 774
[mapelement_774]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 775
[mapelement_775]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 776
[mapelement_776]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 777
[mapelement_777]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 778
[mapelement_778]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 779
[mapelement_779]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 780
[mapelement_780]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 781
[mapelement_781]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 782
[mapelement_782]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 783
[mapelement_783]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 784
[mapelement_784]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 785
[mapelement_785]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 786
[mapelement_786]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 787
[mapelement_787]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 788
[mapelement_788]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 789
[mapelement_789]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 790
[mapelement_790]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 791
[mapelement_791]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 792
[mapelement_792]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 793
[mapelement_793]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 794
[mapelement_794]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 795
[mapelement_795]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 796
[mapelement_796]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 797
[mapelement_797]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 798
[mapelement_798]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 799
[mapelement_799]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 800
[mapelement_800]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 801
[mapelement_801]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 802
[mapelement_802]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 803
[mapelement_803]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 804
[mapelement_804]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 805
[mapelement_805]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 806
[mapelement_806]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 807
[mapelement_807]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 808
[mapelement_808]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 809
[mapelement_809]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 810
[mapelement_810]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 811
[mapelement_811]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 812
[mapelement_812]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 813
[mapelement_813]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 814
[mapelement_814]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 815
[mapelement_815]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 816
[mapelement_816]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 817
[mapelement_817]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 818
[mapelement_818]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 819
[mapelement_819]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 820
[mapelement_820]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 821
[mapelement_821]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 822
[mapelement_822]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 823
[mapelement_823]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 824
[mapelement_824]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 825
[mapelement_825]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 826
[mapelement_826]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 827
[mapelement_827]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 828
[mapelement_828]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 829
[mapelement_829]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 830
[mapelement_830]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 831
[mapelement_831]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 832
[mapelement_832]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 833
[mapelement_833]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 834
[mapelement_834]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 835
[mapelement_835]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 836
[mapelement_836]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 837
[mapelement_837]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 838
[mapelement_838]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 839
[mapelement_839]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 840
[mapelement_840]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 841
[mapelement_841]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 842
[mapelement_842]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 843
[mapelement_843]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 844
[mapelement_844]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 845
[mapelement_845]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 846
[mapelement_846]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 847
[mapelement_847]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 848
[mapelement_848]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 849
[mapelement_849]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 850
[mapelement_850]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 851
[mapelement_851]
text=Ancient<br>Prison
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 852
[mapelement_852]
text=Greater<br>nechryael
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 853
[mapelement_853]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 854
[mapelement_854]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 855
[mapelement_855]
text=Ruins of<br>Ullek
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 856
[mapelement_856]
text=Necropolis
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 857
[mapelement_857]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 858
[mapelement_858]
category=category_1641
sprite="mapfunction,129"
mapfunction=yes
show=both

// 859
[mapelement_859]
category=category_1642
sprite="mapfunction,130"
mapfunction=yes
show=both

// 860
[mapelement_860]
category=category_1643
sprite="mapfunction,131"
mapfunction=yes
show=both

// 861
[mapelement_861]
text=Kovac
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 862
[mapelement_862]
text=Giants'<br>Plateau
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 863
[mapelement_863]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 864
[mapelement_864]
text=Emir's<br>Arena
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 865
[mapelement_865]
text=Kalphite<br>Lair
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 866
[mapelement_866]
text=Kalphite<br>Cave
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 867
[mapelement_867]
text=Trouble<br>Brewing
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 868
[mapelement_868]
text=Piscatoris
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 869
[mapelement_869]
text=Troll<br>Country
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 870
[mapelement_870]
text=Uzer<br>Oasis
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 871
[mapelement_871]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 872
[mapelement_872]
text=Skeleton
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 873
[mapelement_873]
text=Callisto's<br>Den
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 874
[mapelement_874]
text=Silk<br>Chasm
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 875
[mapelement_875]
text=Vet'ion's<br>Rest
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 876
[mapelement_876]
text=Hunter's<br>End
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 877
[mapelement_877]
text=Web<br>Chasm
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 878
[mapelement_878]
text=Skeletal<br>Tomb
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 879
[mapelement_879]
text=Jaldraocht<br>Pyramid
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 880
[mapelement_880]
text=Jalsavrah<br>Pyramid
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 881
[mapelement_881]
text=Jaltevas<br>Pyramid
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 882
[mapelement_882]
text=Daimon's<br>Crater
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 883
[mapelement_883]
text=Frozen Temple
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 884
[mapelement_884]
text=Huntsman's<br>Wood
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 885
[mapelement_885]
text=Tower of<br>Bounty
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 886
[mapelement_886]
text=Bounty<br>Hunter
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 887
[mapelement_887]
category=category_1790
sprite="mapfunction,133"
mapfunction=yes
show=both

// 888
[mapelement_888]
text=The<br>Stranglewood
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 889
[mapelement_889]
text=Temple
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 890
[mapelement_890]
text=Ritual<br>Site
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 891
[mapelement_891]
text=Main<br>Block
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 892
[mapelement_892]
text=Administration
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 893
[mapelement_893]
text=Refugee<br>Camp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 894
[mapelement_894]
text=Science<br>District
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 895
[mapelement_895]
text=Residential<br>District
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 896
[mapelement_896]
text=Sunken<br>Cathedral
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 897
[mapelement_897]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 898
[mapelement_898]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 899
[mapelement_899]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 900
[mapelement_900]
text=Party Room
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 901
[mapelement_901]
category=category_2002
sprite="mapfunction,134"
mapfunction=yes
show=both

// 902
[mapelement_902]
text=Kingdom of<br>Varlamore
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 903
[mapelement_903]
text=Civitas illa<br>Fortis
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 904
[mapelement_904]
text=Avium<br>Savannah
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 905
[mapelement_905]
text=Ralos'<br>Rise
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 906
[mapelement_906]
text=Sunset<br>Coast
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 907
[mapelement_907]
text=Fortis<br>Colosseum
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 908
[mapelement_908]
text=Fortis<br>Cothon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 909
[mapelement_909]
text=Bazaar
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 910
[mapelement_910]
text=Sunrise<br>Palace
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 911
[mapelement_911]
text=Grand<br>Museum
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 912
[mapelement_912]
text=Kualti<br>Headquarters
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 913
[mapelement_913]
text=Outer Fortis
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 914
[mapelement_914]
text=Fortis Aqueduct
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 915
[mapelement_915]
text=Ortus<br>Farm
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 916
[mapelement_916]
text=The<br>Teomat
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 917
[mapelement_917]
text=Cam Torum<br>Entrance
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 918
[mapelement_918]
text=Hunter<br>Guild
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 919
[mapelement_919]
text=Locus<br>Oasis
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 920
[mapelement_920]
text=Stonecutter<br>Outpost
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 921
[mapelement_921]
text=Colossal Wyrm<br>Remains
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 922
[mapelement_922]
text=River<br>Varla
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 923
[mapelement_923]
text=River Ortus
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 924
[mapelement_924]
text=Barracks
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 925
[mapelement_925]
text=Cam Torum
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 926
[mapelement_926]
text=City<br>Entrance
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 927
[mapelement_927]
text=Neypotzli<br>Entrance
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 928
[mapelement_928]
text=The<br>Blood Moon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 929
[mapelement_929]
text=The<br>Blue Moon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 930
[mapelement_930]
text=The<br>Eclipse Moon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 931
[mapelement_931]
text=Earthbound<br>Cavern
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 932
[mapelement_932]
text=Streambound<br>Cavern
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 933
[mapelement_933]
text=Antechamber
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 934
[mapelement_934]
text=Ancient<br>Prison
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 935
[mapelement_935]
text=Ancient<br>Shrine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 936
[mapelement_936]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 937
[mapelement_937]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 938
[mapelement_938]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 939
[mapelement_939]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 940
[mapelement_940]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 941
[mapelement_941]
text=Araxxor
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 942
[mapelement_942]
text=Aldarin
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 943
[mapelement_943]
text=Mistrock
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 944
[mapelement_944]
text=Quetzacalli<br>Gorge
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 945
[mapelement_945]
text=The<br>Proudspire
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 946
[mapelement_946]
text=The<br>Darkfrost
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 947
[mapelement_947]
text=Mons<br>Gratia
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 948
[mapelement_948]
text=Salvager<br>Overlook
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 949
[mapelement_949]
text=Moonrise Brewery<br>and Winery
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 950
[mapelement_950]
text=Twilight<br>Temple
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 951
[mapelement_951]
text=Tower of<br>Ascension
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 952
[mapelement_952]
text=Shipwreck<br>Cove
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 953
[mapelement_953]
text=Darkmoon<br>Ravine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 954
[mapelement_954]
text=Villa<br>Lucens
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 955
[mapelement_955]
text=Alchemical<br>Society
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 956
[mapelement_956]
text=Wolf<br>Den
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 957
[mapelement_957]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 958
[mapelement_958]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 959
[mapelement_959]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 960
[mapelement_960]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 961
[mapelement_961]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 962
[mapelement_962]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 963
[mapelement_963]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 964
[mapelement_964]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 965
[mapelement_965]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 966
[mapelement_966]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 967
[mapelement_967]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 968
[mapelement_968]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 969
[mapelement_969]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 970
[mapelement_970]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 971
[mapelement_971]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 972
[mapelement_972]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 973
[mapelement_973]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 974
[mapelement_974]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 975
[mapelement_975]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 976
[mapelement_976]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 977
[mapelement_977]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 978
[mapelement_978]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 979
[mapelement_979]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 980
[mapelement_980]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 981
[mapelement_981]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 982
[mapelement_982]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 983
[mapelement_983]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 984
[mapelement_984]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 985
[mapelement_985]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 986
[mapelement_986]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 987
[mapelement_987]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 988
[mapelement_988]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 989
[mapelement_989]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 990
[mapelement_990]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 991
[mapelement_991]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 992
[mapelement_992]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 993
[mapelement_993]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 994
[mapelement_994]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 995
[mapelement_995]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 996
[mapelement_996]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 997
[mapelement_997]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 998
[mapelement_998]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 999
[mapelement_999]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1000
[mapelement_1000]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1001
[mapelement_1001]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1002
[mapelement_1002]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1003
[mapelement_1003]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1004
[mapelement_1004]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1005
[mapelement_1005]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1006
[mapelement_1006]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1007
[mapelement_1007]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1008
[mapelement_1008]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1009
[mapelement_1009]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1010
[mapelement_1010]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1011
[mapelement_1011]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1012
[mapelement_1012]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1013
[mapelement_1013]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1014
[mapelement_1014]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1015
[mapelement_1015]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1016
[mapelement_1016]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1017
[mapelement_1017]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1018
[mapelement_1018]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1019
[mapelement_1019]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1020
[mapelement_1020]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1021
[mapelement_1021]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1022
[mapelement_1022]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1023
[mapelement_1023]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1024
[mapelement_1024]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1025
[mapelement_1025]
category=category_1104
sprite="mapfunction,56"
mapfunction=yes
show=both

// 1026
[mapelement_1026]
text=Yama
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1027
[mapelement_1027]
text=Highlord's<br>Chamber
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1028
[mapelement_1028]
text=Stalker<br>Den
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1029
[mapelement_1029]
text=Dragon<br>Nest
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1030
[mapelement_1030]
text=Tempestus
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1031
[mapelement_1031]
text=Tal Teklan
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1032
[mapelement_1032]
text=Kastori
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1033
[mapelement_1033]
text=Tlati<br>Rainforest
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1034
[mapelement_1034]
text=Auburnvale
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1035
[mapelement_1035]
text=Auburn<br>Valley
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1036
[mapelement_1036]
text=Custodia<br>Mountains
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1037
[mapelement_1037]
text=Custodia<br>Pass
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1038
[mapelement_1038]
text=Crypt of<br>Tonali
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1039
[mapelement_1039]
text=Gloomthorn<br>Trail
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1040
[mapelement_1040]
text=Nemus<br>Retreat
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1041
[mapelement_1041]
text=Tal Teok
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1042
[mapelement_1042]
category=category_2261
sprite="mapfunction,136"
mapfunction=yes
show=both

// 1043
[mapelement_1043]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1044
[mapelement_1044]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1045
[mapelement_1045]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1046
[mapelement_1046]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1047
[mapelement_1047]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1048
[mapelement_1048]
category=category_2386
sprite="mapfunction,137"
mapfunction=yes
show=both

// 1049
[mapelement_1049]
category=category_2387
sprite="mapfunction,138"
mapfunction=no
show=both

// 1050
[mapelement_1050]
category=category_2388
sprite="mapfunction,139"
mapfunction=no
show=both

// 1051
[mapelement_1051]
category=category_2389
sprite="mapfunction,140"
mapfunction=no
show=both

// 1052
[mapelement_1052]
category=category_2390
sprite="mapfunction,141"
mapfunction=no
show=both

// 1053
[mapelement_1053]
category=category_2391
sprite="mapfunction,142"
mapfunction=no
show=both

// 1054
[mapelement_1054]
category=category_2392
sprite="mapfunction,143"
mapfunction=no
show=both

// 1055
[mapelement_1055]
category=category_2393
sprite="mapfunction,144"
mapfunction=no
show=both

// 1056
[mapelement_1056]
category=category_2394
sprite="mapfunction,145"
mapfunction=no
show=both

// 1057
[mapelement_1057]
text=Yanille<br>Chain
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1058
[mapelement_1058]
text=River<br>Shilo
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1059
[mapelement_1059]
text=River<br>Amja
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1060
[mapelement_1060]
text=Musa<br>Passage
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1061
[mapelement_1061]
text=Lum<br>Lagoon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1062
[mapelement_1062]
text=Elid<br>Delta
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1063
[mapelement_1063]
text=Alloviz<br>Estuary
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1064
[mapelement_1064]
text=Pyre<br>Cove
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1065
[mapelement_1065]
text=Blighted<br>Volcano
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1066
[mapelement_1066]
text=Dvergfjord
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1067
[mapelement_1067]
text=Rower's<br>Arm
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1068
[mapelement_1068]
text=Vesmjos
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1069
[mapelement_1069]
text=Seers'<br>Eye
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1070
[mapelement_1070]
text=Merwick<br>Lake
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1071
[mapelement_1071]
text=Lake<br>Hemenster
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1072
[mapelement_1072]
text=River<br>Crannmor
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1073
[mapelement_1073]
text=Mynydd
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1074
[mapelement_1074]
text=Afon<br>Ganol
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1075
[mapelement_1075]
text=The<br>Dibber
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1076
[mapelement_1076]
text=The White<br>Cliffs of Lova
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1077
[mapelement_1077]
text=Talon's<br>Grasp
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1078
[mapelement_1078]
text=Karamja<br>Volcano
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1079
[mapelement_1079]
text=Cape<br>Atoll
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1080
[mapelement_1080]
text=Chompy<br>Marsh
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1081
[mapelement_1081]
text=Gorlah
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1082
[mapelement_1082]
text=Kraken<br>Cove
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1083
[mapelement_1083]
text=Cursed<br>Archipelago
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 1084
[mapelement_1084]
text=The<br>Pandemonium
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1085
[mapelement_1085]
text=The Great<br>Conch
textsize=2
textcolour=0xff981f
category=category_1129
mapfunction=no

// 1086
[mapelement_1086]
text=The Summer<br>Shore
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1087
[mapelement_1087]
text=The Sacred<br>Grove
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1088
[mapelement_1088]
text=Abalone<br>Cliffs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1089
[mapelement_1089]
text=Cape<br>Conch
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1090
[mapelement_1090]
text=Gryphons
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1091
[mapelement_1091]
text=Shellbane <br>Gryphon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1092
[mapelement_1092]
text=Coral<br>Nurseries
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1093
[mapelement_1093]
text=Charred<br>Dungeon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1094
[mapelement_1094]
text=The<br>Pandemonium
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1095
[mapelement_1095]
text=Grimstone<br>Dungeon
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1096
[mapelement_1096]
text=Kurask<br>Lair
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1097
[mapelement_1097]
text=Deepfin<br>Mine
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1098
[mapelement_1098]
text=Sunbleak<br>Cave
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1099
[mapelement_1099]
text=Here be<br>minotaurs
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1100
[mapelement_1100]
text=Ynysdail<br>Cavern
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1101
[mapelement_1101]
text=Buccaneers'<br>Laboratory
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1102
[mapelement_1102]
text=Ardent<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1103
[mapelement_1103]
text=Unquiet<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1104
[mapelement_1104]
text=Shrouded<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1105
[mapelement_1105]
text=Western<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1106
[mapelement_1106]
text=Northern<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1107
[mapelement_1107]
text=Sunset<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1108
[mapelement_1108]
text=Forgotten<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1109
[mapelement_1109]
text=Untamed<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1110
[mapelement_1110]
text=Eastern<br>Ocean
textsize=2
textcolour=0x1de0e0
category=category_1129
mapfunction=no

// 1111
[mapelement_1111]
text=Bay of<br>Sarim
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1112
[mapelement_1112]
text=Kharidian<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1113
[mapelement_1113]
text=Lumbridge<br>Basin
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1114
[mapelement_1114]
text=Mudskipper<br>Sound
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1115
[mapelement_1115]
text=Rimmington<br>Strait
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1116
[mapelement_1116]
text=Catherby<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1117
[mapelement_1117]
text=Brimhaven<br>Passage
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1118
[mapelement_1118]
text=Strait of<br>Khazard
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1119
[mapelement_1119]
text=Gu'tanoth<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1120
[mapelement_1120]
text=Feldip<br>Gulf
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1121
[mapelement_1121]
text=Kharazi<br>Strait
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1122
[mapelement_1122]
text=Oo'glog<br>Channel
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1123
[mapelement_1123]
text=Arrow<br>Passage
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1124
[mapelement_1124]
text=Menaphite<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1125
[mapelement_1125]
text=The Simian<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1126
[mapelement_1126]
text=The Storm<br>Tempor
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1127
[mapelement_1127]
text=Turtle<br>Belt
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1128
[mapelement_1128]
text=Sea of<br>Shells
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1129
[mapelement_1129]
text=Red<br>Reef
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1130
[mapelement_1130]
text=Anglerfish's<br>Light
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1131
[mapelement_1131]
text=Bay of<br>Elidinis
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1132
[mapelement_1132]
text=Tortugan<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1133
[mapelement_1133]
text=Pearl<br>Bank
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1134
[mapelement_1134]
text=The Lonely<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1135
[mapelement_1135]
text=Fortis<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1136
[mapelement_1136]
text=Aureum<br>Coast
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1137
[mapelement_1137]
text=Wyrm's<br>Waters
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1138
[mapelement_1138]
text=Mythic<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1139
[mapelement_1139]
text=Breakbone<br>Strait
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1140
[mapelement_1140]
text=Backwater
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1141
[mapelement_1141]
text=Zul-Egil
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1142
[mapelement_1142]
text=The<br>Skullhorde
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1143
[mapelement_1143]
text=Sea of<br>Souls
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1144
[mapelement_1144]
text=Soul<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1145
[mapelement_1145]
text=Barracuda<br>Belt
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1146
[mapelement_1146]
text=The<br>Everdeep
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1147
[mapelement_1147]
text=Sapphire<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1148
[mapelement_1148]
text=Western<br>Gate
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1149
[mapelement_1149]
text=Rainbow<br>Reef
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1150
[mapelement_1150]
text=Southern<br>Expanse
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1151
[mapelement_1151]
text=Sunset<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1152
[mapelement_1152]
text=Misty<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1153
[mapelement_1153]
text=Dusk's<br>Maw
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1154
[mapelement_1154]
text=Aehecatl
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1155
[mapelement_1155]
text=Aestuarium<br>Tempestus
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1156
[mapelement_1156]
text=Calidum<br>Reach
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1157
[mapelement_1157]
text=Ochre<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1158
[mapelement_1158]
text=Horizon's<br>End
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1159
[mapelement_1159]
text=Great<br>Sound
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1160
[mapelement_1160]
text=Crabclaw<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1161
[mapelement_1161]
text=Gulf of<br>Kourend
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1162
[mapelement_1162]
text=Hosidian<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1163
[mapelement_1163]
text=Pilgrims'<br>Passage
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1164
[mapelement_1164]
text=Litus<br>Lucis
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1165
[mapelement_1165]
text=Porth<br>Neigwl
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1166
[mapelement_1166]
text=Tirannwn<br>Bight
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1167
[mapelement_1167]
text=Crystal<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1168
[mapelement_1168]
text=Porth<br>Gwenith
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1169
[mapelement_1169]
text=Piscatoris<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1170
[mapelement_1170]
text=Vagabonds<br>Rest
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1171
[mapelement_1171]
text=Moonshadow
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1172
[mapelement_1172]
text=Fremensund
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1173
[mapelement_1173]
text=Grandroot<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1174
[mapelement_1174]
text=V's<br>Belt
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1175
[mapelement_1175]
text=Fremennik<br>Strait
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1176
[mapelement_1176]
text=Idestia<br>Strait
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1177
[mapelement_1177]
text=Lunar<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1178
[mapelement_1178]
text=Winter's<br>Edge
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1179
[mapelement_1179]
text=Lunar<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1180
[mapelement_1180]
text=Everwinter<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1181
[mapelement_1181]
text=Kannski<br>Tides
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1182
[mapelement_1182]
text=Weissmere
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1183
[mapelement_1183]
text=Stoneheart<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1184
[mapelement_1184]
text=Shiverwake<br>Expanse
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1185
[mapelement_1185]
text=Weiss<br>Melt
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1186
[mapelement_1186]
text=Uzer<br>Channel
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1187
[mapelement_1187]
text=Scabaras'<br>Shallows
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1188
[mapelement_1188]
text=Sanctuary's<br>End
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1189
[mapelement_1189]
text=The Iron<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1190
[mapelement_1190]
text=Strait of<br>Discord
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1191
[mapelement_1191]
text=Murkshore<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1192
[mapelement_1192]
text=Mos<br>Le'Water
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1193
[mapelement_1193]
text=Eastern<br>Ridge
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1194
[mapelement_1194]
text=Tainted<br>Tides
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1195
[mapelement_1195]
text=Shrieking<br>Waters
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1196
[mapelement_1196]
text=Forbidden<br>Depths
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1197
[mapelement_1197]
text=The Accursed<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1198
[mapelement_1198]
text=Gravewater<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1199
[mapelement_1199]
text=Sotfa<br>Forest
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1200
[mapelement_1200]
text=Hallowed<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1201
[mapelement_1201]
text=Dragon's<br>Maw
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1202
[mapelement_1202]
text=Haunted<br>Coast
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1203
[mapelement_1203]
text=Bleakwater<br>Bay
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1204
[mapelement_1204]
text=Echoing<br>Rift
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1205
[mapelement_1205]
text=The Searing<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1206
[mapelement_1206]
text=Wyvern's<br>Wake
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1207
[mapelement_1207]
text=Fiend's<br>Passage
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1208
[mapelement_1208]
text=The<br>Precipice
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1209
[mapelement_1209]
text=The<br>Cinderwaters
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1210
[mapelement_1210]
text=Ancient<br>Reef
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1211
[mapelement_1211]
text=The Eastern<br>Doldrums
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1212
[mapelement_1212]
text=Last<br>Gasp
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1213
[mapelement_1213]
text=Grieving<br>Bight
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1214
[mapelement_1214]
text=Kebos<br>Shore
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1215
[mapelement_1215]
text=Sulphur<br>Cove
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1216
[mapelement_1216]
text=Frostgrave<br>Depths
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1217
[mapelement_1217]
text=Lovkengj's<br>Shroud
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1218
[mapelement_1218]
text=Dagger's<br>Edge
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1219
[mapelement_1219]
text=The Endless<br>Sea
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1220
[mapelement_1220]
text=Rock Island<br>Prison
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1221
[mapelement_1221]
text=Fort<br>Locke
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1222
[mapelement_1222]
text=Dognose<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1223
[mapelement_1223]
text=The Little<br>Pearl
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1224
[mapelement_1224]
text=The Onyx<br>Crest
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1225
[mapelement_1225]
text=Red<br>Rock
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1226
[mapelement_1226]
text=Last<br>Light
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1227
[mapelement_1227]
text=Charred<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1228
[mapelement_1228]
text=Vatrachos<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1229
[mapelement_1229]
text=Anglers'<br>Retreat
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1230
[mapelement_1230]
text=Minotaurs'<br>Rest
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1231
[mapelement_1231]
text=Isle of<br>Bones
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1232
[mapelement_1232]
text=Tear of<br>the Soul
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1233
[mapelement_1233]
text=Wintumber<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1234
[mapelement_1234]
text=Barracuda HQ
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1235
[mapelement_1235]
text=Deepfin<br>Point
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1236
[mapelement_1236]
text=The Crown<br>Jewel
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1237
[mapelement_1237]
text=Rainbow's<br>End
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1238
[mapelement_1238]
text=Sunbleak<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1239
[mapelement_1239]
text=Isle of<br>Serpents
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1240
[mapelement_1240]
text=Shimmering<br>Atoll
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1241
[mapelement_1241]
text=Laguna<br>Aurorae
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1242
[mapelement_1242]
text=Chinchompa<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1243
[mapelement_1243]
text=Port<br>Roberts
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1244
[mapelement_1244]
text=Lledrith<br>Island
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1245
[mapelement_1245]
text=Ynysdail
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1246
[mapelement_1246]
text=Buccaneers'<br>Haven
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1247
[mapelement_1247]
text=Drumstick<br>Isle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1248
[mapelement_1248]
text=The<br>Graveyard
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1249
[mapelement_1249]
text=Brittle<br>Isle
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1250
[mapelement_1250]
text=Grimstone
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1251
[mapelement_1251]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1252
[mapelement_1252]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1253
[mapelement_1253]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1254
[mapelement_1254]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1255
[mapelement_1255]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1256
[mapelement_1256]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

// 1257
[mapelement_1257]
text=Ruined<br>Village
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1258
[mapelement_1258]
text=Apsul<br>Hunting<br>Ground
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1259
[mapelement_1259]
text=Virer<br>Hunting<br>Ground
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1260
[mapelement_1260]
category=category_1056
sprite="mapfunction,6"
show=both

// 1261
[mapelement_1261]
text=Wyrmscraig<br>Cavern
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1262
[mapelement_1262]
text=Wyrmscraig
textsize=1
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1263
[mapelement_1263]
text=Ardeaglais
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1264
[mapelement_1264]
text=Auchrie
textsize=0
textcolour=0xffffff
category=category_1129
mapfunction=no

// 1265
[mapelement_1265]
category=category_1056
sprite="mapfunction,6"
mapfunction=yes
show=both

